### ISSUE TITLE
Amazon VOD addon is not working

### ISSUE THREAD

**Issue by gofirst2220** [Sandmann79/xbmc#153]
it says to see log for information and I opened the log and got this:

` ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: character mapping must return integer, None or unicode
                                            Traceback (most recent call last):
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 3, in <module>
                                                from resources.lib.startup import EntryPoint
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 6, in <module>
                                                from .network import *
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\network.py", line 19, in <module>
                                                from .logging import *
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\logging.py", line 9, in <module>
                                                g = Globals()
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\singleton.py", line 14, in __call__
                                                cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\common.py", line 70, in __init__
                                                self._globals['deviceID'] = self.genID()
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\common.py", line 104, in genID
                                                guid = hmac.new(getConfig('UserAgent'), uuid.uuid4().bytes, hashlib.sha224).hexdigest()
                                              File "C:\Program Files\Kodi\system\python\Lib\hmac.py", line 136, in new
                                                return HMAC(key, msg, digestmod)
                                              File "C:\Program Files\Kodi\system\python\Lib\hmac.py", line 75, in __init__
                                                self.outer.update(key.translate(trans_5C))
                                            TypeError: character mapping must return integer, None or unicode
                                            -->End of Python script error report<--
13:22:38.559 T:7088 WARNING: CPythonInvoker(26, C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py): the python script "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon,class XBMCAddon::xbmcgui::Dialog
13:22:38.571 T:10572   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.amazon-test/?reload=
13:22:40.263 T:18396 WARNING: Trying to add unsupported control type 1
13:22:40.279 T:556   ERROR: Window Translator: Can't find window videolibrary
13:22:40.854 T:1684   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: character mapping must return integer, None or unicode
                                            Traceback (most recent call last):
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 3, in <module>
                                                from resources.lib.startup import EntryPoint
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 6, in <module>
                                                from .network import *
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\network.py", line 19, in <module>
                                                from .logging import *
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\logging.py", line 9, in <module>
                                                g = Globals()
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\singleton.py", line 14, in __call__
                                                cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\common.py", line 70, in __init__
                                                self._globals['deviceID'] = self.genID()
                                              File "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\common.py", line 104, in genID
                                                guid = hmac.new(getConfig('UserAgent'), uuid.uuid4().bytes, hashlib.sha224).hexdigest()
                                              File "C:\Program Files\Kodi\system\python\Lib\hmac.py", line 136, in new
                                                return HMAC(key, msg, digestmod)
                                              File "C:\Program Files\Kodi\system\python\Lib\hmac.py", line 75, in __init__
                                                self.outer.update(key.translate(trans_5C))
                                            TypeError: character mapping must return integer, None or unicode
                                            -->End of Python script error report<--
13:22:40.946 T:1684 WARNING: CPythonInvoker(31, C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py): the python script "C:\Users\LAndr\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::Dialog,class XBMCAddon::xbmcaddon::Addon
13:22:40.950 T:10572   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.amazon-test/?reload=20180729182233`

Is there something you missed or needed cleaning?

**Comment by Sandmann79** [comment]
Yes there is one command at wrong place and produce this error at fresh install of addon. 
I fix this tomorrow.

**Comment by Sandmann79** [comment]
Fixed with bd2dc9af12fdddc0f9016765f2519a28e3a56bec

**Comment by AlCalzone** [comment]
Great! When can we expect it to be released?

**Comment by Sandmann79** [comment]
Just now :wink: 369e2504261da87208dcc3f75fc9853b3fdcfa1c
