### ISSUE TITLE
Widevine update fails with error

### ISSUE THREAD

**Issue by AlCalzone** [Sandmann79/xbmc#156]
Now that 0.5.6 is out, I tried to play videos from Amazon, but I always get the message that a Widevine update is required. However, after accepting the EULA, the update crashes with the following error message:

```
20:19:11.561 T:1590670192 WARNING: CPythonInvoker(16, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE
20:19:11.572 T:1939529744   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.amazon-test/?asin=B015NZ83EG&mode=PlayVideo&adult=0&name=1+-+Pilot&trailer=0&selbitrate=0]
20:20:10.319 T:1590670192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: [Errno 12] Cannot allocate memory
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 68, in EntryPoint
                                                PlayVideo(args.get('name', ''), args.get('asin'), args.get('adult', '0'), int(args.get('trailer', '0')), int(args.get('selbitrate', '0')))
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 579, in PlayVideo
                                                playable = _IStreamPlayback(asin, name, trailer, isAdult, extern)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 459, in _IStreamPlayback
                                                if not inputstream_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 763, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 741, in _check_drm
                                                return self._check_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 655, in _check_widevine
                                                return self._install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 542, in _install_widevine
                                                return self._install_widevine_arm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 485, in _install_widevine_arm
                                                if not self._cmd_exists('fdisk') and not self._cmd_exists('parted'):
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 164, in _cmd_exists
                                                return subprocess.call('type ' + cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE) == 0
                                              File "/usr/lib/python2.7/subprocess.py", line 172, in call
                                              File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
                                              File "/usr/lib/python2.7/subprocess.py", line 938, in _execute_child
                                            OSError: [Errno 12] Cannot allocate memory
                                            -->End of Python script error report<--
20:20:10.486 T:1590670192 WARNING: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
20:20:10.499 T:1939529744   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.amazon-test/?asin=B015X5GVZO&mode=PlayVideo&adult=0&name=2+-+A+Stray+Howl&trailer=0&selbitrate=0]
```

I'm using LibreElec 9 on a RPi 3 if that helps somehow.

**Comment by AlCalzone** [comment]
Is there another way to update this lib? I've tried
```curl -Ls http://nmacleod.com/public/libreelec/getwidevine.sh | bash```
as mentioned [here](https://forum.kodi.tv/showthread.php?tid=298461) but that doesn't make the update dialog go away.

**Comment by Varstahl** [comment]
You can manually download the current latest zip for [x86](https://dl.google.com/widevine-cdm/1.4.9.1088-linux-ia32.zip) or [x64](https://dl.google.com/widevine-cdm/1.4.9.1088-linux-x64.zip) architecture, and then manually replace `~/.kodi/cdm/libwidevinecdm.so`.

**Comment by Sandmann79** [comment]
This won't work @Varstahl. You need an armv7 library on RPi devices. This is included at Google ChromeOS images.
@AlCalzone Follow this guide to update it manually: https://forum.kodi.tv/showthread.php?tid=298461&pid=2741584#pid2741584

BTW this issue is not really addon related. You should open an issue at https://github.com/emilsvennesson/script.module.inputstreamhelper

**Comment by Varstahl** [comment]
Whops, I confused the threads, I'm sorry.

**Comment by AlCalzone** [comment]
I opened an issue in the repo you linked and tried the manual installation of the lib as described in the link you posted. Sandly that didn't work either. I'm still getting "an update of Widevine CDM is required to play this content".

**Comment by Sandmann79** [comment]
You'll always get this message till inputstream helper finished the update. But you can cancel it and should be able to play videos.

**Comment by AlCalzone** [comment]
> But you can cancel it and should be able to play videos.

Care to elaborate how I do that? I get the message that I should update, there I can press [OK].
Then I get asked if I want to extract something from ChromeOS, with the options [Yes] and [No]. Yes gives the error, No cancels the playback.

**Comment by mirh** [comment]
I updated wv this morning, with no problem whatsoever (on windows).

**Comment by Varstahl** [comment]
As far as I know the latest update on LibreElec have fixed all the issues, and Amazon VOD 0.5.8 which I just released to the public should fix the issues with their servers. Any update? Is this fixed by now?

**Comment by Varstahl** [comment]
Closing for inactivity but tests with LibreElec report it as working.

**Comment by cassiel74** [comment]
Well, I am on LibreElec and something is not working

> > ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.OSError'>
>                                             Error Contents: [Errno 12] Cannot allocate memory
>                                             Traceback (most recent call last):
>                                               File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
>                                                 EntryPoint()
>                                               File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
>                                                 g.pv.Browse(None if 'path' not in args else args['path'])
>                                               File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 185, in Browse
>                                                 PlayVideo(self._videodata[nodeName]['metadata']['video'], self._videodata[nodeName]['metadata']['asin'], '', 0)
>                                               File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 587, in PlayVideo
>                                                 playable = _IStreamPlayback(asin, name, trailer, isAdult, extern)
>                                               File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 469, in _IStreamPlayback
>                                                 if not inputstream_helper.check_inputstream():
>                                               File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 763, in check_inputstream
>                                                 return self._check_drm()
>                                               File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 741, in _check_drm
>                                                 return self._check_widevine()
>                                               File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 663, in _check_widevine
>                                                 if self._missing_widevine_libs():
>                                               File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 613, in _missing_widevine_libs
>                                                 if self._cmd_exists('ldd'):
>                                               File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 164, in _cmd_exists
>                                                 return subprocess.call('type ' + cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE) == 0
>                                               File "/usr/lib/python2.7/subprocess.py", line 168, in call
>                                               File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
>                                               File "/usr/lib/python2.7/subprocess.py", line 916, in _execute_child
>                                             OSError: [Errno 12] Cannot allocate memory

**Comment by Varstahl** [comment]
> Well, I am on LibreElec and something is not working
> > `OSError: [Errno 12] Cannot allocate memory`

@cassiel74 you ran out of RAM on the device, that has nothing to do with the addon nor us.

@AlCalzone don't worry, no biggie, but thanks for the confirmation :)
