### ISSUE TITLE
Can't play exported movies

### ISSUE THREAD

**Issue by snoopyjoe** [Sandmann79/xbmc#159]
I noticed a bug that starts in v0.5.5. Any movie exported and scanned to the library cannot be played from Kodi library.  A movie can played from within the addon and from the export folder by clicking the .strm file, but playing from the Kodi library gives an Amazon VOD error. This is a weird bug as it does not affect exported TV shows. 
I'm running CoreELEC 8.95.0 Kodi v18 beta1 compiled 8/6/18. Here is the full [Log File](https://pastebin.com/Km9cqMHV).

01:18:55.289 T:3369399152  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.2.24.0
01:18:55.291 T:3369399152   DEBUG: [Amazon VOD] 668
01:18:55.372 T:3369399152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'episodedetails'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 68, in EntryPoint
                                                PlayVideo(args.get('name', ''), args.get('asin'), args.get('adult', '0'), int(args.get('trailer', '0')), int(args.get('selbitrate', '0')))
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 579, in PlayVideo
                                                playable = _IStreamPlayback(asin, name, trailer, isAdult, extern)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 547, in _IStreamPlayback
                                                player.resolve(listitem)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 720, in resolve
                                                if not self.checkResume():
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/playback.py", line 742, in checkResume
                                                position = int(result['episodedetails']['resume']['position'])
                                            KeyError: u'episodedetails'
                                            -->End of Python script error report<--
01:18:55.372 T:3369399152   DEBUG: onExecutionDone(26, /storage/.kodi/addons/plugin.video.amazon-test/default.py)

**Comment by ASHJG** [comment]
I also have this issue.

**Comment by Sandmann79** [comment]
I'll fix this soon. This should only happens on movies.
