### ISSUE TITLE
Search fails

### ISSUE THREAD

**Issue by ido-ran** [Sandmann79/xbmc#174]
Recently when I try to search in Amazon VOD plugin I get a failure message. It used to work before and I didn't update the plugin since.
Similar (or maybe identical) failure occurs when I try to browse any other TV Show or Movie.

I'm running version `0.5.7`.
I use Rpi3
LibreElec version `devel-20180429210303-#0429`
Kodi `18.0-ALPHA2` Git:`cd6c3fa`

This is the log since I've open the plugin for the search.

```
20:49:51.179 T:1940431440   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
20:49:56.891 T:1442837360 WARNING: CAddonSettings[plugin.video.amazon-test]: failed to load value "" for setting episodeid
20:49:56.891 T:1442837360 WARNING: CAddonSettings[plugin.video.amazon-test]: failed to load value "" for setting movieid
20:49:56.891 T:1442837360 WARNING: CAddonSettings[plugin.video.amazon-test]: failed to load value "" for setting pin
20:49:56.891 T:1442837360 WARNING: CAddonSettings[plugin.video.amazon-test]: failed to load value "" for setting seasonid
20:49:56.891 T:1442837360 WARNING: CAddonSettings[plugin.video.amazon-test]: failed to load value "" for setting showid
20:49:56.892 T:1442837360  NOTICE: [Amazon VOD] {'mode': 'PrimeVideo_Search'}
20:50:04.392 T:1442837360  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/search/ref=atv_nb_sr?ie=UTF8&phrase=paw
20:50:06.210 T:1442837360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 85, in EntryPoint
                                                g.pv.Search()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 148, in Search
                                                self.Browse('search', xbmcplugin.SORT_METHOD_NONE)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 177, in Browse
                                                self._LazyLoad(node, nodeName)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 441, in _LazyLoad
                                                results = re.search(r'<section\s+[^>]*class="[^"]*av-detail-section[^"]*"[^>]*>\s*(.*?)\s*</section>', cnt, flags=re.DOTALL).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
20:50:06.445 T:1442837360 WARNING: CPythonInvoker(59, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
20:50:06.460 T:1940431440   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/?mode=PrimeVideo_Search
20:50:06.462 T:1940431440   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/?mode=PrimeVideo_Search) failed

```

This is the log for the TV Show browsing.

```
20:57:05.303 T:1442837360  NOTICE: [Amazon VOD] {'path': 'root-//-TV Shows', 'mode': 'PrimeVideo_Browse'}
20:57:05.370 T:1442837360  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/storefront/tv/ref=atv_nb_sf_tv?_encoding=UTF8&format=json
20:57:30.082 T:1442837360  NOTICE: [Amazon VOD] PIMS: {u'title': u'Watch Next TV'} [] Paw Patrol Season 1 https://images-eu.ssl-images-amazon.com/images/S/sgp-catalog-images/boxart_images/56cf080c-5f12-4ded-90e1-0dbcf780abb1-28b6c89f-0f7f-4986-813e-8d397201ff75_RGB_SD._UR267,200_FMJPG_.jpg https://www.primevideo.com/detail/0NU8EKJ5WY0MT1FX8MUX8RWY1Y/ref=atv_tv_hom_c_1H6noD_2_1
20:57:30.084 T:1442837360  NOTICE: [Amazon VOD] PIMS: {u'0NU8EKJ5WY0MT1FX8MUX8RWY1Y': {}, u'title': u'Watch Next TV'} [] Seinfeld, Season 1 https://images-eu.ssl-images-amazon.com/images/S/sgp-catalog-images/boxart_images/3cef4312-bd87-4ce9-aa30-3d5a59b6b0ac-a61a96dc-118f-4325-b8f6-cc5ea9894631_RGB_SD._UR267,200_FMJPG_.jpg https://www.primevideo.com/detail/0TVLMR2QYSI7PGPEVQW3KOO4TR/ref=atv_tv_hom_c_1H6noD_2_2
20:57:34.538 T:1442837360  NOTICE: [Amazon VOD] {'path': 'root-//-TV Shows-//-Kids & Family TV', 'mode': 'PrimeVideo_Browse'}
20:57:34.593 T:1442837360  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/search/ref=atv_tv_hom_c_kstdee_10_smr?_encoding=UTF8&ie=UTF8&phrase=&query=p_n_entity_type%3DTV%20Show%26search-alias%3Dinstant-video%26index%3Deu-amazon-video-other%26adult-product%3D0%26bq%3D%28and%20sort%3A%27featured-rank%27%20%28and%20%28and%20%28or%20av_primary_genre%3A%27av_genre_kids%27%29%20%28not%20av_secondary_genre%3A%27av_subgenre_international_india%27%29%29%20%28not%20%28or%20regulatory_rating%3A%2718%20%27%20regulatory_rating%3A%27nr%27%29%29%29%29%26av_offered_in_territory%3DIL%26qs-av_request_type%3D4%26qs-is-prime-customer%3D2
20:57:35.530 T:1442837360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 177, in Browse
                                                self._LazyLoad(node, nodeName)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 441, in _LazyLoad
                                                results = re.search(r'<section\s+[^>]*class="[^"]*av-detail-section[^"]*"[^>]*>\s*(.*?)\s*</section>', cnt, flags=re.DOTALL).group(1)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
20:57:35.719 T:1442837360 WARNING: CPythonInvoker(61, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
20:57:35.720 T:1940431440   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-TV%20Shows-%2f%2f-Kids%20%26%20Family%20TV
20:57:35.722 T:1940431440   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-TV%20Shows-%2f%2f-Kids%20%26%20Family%20TV) failed
```

**Comment by Varstahl** [comment]
The addon isn't working as of last week, after Amazon changed its UI. That might be the reason why it's not working at the moment. You can try grabbing the latest [primevideo.py](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/resources/lib/primevideo.py) from the master repo, and try again. There are also a number of weird errors:

```
WARNING: CAddonSettings[plugin.video.amazon-test]: failed to load value "" for setting episodeid
WARNING: CAddonSettings[plugin.video.amazon-test]: failed to load value "" for setting movieid
WARNING: CAddonSettings[plugin.video.amazon-test]: failed to load value "" for setting pin
WARNING: CAddonSettings[plugin.video.amazon-test]: failed to load value "" for setting seasonid
WARNING: CAddonSettings[plugin.video.amazon-test]: failed to load value "" for setting showid
```

either a connection failed before this, or there might be some big problem in the cached data. At the moment I don't know which is which, but if you have version 0.5.7 it won't work 100%.

**Comment by Varstahl** [comment]
If you want to test, as of 57dcecda1d34526d131f13c374242fc3bddd0bce everything should be fixed and/or improved. You can grab the primevideo.py from the master, I want to wait another couple days before pushing the release to see if Amazon breaks everything once more.

**Comment by ido-ran** [comment]
It looks like this solve the issue.
Thanks
