### ISSUE TITLE
Unable to play http error

### ISSUE THREAD

**Issue by jgmGit** [Sandmann79/xbmc#204]
I am getting the following error when I try to play videos. I am using version 0.6.2 and Kodi version 18.0-RC1

I found the following errors in the log. How to fix it ?

```
12:53:26.361 T:1473766256 WARNING: CPythonInvoker(18, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
12:53:26.758 T:1791984496  NOTICE: [Amazon VOD] Service: Start
12:53:26.768 T:1791984496  NOTICE: [Amazon VOD] Service: End
12:53:26.935 T:1791984496 WARNING: CPythonInvoker(19, /storage/.kodi/addons/plugin.video.amazon-test/service.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE
12:53:43.285 T:1699664752  NOTICE: [Amazon] AmazonDB: Starting DBUpdate (1970-01-01 00:00:00 / 2018-11-11 12:53:43.283762)
12:53:44.604 T:1938046496   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
12:53:44.609 T:1791984496  NOTICE: [Amazon] Args: {'sitemode': 'updateAll', 'mode': 'appfeed'}
12:53:44.808 T:1791984496  NOTICE: [Amazon] Login
12:53:49.451 T:1473766256  NOTICE: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=424de7f640796e72e238b9c6ca3246bcf22036995220b1b3f173cc89&format=json&version=2&formatVersion=3&marketplaceId=A1PA6795UKMFR9&IncludeAll=T&AID=1&OfferGroups=B0043YVHMY&ContentType=TVEpisode&RollupToSeason=T&OrderBy=MostPopular&NumberOfResults=40&StartIndex=0&Detailed=T&mobileClient=true
12:53:53.401 T:1473766256  NOTICE: [Amazon VOD] Starting Fanart Update
12:53:53.506 T:1473766256  NOTICE: [Amazon VOD] Finished Fanart Update
12:53:56.425 T:1473766256  NOTICE: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=424de7f640796e72e238b9c6ca3246bcf22036995220b1b3f173cc89&format=json&version=2&formatVersion=3&marketplaceId=A1PA6795UKMFR9&IncludeAll=T&AID=1&version=2&SeasonASIN=B07HF73RK2,B07HF78RRM,B07HF7ZQQD,B07HF8BQDR&OfferGroups=B0043YVHMY&IncludeAll=T&AID=T&Detailed=T&tag=1&ContentType=TVEpisode&IncludeBlackList=T&NumberOfResults=40&StartIndex=0&Detailed=T&mobileClient=true
12:53:58.913 T:1473766256  NOTICE: [Amazon VOD] Starting Fanart Update
12:53:59.004 T:1473766256  NOTICE: [Amazon VOD] Finished Fanart Update
12:54:01.474 T:1473766256  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.amazon.de/cdp/catalog/GetPlaybackResources?asin=B07HNLJ64D&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=424de7f640796e72e238b9c6ca3246bcf22036995220b1b3f173cc89&marketplaceID=A1PA6795UKMFR9&format=json&version=1&gascEnabled=false&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives&supportedDRMKeyScheme=DUAL_KEY
12:54:01.565 T:1473766256  NOTICE: [Amazon VOD] Error 403
12:54:01.566 T:1473766256   ERROR: [Amazon VOD] Error reason: 429 (HTTPError)
12:54:11.567 T:1473766256  NOTICE: [Amazon VOD] Attempt #2. Too many requests - Pause 10 sec
12:54:11.569 T:1473766256  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.amazon.de/cdp/catalog/GetPlaybackResources?asin=B07HNLJ64D&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=424de7f640796e72e238b9c6ca3246bcf22036995220b1b3f173cc89&marketplaceID=A1PA6795UKMFR9&format=json&version=1&gascEnabled=false&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives&supportedDRMKeyScheme=DUAL_KEY
12:54:11.659 T:1473766256  NOTICE: [Amazon VOD] Error 403
12:54:11.660 T:1473766256   ERROR: [Amazon VOD] Error reason: 429 (HTTPError)
12:54:21.661 T:1473766256  NOTICE: [Amazon VOD] Attempt #3. Too many requests - Pause 10 sec
12:54:21.663 T:1473766256  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.amazon.de/cdp/catalog/GetPlaybackResources?asin=B07HNLJ64D&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=424de7f640796e72e238b9c6ca3246bcf22036995220b1b3f173cc89&marketplaceID=A1PA6795UKMFR9&format=json&version=1&gascEnabled=false&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives&supportedDRMKeyScheme=DUAL_KEY
12:54:21.750 T:1473766256  NOTICE: [Amazon VOD] Error 403
12:54:21.751 T:1473766256   ERROR: [Amazon VOD] Error reason: 429 (HTTPError)
12:54:21.810 T:1938046496  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B07HNLJ64D&mode=PlayVideo&adult=0&name=4+-+Entfesselt+die+Bestie&trailer=0&selbitrate=0
```

**Comment by jgmGit** [comment]
I was not able to fix it. So I tried to uninstall and reinstall it  again. Now there is a new error.
After I enter the user name and password. Then it comes to a second screen where it asks for username, password and and a captcha. I get another error when i enter those. I retried it several time, still the same error.

The following is the log.
```

13:39:38.570 T:1938296352   DEBUG: Previous line repeats 8 times.
13:39:38.570 T:1938296352   DEBUG: ------ Window Deinit (Pointer.xml) ------
13:39:45.716 T:1928328048   DEBUG: libinput: event5  - debounce state: DEBOUNCE_STATE_IS_UP → DEBOUNCE_EVENT_PRESS → DEBOUNCE_STATE_DOWN_WAITING
13:39:45.717 T:1928328048   DEBUG: CLibInputPointer::ProcessButton - event.type: 4, event.button.button: 1, event.button.x: 931, event.button.y: 874
13:39:45.741 T:1928328048   DEBUG: libinput: event5  - debounce state: DEBOUNCE_STATE_DOWN_WAITING → DEBOUNCE_EVENT_TIMEOUT → DEBOUNCE_STATE_IS_DOWN
13:39:45.812 T:1928328048   DEBUG: libinput: event5  - debounce state: DEBOUNCE_STATE_IS_DOWN → DEBOUNCE_EVENT_RELEASE → DEBOUNCE_STATE_RELEASE_WAITING
13:39:45.813 T:1928328048   DEBUG: CLibInputPointer::ProcessButton - event.type: 5, event.button.button: 1, event.button.x: 931, event.button.y: 874
13:39:45.824 T:1928328048   DEBUG: libinput: event5  - debounce state: DEBOUNCE_STATE_RELEASE_WAITING → DEBOUNCE_EVENT_TIMEOUT_SHORT → DEBOUNCE_STATE_RELEASED
13:39:45.837 T:1928328048   DEBUG: libinput: event5  - debounce state: DEBOUNCE_STATE_RELEASED → DEBOUNCE_EVENT_TIMEOUT → DEBOUNCE_STATE_IS_UP
13:39:45.837 T:1938296352   DEBUG: ProcessMouse: trying mouse action leftclick
13:39:45.845 T:1938296352   DEBUG: ------ Window Init (Pointer.xml) ------
13:39:45.954 T:1938296352   DEBUG: ------ Window Deinit () ------
13:39:46.247 T:1808769904   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'mechanize._form.AmbiguityError'>
                                            Error Contents: more than one control matching name u'email'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 89, in EntryPoint
                                                exec '%s()' % mode
                                              File "<string>", line 1, in <module>
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 474, in LogIn
                                                br = _MFACheck(br, email, soup)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 336, in _MFACheck
                                                br['email'] = wnd.email
                                              File "/storage/.kodi/addons/script.module.mechanize/lib/mechanize/_form.py", line 2780, in __setitem__
                                                control = self.find_control(name)
                                              File "/storage/.kodi/addons/script.module.mechanize/lib/mechanize/_form.py", line 3101, in find_control
                                                return self._find_control(name, type, kind, id, label, predicate, nr)
                                              File "/storage/.kodi/addons/script.module.mechanize/lib/mechanize/_form.py", line 3183, in _find_control
                                                raise AmbiguityError("more than one control matching "+description)
                                            AmbiguityError: more than one control matching name u'email'
                                            -->End of Python script error report<--
13:39:46.248 T:1808769904   DEBUG: onExecutionDone(13, /storage/.kodi/addons/plugin.video.amazon-test/default.py)
```

**Comment by Sandmann79** [comment]
Please enable verbose logging at addons settings -> miscellaneous.
After that, login again and upload `/storage/.kodi/avod-login.log` here.
This log is just the HTML response from Amazons signin page, so you have to remove your email/password from it.

**Comment by jgmGit** [comment]
Thanks for the response. Please find the log file attached.
[avod-login.log](https://github.com/Sandmann79/xbmc/files/2569778/avod-login.log)

**Comment by jgmGit** [comment]
Finally I figured out what was the issue. I had updated the password of my amazon account and I didn't update it in the plugin. That is why I was getting all the errors. When I used the correct password it worked. 

Maybe proper error messages in the plugin would be helpful to identify if it is a user name / password issue.

Sorry for all the trouble.

**Comment by Sandmann79** [comment]
There already error checks included, but Amazon changed recently their signin page with an second form field.  There is now an register and login field and this breaks the Addon at this point.
This will be fixed in the near future.

**Comment by Sandmann79** [comment]
@oomek see answer above https://github.com/Sandmann79/xbmc/issues/204#issuecomment-437665775

**Comment by Sandmann79** [comment]
This should be fixed with the latest release
