### ISSUE TITLE
plugin.video.amazon - mysql: possible timeout?

### ISSUE THREAD

**Issue by hawkeyexp** [Sandmann79/xbmc#209]
After a full update of db which took a long time i got this:

```
14:40:51.428 T:7316   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
        - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <class 'mysql.connector.errors.OperationalError'>
    Error Contents: MySQL Connection not available.
    Traceback (most recent call last):
        File "C:\Users\hawkeye\AppData\Roaming\Kodi\addons\plugin.video.amazon\default.py", line 52, in <module>
        modes()
        File "C:\Users\hawkeye\AppData\Roaming\Kodi\addons\plugin.video.amazon\default.py", line 49, in modes
        exec 'sitemodule.%s()' % var.args.get('sitemode')
        File "<string>", line 1, in <module>
        File "C:\Users\hawkeye\AppData\Roaming\Kodi\addons\plugin.video.amazon\resources\lib\appfeed.py", line 353, in updateAll
        mvresult = movies.addMoviesdb(False, cj=cj)
        File "C:\Users\hawkeye\AppData\Roaming\Kodi\addons\plugin.video.amazon\resources\lib\movies.py", line 124, in addMoviesdb
        MOVIE_ASINS = getMoviedbAsins(retlist=True)
        File "C:\Users\hawkeye\AppData\Roaming\Kodi\addons\plugin.video.amazon\resources\lib\movies.py", line 93, in getMoviedbAsins
        c = MovieDB.cursor()
        File "C:\Users\hawkeye\AppData\Roaming\Kodi\addons\script.module.myconnpy\lib\mysql\connector\connection.py", line 1231, in cursor
        raise errors.OperationalError("MySQL Connection not available.")
    OperationalError: MySQL Connection not available.
    -->End of Python script error report<--
```

I think it is a timeout caused by long connection and results in not completing full update.

The check of the mysql is fine and all running and accessible.

**Comment by Varstahl** [comment]
Stale issue, 1 year of inactivity on both ends, closing this for the moment as this might not be relevant anymore.
