### ISSUE TITLE
Amazon broke Watchlist again

### ISSUE THREAD

**Issue by sirisfir** [Sandmann79/xbmc#231]
RPi3, Libreelec, Kodi 18.

Added "The Grand Tour" to Watchlist. Clicking TV Shows from Watchlist throws:

```
13:46:17.365 T:1599927152  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/detail/0U8EQ8DRAGDYW8WQP5R1USHCJQ/ref=atv_wtlp_wtl_1
13:46:18.562 T:1599927152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'parent'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 189, in Browse
                                                self._LazyLoad(node, nodeName)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 735, in _LazyLoad
                                                o[self._videodata[refUrn]['parent']] = self._videodata[self._videodata[refUrn]['parent']]
                                            KeyError: u'parent'
                                            -->End of Python script error report<--
13:46:18.709 T:1599927152 WARNING: CPythonInvoker(5, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left sever
al classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
13:46:18.719 T:1707008880   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-Watchlist-%2f%2f-TV%20Shows
13:46:18.721 T:1937468960   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-%2f%2f-Watchlist-%2f%2f-TV%20Shows) failed
```

Deleted *.pvcp and *.pvdp, restarted. Earlier on I could only see 1 entry in the list, now it crashes on just clicking TV Shows

**Comment by Varstahl** [comment]
That's pretty strange, I'll have to look into it.

**Comment by Varstahl** [comment]
Amazon broke the website and the watchlist. Will need to address the issue.

**Comment by Varstahl** [comment]
Sorry @sirisfir, your comment slipped by me. Due to the changes in amazon's back end, the video data that was previously cached has been rendered useless. You need to locate and manually remove them: [FAQ answer](https://github.com/Sandmann79/xbmc/wiki/FAQ#where-are-kodis-logs--where-are-the-addons-cache-files).
