### ISSUE TITLE
Error when using the option "browse for subtitles"

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#233]
Whenever I select the option "browse for subtitles" in order to load subtitles from the folder I set in the kodi preferences for external subtitles (the folder is in a samba share), there's an error from Amazon VOD. The option works fine though.

The log says this:
```

18:17:48.212 T:205795820784   DEBUG: CMultiPathDirectory::GetDirectory(multipath://plugin%3a%2f%2fplugin.video.amazon-test%2f%3fmode%3dPrimeVideo_Browse%26path%3droot-%2f%2f-Watchlist-%2f%2f-Pel%25C3%25ADculas-%2f%2f/smb%3a%2f%2fBOX%2fdownload%2fSubtitulos%2f/)
18:17:48.212 T:205795820784   DEBUG: Getting Directory (plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-//-Watchlist-//-Pel%C3%ADculas-//)
18:17:48.213 T:205795820784   DEBUG: StartScript - calling plugin Amazon VOD('plugin://plugin.video.amazon-test/','1','?mode=PrimeVideo_Browse&path=root-//-Watchlist-//-Pel%C3%ADculas-//','resume:false')
18:17:48.215 T:205795820784   DEBUG: GetLanguageInvoker - Reusing LanguageInvokerThread 5 for script /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/default.py
18:17:48.215 T:206005404912    INFO: initializing python engine.
18:17:48.215 T:206005404912   DEBUG: CPythonInvoker(5, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/default.py): start processing
18:17:48.215 T:206005404912   DEBUG: CPythonInvoker(5, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/default.py): entering source directory /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test
18:17:48.216 T:206005404912   DEBUG: CPythonInvoker(5, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/default.py): instantiating addon using automatically obtained id of "plugin.video.amazon-test" dependent on version 2.24.0 of the xbmc.python api
18:17:48.217 T:206005404912   DEBUG: [Amazon VOD] {'path': 'root-//-Watchlist-//-Pel\xc3\xadculas-//', 'mode': 'PrimeVideo_Browse'}
18:17:48.223 T:206005404912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'Pel\xedculas-//'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 181, in Browse
                                                node = node[n]
                                            KeyError: u'Pel\xedculas-//'
                                            -->End of Python script error report<--

```

**Comment by Varstahl** [comment]
I'm not sure what happened, but there's a part of the path missing. The URI is cut short. That's impossible for it to happen on the addon by itself. Did you install something recently?

**Comment by Varstahl** [comment]
Then I need you to tell me exactly what you do, step by step. If you load the video, which buttons/menus you select, etc.

**Comment by Paco8** [comment]
I start to play a movie, then I press OK and then I select the subtitle option in the control bar, and then I select  "browse for subtitles". At this point a window opens so that I can select the subtitle file, just when that window opens I get a notification about an error from Amazon VOD. 
Anyway I still can select the subtitle file, and it loads and works ok.

**Comment by Varstahl** [comment]
I'm unable to reproduce the issue, but [this primevideo.py](https://github.com/Varstahl/xbmc/blob/5e9cc48eb9f50d4ee372860f1ada600fb599d131/plugin.video.amazon-test/resources/lib/primevideo.py) should fix the problem. Can you test it out for me?

**Comment by Paco8** [comment]
Yes, the problem seems fixed. Thank you.
