### ISSUE TITLE
Crash when trying to use a TV show added to Kodi's favourites

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#244]
I do this: in the Amazon VOD I enter in the watchlist, shows. Then I add one of the shows to the Kodi favourites with the context menu. I go back to the Kodi main screen, go to the Favourites section. The show I added is there, I enter in it and it lists the episodes of the show. All correct.

However some hours later (maybe when the catalog cache has expired): I open Kodi, go to the Favourites section, try to enter in the show but now I get an error and the episodes are no shown.

This is the error in the log:

```
22:17:40.592 T:162432050416   DEBUG: [Amazon VOD] {'path': 'root-!!-Watchlist-!!-Series-!!-amzn1.dv.gti.70b0291b-c1c4-9912-8215-86457dfafd47', 'mode': 'PrimeVideo_Browse'}
22:17:40.835 T:162432050416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'root'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
                                                g.pv.Browse(None if 'path' not in args else args['path'])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 218, in Browse
                                                node = node[n]
                                            KeyError: u'root'
                                            -->End of Python script error report<--
22:17:40.835 T:162432050416   DEBUG: onExecutionDone(5, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/default.py)
22:17:40.839 T:162198381808   DEBUG: ------ Window Init (DialogNotification.xml) ------

```
I'm using the latest version of the addon (0.6.6)

**Comment by Varstahl** [comment]
Hmm, I actually never thought of that. It's possible that the cache expired and by accessing externally it obviously doesn't find any cache to begin with. I'll have to look into this, it probably needs some work.
