### ISSUE TITLE
What is InputStream plugin is not available ?

### ISSUE THREAD

**Issue by vasundhar** [Sandmann79/xbmc#25]
I am trying to use it on OSMC on raspberry pi3 .
I am getting this error InputStream is not available. 
Should I switch to some other mode? 
If so what you recommend that certainly works ?

**Comment by Sandmann79** [comment]
That error message appears, if no inptutstream addon (e.g. inputstream.adaptive) is activated.
You can check this in Main Menu at Addons -> My add-ons -> Videoplayer Inputstream.

On RasPi is no other playback method available.

**Comment by vasundhar** [comment]
Following are the Errors I received from kodi.log 

 Executing: Browser or Script not found. Please check settings.
00:58:20 1139.455933 T:1713259504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: [Errno 2] No such file or directory
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 2091, in <module>
                                                PlayVideo(args.get('name'), args.get('asin'), args.get('adult'), args.get('trailer'))
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 972, in PlayVideo
                                                ExtPlayback(videoUrl, asin, isAdult, methodOW)
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 1007, in ExtPlayback
                                                process = subprocess.Popen(args, stdout=subprocess.PIPE)
                                              File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
                                                errread, errwrite)
                                              File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
                                                raise child_exception
                                            OSError: [Errno 2] No such file or directory
                                            -->End of Python script error report<--

**Comment by Sandmann79** [comment]
As i wrote above, for RasPi's are no other playback or fallback methods available, except Inputstream. 

This error indicates that no browser or script (depends on your settings) is found, so you have to select it manually at settings.
