### ISSUE TITLE
Can't play some movies

### ISSUE THREAD

**Issue by socket462** [Sandmann79/xbmc#277]
Dear contributors,

I would like to submit this issue.
It is my first issue so please help me fix it if there is need to.

I am able to browse through TV shows and play them just fine.

The problem is with movies. I can browse the list (most of the times) and play some of them, but there are some movies that do not start to play:

I already tried to clear the cache (*.pvcp and *.pvdp files)

Here is the relevant log (I think):

```
2019-03-03 17:47:00.795 T:1574425456  NOTICE: [Amazon VOD] http://127.0.0.1:35507/mpd/https%3A%2F%2Fs3-dub-ww.cf.dash.row.aiv-cdn.net%2Fdm%2F2%243VxEjAoeWY76MWvfpm35WhuYJ4s%2Fb449%2F55e4%2Ff4d4%2F4efe-a383-aed16dcc7723%2F6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd
2019-03-03 17:47:00.905 T:1574425456  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 999.2.3.13
2019-03-03 17:47:01.311 T:1936955856  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=search-!!-0TN3WP93H2FAWUR79B7T1OSBYV
2019-03-03 17:47:01.314 T:1473241968  NOTICE: Creating InputStream
2019-03-03 17:47:01.487 T:1436545904  NOTICE: [Amazon VOD] [PS] Requested GET path [u'mpd', u'https%3A%2F%2Fs3-dub-ww.cf.dash.row.aiv-cdn.net%2Fdm%2F2%243VxEjAoeWY76MWvfpm35WhuYJ4s%2Fb449%2F55e4%2Ff4d4%2F4efe-a383-aed16dcc7723%2F6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd']
2019-03-03 17:47:01.504 T:1436545904  NOTICE: [Amazon VOD] [PS] Forwarding the get request towards https://s3-dub-ww.cf.dash.row.aiv-cdn.net/dm/2$3VxEjAoeWY76MWvfpm35WhuYJ4s/b449/55e4/f4d4/4efe-a383-aed16dcc7723/6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd
2019-03-03 17:47:01.634 T:1436545904   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
2019-03-03 17:47:17.936 T:1436545904   ERROR: Traceback (most recent call last):
2019-03-03 17:47:17.936 T:1436545904   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2019-03-03 17:47:17.953 T:1436545904   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2019-03-03 17:47:17.953 T:1436545904   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2019-03-03 17:47:17.953 T:1436545904   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2019-03-03 17:47:17.954 T:1436545904   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2019-03-03 17:47:17.954 T:1436545904   ERROR:   File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 148, in do_GET
2019-03-03 17:47:17.956 T:1436545904   ERROR:     self._AlterMPD(unquote(path[1]), headers, data)
2019-03-03 17:47:17.956 T:1436545904   ERROR:   File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 257, in _AlterMPD
2019-03-03 17:47:17.957 T:1436545904   ERROR:     self._SendResponse(status_code, headers, header + ''.join(new_sets) + footer, True)
2019-03-03 17:47:17.957 T:1436545904   ERROR: MemoryError
2019-03-03 17:47:18.022 T:1473241968   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
2019-03-03 17:47:18.025 T:1473241968   ERROR: CCurlFile::Open failed with code 0 for http://127.0.0.1:35507/mpd/https%3A%2F%2Fs3-dub-ww.cf.dash.row.aiv-cdn.net%2Fdm%2F2%243VxEjAoeWY76MWvfpm35WhuYJ4s%2Fb449%2F55e4%2Ff4d4%2F4efe-a383-aed16dcc7723%2F6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd:
2019-03-03 17:47:18.037 T:1473241968   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://127.0.0.1:35507/mpd/https%3A%2F%2Fs3-dub-ww.cf.dash.row.aiv-cdn.net%2Fdm%2F2%243VxEjAoeWY76MWvfpm35WhuYJ4s%2Fb449%2F55e4%2Ff4d4%2F4efe-a383-aed16dcc7723%2F6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd
2019-03-03 17:47:18.076 T:1473241968   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://127.0.0.1:35507/mpd/https%3A%2F%2Fs3-dub-ww.cf.dash.row.aiv-cdn.net%2Fdm%2F2%243VxEjAoeWY76MWvfpm35WhuYJ4s%2Fb449%2F55e4%2Ff4d4%2F4efe-a383-aed16dcc7723%2F6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd)
2019-03-03 17:47:18.102 T:1473241968   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=search-!!-0TN3WP93H2FAWUR79B7T1OSBYV]
2019-03-03 17:47:18.102 T:1473241968  NOTICE: CVideoPlayer::OnExit()
2019-03-03 17:47:19.387 T:1936955856  NOTICE: CVideoPlayer::CloseFile()
2019-03-03 17:47:19.387 T:1936955856  NOTICE: VideoPlayer: waiting for threads to exit
2019-03-03 17:47:19.387 T:1936955856  NOTICE: VideoPlayer: finished waiting
2019-03-03 17:47:19.403 T:1936955856 WARNING: OnMessage: Suspiciously long time to handle GUI_MSG_PLAYBACK_STARTED (18.06s)
2019-03-03 17:47:19.441 T:1574425456  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/usage/UpdateStream?asin=amzn1.dv.gti.f4aff811-0adf-82ef-b9d8-b218150d7797&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=3cc6a1f7735a55535c8d7532ce4d9112ac559040bea5b77eea316369&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&subtitleFormat=TTMLv2&event=STOP&timecode=0.0
2019-03-03 17:47:19.457 T:1574425456   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
2019-03-03 17:47:56.208 T:1908773744  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:1102)
2019-03-03 17:50:37.161 T:1936955856  NOTICE: stop player
2019-03-03 17:50:37.162 T:1936955856  NOTICE: Storing total System Uptime
2019-03-03 17:50:37.162 T:1936955856  NOTICE: Saving settings
2019-03-03 17:50:38.733 T:1936955856  NOTICE: Saving skin settings
2019-03-03 17:50:39.398 T:1936955856  NOTICE: stop all
2019-03-03 17:50:39.399 T:1936955856  NOTICE: ES: Stopping event server
2019-03-03 17:50:39.778 T:1936955856  NOTICE: stopping zeroconf publishing
2019-03-03 17:50:39.784 T:1936955856  NOTICE: CWebServer[8080]: Stopped
2019-03-03 17:50:39.948 T:1680966512  NOTICE: ES: UDP Event server stopped
2019-03-03 17:50:39.948 T:1936955856  NOTICE: stop dvd detect media
2019-03-03 17:50:40.341 T:1515676528  NOTICE: [Amazon VOD] Service: Proxy server stopped
2019-03-03 17:50:40.341 T:1515676528  NOTICE: [Amazon VOD] Service stopped
2019-03-03 17:50:40.382 T:1515676528 WARNING: CPythonInvoker(3, /storage/.kodi/addons/plugin.video.amazon-test/service.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2019-03-03 17:50:40.620 T:1936955856  NOTICE: stopped
2019-03-03 17:50:40.826 T:1936955856  NOTICE: destroy
2019-03-03 17:50:40.972 T:1936955856  NOTICE: unload skin
2019-03-03 17:50:41.088 T:1574425456  NOTICE: [Amazon VOD] Abort requested - exiting addon
2019-03-03 17:50:41.143 T:1574425456 WARNING: CPythonInvoker(5, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2019-03-03 17:50:41.166 T:1936955856  NOTICE: unload sections
2019-03-03 17:50:41.401 T:1936955856  NOTICE: application stopped...
```

**Comment by Varstahl** [comment]
Well, for starters you're either using a TLS proxy or have disabled certificate verification, which is already real bad, then while trying to manage the server's response your machine ran out of memory:

```
2019-03-03 17:47:17.957 T:1436545904 ERROR: self._SendResponse(status_code, headers, header + ''.join(new_sets) + footer, True)
2019-03-03 17:47:17.957 T:1436545904 ERROR: MemoryError
```

On top of whatever is compromising your box, either intentionally or not, it's not capable of managing some 5-15 MB data reassembling in memory. Doesn't look very good.

If it works for you, you might try to manually install VOD 0.6.8, pre-proxy server, [from here](https://github.com/Sandmann79/xbmc/tree/118e5950bb73443c3573b471afc9d572a7eb2bf9/packages/plugin.video.amazon-test), and see if it floats your boat.

**Comment by socket462** [comment]
My box is pi3 with milhouse libreelec latest nightly.
No TLS proxy for sure. and disabled certificate validation (maybe I forgot this one when tampered with options like a  monkey casually bashing them)

**Comment by Varstahl** [comment]
Yeah, but the problem still stands. The MPD you're trying to download is 32MB, by splitting and doing stuff it gets reassembled probably using around 96MB of RAM, and it explodes with an OOM error. It's not a small amount, but the RPi3+ has 1GB, we're in single digits numbers here.

Can you try to see if replacing [line 257 of proxy.py](https://github.com/Sandmann79/xbmc/blob/3a2f9df6cd8dcab6255b93bb1dc50ef23b97c54b/plugin.video.amazon-test/resources/lib/proxy.py#L257) with the following code makes it work?
```py
        new_sets = ''.join(new_sets)
        content = header + new_sets + footer
        del header
        del new_sets
        del footer
        self._SendResponse(status_code, headers, content, True)
```

**Comment by c0d3m4st4** [comment]
I use this on a RPi3B+ too and haven't experienced any issues so far.

What movie makes the addon crash so i can check if it is a common issue ? Maybe mem settings in config.txt ?

**Comment by Varstahl** [comment]
> I use this on a RPi3B+ too and haven't experienced any issues so far

Even if the addon uses 150MB in a few seconds (huge exaggeration), it's still about 15% of the total RAM available. Even considering such a high value ridiculous, it means that his RPi has an idle usage of about 900+MB of RAM, which is a tad extreme. Regardless, if the above fixes the issue, I'm not going to lose sleep over the few milliseconds lost, and I'll merge it into main.

I'm also not aware of any memory limitations imposed on addons, that might also be the case if such thing has been implemented.

> What movie makes the addon crash so i can check if it is a common issue ? Maybe mem settings in config.txt ?

Judging by the ID, it should be [this one](https://www.primevideo.com/detail/0TN3WP93H2FAWUR79B7T1OSBYV).

**Comment by socket462** [comment]
> Judging by the ID, it should be this one.

Exactly

I re-enabled certificate check and retried with the same movie. Logs are cleaner now because certificate warning went away (obviously). But the result is still the same

```
2019-03-04 21:38:58.126 T:1553785712  NOTICE: [Amazon VOD] {'path': 'root-!!-Film-!!-Film \xe2\x80\x93 Drammatico-!!-0TN3WP93H2FAWUR79B7T1OSBYV', 'mode': 'PrimeVideo_Browse'}
2019-03-04 21:38:59.253 T:1553785712  NOTICE: [Amazon VOD] postURL: http://127.0.0.1:41301/gpr/https%3A%2F%2Fatv-ps-eu.primevideo.com%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3Damzn1.dv.gti.f4aff811-0adf-82ef-b9d8-b218150d7797%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3D3cc6a1f7735a55535c8d7532ce4d9112ac559040bea5b77eea316369%26marketplaceID%3DA3K6Y4MI8GDYMT%26format%3Djson%26version%3D1%26gascEnabled%3Dtrue%26subtitleFormat%3DTTMLv2%26operatingSystemName%3DWindows%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%26supportedDRMKeyScheme%3DDUAL_KEY
2019-03-04 21:38:59.282 T:1815065456  NOTICE: [Amazon VOD] [PS] Requested POST path [u'gpr', u'https%3A%2F%2Fatv-ps-eu.primevideo.com%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3Damzn1.dv.gti.f4aff811-0adf-82ef-b9d8-b218150d7797%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3D3cc6a1f7735a55535c8d7532ce4d9112ac559040bea5b77eea316369%26marketplaceID%3DA3K6Y4MI8GDYMT%26format%3Djson%26version%3D1%26gascEnabled%3Dtrue%26subtitleFormat%3DTTMLv2%26operatingSystemName%3DWindows%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%26supportedDRMKeyScheme%3DDUAL_KEY']
2019-03-04 21:39:00.267 T:1815065456  NOTICE: [Amazon VOD] [PS] Forwarding the get request towards https://atv-ps-eu.primevideo.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.f4aff811-0adf-82ef-b9d8-b218150d7797&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=3cc6a1f7735a55535c8d7532ce4d9112ac559040bea5b77eea316369&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&subtitleFormat=TTMLv2&operatingSystemName=Windows&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives&supportedDRMKeyScheme=DUAL_KEY
2019-03-04 21:39:00.736 T:1553785712  NOTICE: [Amazon VOD] Using Host: Akamai
2019-03-04 21:39:00.738 T:1553785712  NOTICE: [Amazon VOD] checkURL: https://a46avoddashs3ww-a.akamaihd.net/d/2$3VxEjAoeWY76MWvfpm35WhuYJ4s~/ondemand/ww_dub/b449/55e4/f4d4/4efe-a383-aed16dcc7723/6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd
2019-03-04 21:39:00.908 T:1553785712   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
2019-03-04 21:39:03.669 T:1553785712  NOTICE: [Amazon VOD] http://127.0.0.1:41301/mpd/https%3A%2F%2Fa46avoddashs3ww-a.akamaihd.net%2Fd%2F2%243VxEjAoeWY76MWvfpm35WhuYJ4s%2Fondemand%2Fww_dub%2Fb449%2F55e4%2Ff4d4%2F4efe-a383-aed16dcc7723%2F6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd
2019-03-04 21:39:03.773 T:1553785712  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 999.2.3.15
2019-03-04 21:39:04.017 T:1936465936  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-!!-Film-!!-Film+%E2%80%93+Drammatico-!!-0TN3WP93H2FAWUR79B7T1OSBYV
2019-03-04 21:39:04.018 T:1482494832  NOTICE: Creating InputStream
2019-03-04 21:39:07.364 T:1468003184  NOTICE: [Amazon VOD] [PS] Requested GET path [u'mpd', u'https%3A%2F%2Fa46avoddashs3ww-a.akamaihd.net%2Fd%2F2%243VxEjAoeWY76MWvfpm35WhuYJ4s%2Fondemand%2Fww_dub%2Fb449%2F55e4%2Ff4d4%2F4efe-a383-aed16dcc7723%2F6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd']
2019-03-04 21:39:07.381 T:1468003184  NOTICE: [Amazon VOD] [PS] Forwarding the get request towards https://a46avoddashs3ww-a.akamaihd.net/d/2$3VxEjAoeWY76MWvfpm35WhuYJ4s/ondemand/ww_dub/b449/55e4/f4d4/4efe-a383-aed16dcc7723/6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd
2019-03-04 21:39:21.667 T:1468003184   ERROR: Traceback (most recent call last):
2019-03-04 21:39:21.668 T:1468003184   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2019-03-04 21:39:21.669 T:1468003184   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2019-03-04 21:39:21.669 T:1468003184   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2019-03-04 21:39:21.669 T:1468003184   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2019-03-04 21:39:21.669 T:1468003184   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2019-03-04 21:39:21.670 T:1468003184   ERROR:   File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 148, in do_GET
2019-03-04 21:39:21.672 T:1468003184   ERROR:     self._AlterMPD(unquote(path[1]), headers, data)
2019-03-04 21:39:21.672 T:1468003184   ERROR:   File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 257, in _AlterMPD
2019-03-04 21:39:21.672 T:1468003184   ERROR:     self._SendResponse(status_code, headers, header + ''.join(new_sets) + footer, True)
2019-03-04 21:39:21.672 T:1468003184   ERROR: MemoryError
2019-03-04 21:39:21.737 T:1482494832   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
2019-03-04 21:39:21.739 T:1482494832   ERROR: CCurlFile::Open failed with code 0 for http://127.0.0.1:41301/mpd/https%3A%2F%2Fa46avoddashs3ww-a.akamaihd.net%2Fd%2F2%243VxEjAoeWY76MWvfpm35WhuYJ4s%2Fondemand%2Fww_dub%2Fb449%2F55e4%2Ff4d4%2F4efe-a383-aed16dcc7723%2F6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd:
2019-03-04 21:39:21.753 T:1482494832   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://127.0.0.1:41301/mpd/https%3A%2F%2Fa46avoddashs3ww-a.akamaihd.net%2Fd%2F2%243VxEjAoeWY76MWvfpm35WhuYJ4s%2Fondemand%2Fww_dub%2Fb449%2F55e4%2Ff4d4%2F4efe-a383-aed16dcc7723%2F6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd
2019-03-04 21:39:21.764 T:1482494832   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://127.0.0.1:41301/mpd/https%3A%2F%2Fa46avoddashs3ww-a.akamaihd.net%2Fd%2F2%243VxEjAoeWY76MWvfpm35WhuYJ4s%2Fondemand%2Fww_dub%2Fb449%2F55e4%2Ff4d4%2F4efe-a383-aed16dcc7723%2F6db173f4-03cd-4d4e-acb4-e7cd03d5e628_corrected.mpd)
2019-03-04 21:39:21.772 T:1482494832   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.amazon-test/?mode=PrimeVideo_Browse&path=root-!!-Film-!!-Film+%E2%80%93+Drammatico-!!-0TN3WP93H2FAWUR79B7T1OSBYV]
2019-03-04 21:39:21.772 T:1482494832  NOTICE: CVideoPlayer::OnExit()
2019-03-04 21:39:24.089 T:1936465936  NOTICE: CVideoPlayer::CloseFile()
2019-03-04 21:39:24.090 T:1936465936  NOTICE: VideoPlayer: waiting for threads to exit
2019-03-04 21:39:24.090 T:1936465936  NOTICE: VideoPlayer: finished waiting
2019-03-04 21:39:24.102 T:1936465936 WARNING: OnMessage: Suspiciously long time to handle GUI_MSG_PLAYBACK_STARTED (20.07s)
2019-03-04 21:39:24.173 T:1553785712  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/usage/UpdateStream?asin=amzn1.dv.gti.f4aff811-0adf-82ef-b9d8-b218150d7797&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=3cc6a1f7735a55535c8d7532ce4d9112ac559040bea5b77eea316369&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&subtitleFormat=TTMLv2&event=STOP&timecode=0.0
2019-03-04 21:39:24.189 T:1553785712   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
```

>What movie makes the addon crash so i can check if it is a common issue ? Maybe mem settings in config.txt ?

@c0d3m4st4 Where is config.txt located?

I don't know if this can be relevant but I run top while watching a 720p TV show using this same plugin:

```
top - 21:55:40 up 25 min,  1 user,  load average: 1.70, 1.35, 0.97
Tasks:  98 total,   1 running,  52 sleeping,   0 stopped,   0 zombie
%Cpu(s): 33.5 us,  5.6 sy,  0.1 ni, 60.6 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem :   765820 total,   419304 free,   174540 used,   171976 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   528128 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  369 root      20   0  668808 175180  45404 S 140.4 22.9  20:02.10 kodi.bin
   84 root       1 -19       0      0      0 S   0.7  0.0   0:10.07 vchiq-slot+
  851 root      20   0    2808   1616   1404 R   0.7  0.2   0:00.11 top
    1 root      20   0   24472   5056   4152 S   0.0  0.7   0:02.01 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.01 kthreadd
    3 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 rcu_gp
    4 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 rcu_par_gp
    8 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 mm_percpu_+
    9 root      20   0       0      0      0 S   0.0  0.0   0:00.50 ksoftirqd/0
   10 root      20   0       0      0      0 I   0.0  0.0   0:00.32 rcu_sched
   11 root      20   0       0      0      0 I   0.0  0.0   0:00.00 rcu_bh
   12 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 migration/0
   13 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0
   14 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1
   15 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 migration/1
   16 root      20   0       0      0      0 S   0.0  0.0   0:00.02 ksoftirqd/1
   18 root       0 -20       0      0      0 I   0.0  0.0   0:00.14 kworker/1:+
```

@Varstahl How can I make the changes you suggest at proxy.py?

**Comment by c0d3m4st4** [comment]
@socket462 

You can set gpu_mem in /boot/config.txt Default value is 64 IIRC so if you didn't touch anything that should be fine. I use 384 for Retropie. Everything was smooth until today xD

@Varstahl However, i cannot play ANY movie today (not even the one i played fine yesterday!). TV shows seems to play fine, but most are empty and others start playing the 1st episode automatically (The Purge) ? (i think i read about this in some other issue but been busy so didn't pay attention to it). About this, also noticed in the stuff i'm following, instead of the TV show, i have the first episode listed instead of the TV show itself.

I think they keep changing stuff in their HTML, so parser is going nuts. Little to do until they are done for once.

My log, same errors as @socket462 

https://pastebin.com/qrZz96kW

**Comment by Varstahl** [comment]
The TV series bug is already fixed, you can replace the primevideo.py with the one from the master branch. If you're able to play movies with the patch I provided above, let me know and I'll introduce it.

**Comment by c0d3m4st4** [comment]
No luck.... not sure if the log is complete. Either kodi crashes and exits, or freeze.

%MEM goes from 30% to 100% quickly before crashinf/freezing. Same with %CPU as it happened to @socket462 

https://pastebin.com/SF17MVU4

**Comment by Varstahl** [comment]
I'll need to check some python internals to figure this out. Admittedly with large MPDs the memory consumption can rise, but 700MB for a 70MB MPD seems a bit too much. I'll have to look into this when I can.

**Comment by c0d3m4st4** [comment]
> 
> 
> I'll need to check some python internals to figure this out. Admittedly with large MPDs the memory consumption can rise, but 700MB for a 70MB MPD seems a bit too much. I'll have to look into this when I can.

@socket462 was using default mem settings so only taking 56 gpu_emm in his case.

I'lll try ckecking thiss too, my python is not the best, but maybe i'll learn a bit :) If only i had more time during the week... :\

**Comment by Varstahl** [comment]
Hah! So the delete actually works. It just gets timed out. I can work around that. Hopefully.

> Let's not forget this is happening to me with some movies that played fine before, so could just be something amazon changed in the MPDs?

No, I changed things so it may sadly be normal. We needed some MPD alteration to better support audio languages, and audio descriptions, things that I couldn't do without altering the MPD. So now it's a juggle between time outs (low processing speed), RAM, and full transfer over chunked. I'll need to change the data transfer to chunked to begin with, then rework part of the operation.

**Comment by Varstahl** [comment]
Replace your proxy.py with [this one](https://raw.githubusercontent.com/Sandmann79/xbmc/9230843207441d26ad857d57ce884be592fa0f07/plugin.video.amazon-test/resources/lib/proxy.py) and report back asap. I've done so many changes I don't even know if just changing proxy.py by itself would solve the issue or cause new ones. If everything fails I'll just push the update and we'll take it from there.

**Comment by c0d3m4st4** [comment]
> 
> 
> Replace your proxy.py with [this one](https://raw.githubusercontent.com/Sandmann79/xbmc/9230843207441d26ad857d57ce884be592fa0f07/plugin.video.amazon-test/resources/lib/proxy.py) and report back asap. I've done so many changes I don't even know if just changing proxy.py by itself would solve the issue or cause new ones. If everything fails I'll just push the update and we'll take it from there.

You got it!  Awesome work! 👍 

Movies with a big number of audio channels were the ones crashing before (didn't check this yesterday). World War Z has 31, takes around 2 minutes to load, but works perfectly now.  I tested as few of the ones that didn't play yesterday, and they all play now with the new proxy. Didn't appreciate longer loading times for the ones that worked before (with lower number of audio channels).

Mem usage went up to 70% max with that one but just temporarily.

TV series are fine too 👍

**Comment by Varstahl** [comment]
That's a bit of a bitch. I noticed that a movie with a 20MB MPD on my machine, depending on the server/luck, can take up to 400%, just for the initial download, and for no particular reason. You try the same URL 10 seconds later, and it's back to loading everything in 8 seconds. The MPD I was testing on, past the initial download time, added 2 seconds of loading time for 56 sets of audio tracks, which is absolutely a silly small amount. Of course with slower networks/CPUs you can feel it more, especially since past the video preloading I actually need to download *all* the audio tracks, before altering them.

It sucks that it takes so long, but it's either that or losing a bunch of audio track information and language fixes. I don't think I can ever go back.

We might be able to suppress a bunch of unneeded audio tracks though later on, so eventually we should to get back a minute and a half-ish. For today though, I'll just close this as a victory. Update coming shortly.

**Comment by c0d3m4st4** [comment]
New update. Just realized i was testing over the VPN. The extra load will probably slow down things a bit even if it is a fast one (600 symetric both sides) between my house and my parents, RPi acts as a gateway so i can remote admin their PC for fixes and stuff from any computer in my network.

Tested now directly and seems it just took 1 minute. After reading your relpy, dunno if it was just luck or just the extra load :)  No doubt processing will be slower on the RPi, but i can live with that :)

Definetly a victory! :)

Thanks! 👍
