### ISSUE TITLE
Unable to browse Tv series

### ISSUE THREAD

**Issue by Ghembs** [Sandmann79/xbmc#285]
Hi there,

I've seen similar issues but with different error logs, so perhaps this is a different problem, as per title, here's the log:

```
2019-03-17 19:10:53.161 T:1899900176   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.amazon-test/pv/browse/root/Serie+TV)
2019-03-17 19:10:53.161 T:1899900176   DEBUG:   ParentPath = [plugin://plugin.video.amazon-test/]
2019-03-17 19:10:53.162 T:1529869040   DEBUG: Thread waiting start, auto delete: false
2019-03-17 19:10:53.197 T:1774576368   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.amazon-test] took 36 ms
2019-03-17 19:10:53.197 T:1529869040   DEBUG: StartScript - calling plugin Amazon VOD('plugin://plugin.video.amazon-test/pv/browse/root/Serie+TV','1','','resume:false')
2019-03-17 19:10:53.197 T:1529869040   DEBUG: GetLanguageInvoker - Reusing LanguageInvokerThread 5 for script /home/pi/.kodi/addons/plugin.video.amazon-test/default.py
2019-03-17 19:10:53.197 T:1521476336    INFO: initializing python engine.
2019-03-17 19:10:53.197 T:1521476336   DEBUG: CPythonInvoker(5, /home/pi/.kodi/addons/plugin.video.amazon-test/default.py): start processing
2019-03-17 19:10:53.198 T:1521476336   DEBUG: CPythonInvoker(5, /home/pi/.kodi/addons/plugin.video.amazon-test/default.py): entering source directory /home/pi/.kodi/addons/plugin.video.amazon-test
2019-03-17 19:10:53.198 T:1521476336   DEBUG: CPythonInvoker(5, /home/pi/.kodi/addons/plugin.video.amazon-test/default.py): instantiating addon using automatically obtained id of "plugin.video.amazon-test" dependent on version 2.24.0 of the xbmc.python api
2019-03-17 19:10:53.199 T:1521476336   DEBUG: [Amazon VOD] Requested /pv/browse/root/Serie+TV
2019-03-17 19:10:53.262 T:1899900176   DEBUG: ------ Window Init (DialogBusy.xml) ------
2019-03-17 19:10:53.276 T:1521476336  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/storefront/tv/ref=atv_nb_sf_tv?_encoding=UTF8
2019-03-17 19:10:54.949 T:1521476336   DEBUG: [Amazon VOD] Storefront page
2019-03-17 19:11:01.942 T:1899900176   DEBUG: ------ Window Init (DialogNotification.xml) ------
2019-03-17 19:11:01.989 T:1521476336  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/storefront/ref=atv_hm_nxt_2?startIndex=14&serviceToken=eyJ0eXBlIjoidnBhZ2UiLCJuYXYiOmZhbHNlLCJzZWMiOiJjZW50ZXIiLCJwcmlkIjoiODAwMTdjNzItOTA4OS00OTJmLWFhNzgtOGM0M2M1YzhhYjNhIiwicmFuayI6Ikg0c0lBQUFBQUFBQUFCMlBTUmFFSUJCREw5UUxCaEh0SFFxRktPV0FJTmozUDBnL1dQNjhKSldpWDBxTllzUXdaTm9kOFVPL1ZQWmRYTzkrQ21oSlpmYndpSVVNRUdacHFvQjZ0RXljbHkyNFZxWXFxSDNQZ0NMNFp1QjhRL2ViQjR2eDdWc0ZiRjVKLzRaYkRLNEttbDN1eDEwd1RMMlZoMmwvN1ZaOEw3QXhrNXNlMVI1UlNHaVZxVXM1OFlJeFVXZzNDWXd4MjJPR05iVVJiTW1ROFZsMEVsTjdneE1RcHdjaWdqbFlpMHpuT2RxYmRGcUdwVVY4dmx4WmRub1ZmWC8rUjZqZGRRc0JBQUE9Iiwib2Zmc2V0IjowLCJzeXMiOlsiQ01TX1QxIl0sIm5wc2kiOjAsIm9yZXEiOiI1Q1JZWTJFWjhaSFM1RDAzODRWRTowIiwiYXBNYXgiOjE2fQ%3D%3D&pageSize=14&targetId=V1.1%3DrO0ABXNyADxjb20uYW1hem9uLmF2LnN3aWZ0c2VydmljZS5tb2RlbC5pZGVudGlmaWVyLkltbXV0YWJsZVN3aWZ0SWQWSxkI_R5k6AIABkwADGNvbGxlY3Rpb25JZHQAEkxqYXZhL2xhbmcvU3RyaW5nO0wABnBhZ2VJZHEAfgABTAARcGFnZU1lbWJlckdyb3VwSWRxAH4AAUwACHBhZ2VUeXBlcQB-AAFMAA5zd2lmdElkVmVyc2lvbnEAfgABTAAId2lkZ2V0SWRxAH4AAXhwcHQABGhvbWV0AA9zdGFuZGFyZENvbnRlbnR0AAJ0dnQABFYxLjFw&contentType=tv&contentId=home&page=2
2019-03-17 19:11:02.346 T:1521476336   DEBUG: [Amazon VOD] Storefront page
2019-03-17 19:11:02.655 T:1521476336  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/detail/0IIE9NXIF2DEKZVON3Q2KEBEAR/ref=atv_tv_hom_c_1H6noD_2_1
2019-03-17 19:11:03.642 T:1521476336   DEBUG: [Amazon VOD] Season page rev2
2019-03-17 19:11:03.675 T:1521476336   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'parent'
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 58, in EntryPoint
                                                elif 'browse' == verb: g.pv.Browse(path)
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 248, in Browse
                                                node, nodeName, ancestorNode, ancestorName = self._TraverseCatalog(path)
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 166, in _TraverseCatalog
                                                self._LazyLoad(node[nodeName], nodeName, ancestorNode, ancestorName)
                                              File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 881, in _LazyLoad
                                                o[self._videodata[refUrn]['parent']] = self._videodata[self._videodata[refUrn]['parent']]
                                            KeyError: u'parent'
                                            -->End of Python script error report<--
2019-03-17 19:11:03.675 T:1521476336   DEBUG: onExecutionDone(5, /home/pi/.kodi/addons/plugin.video.amazon-test/default.py)
2019-03-17 19:11:03.831 T:1521476336 WARNING: CPythonInvoker(5, /home/pi/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/pi/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2019-03-17 19:11:03.831 T:1521476336    INFO: Python interpreter stopped
2019-03-17 19:11:03.831 T:1521476336    INFO: Previous line repeats 1 times.
2019-03-17 19:11:03.832 T:1521476336   DEBUG: Thread LanguageInvoker 1521476336 terminating
2019-03-17 19:11:03.842 T:1529869040   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/Serie+TV
2019-03-17 19:11:03.842 T:1529869040   DEBUG: Thread waiting 1529869040 terminating
2019-03-17 19:11:03.843 T:1899900176   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2019-03-17 19:11:03.844 T:1899900176   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/Serie+TV) failed
2019-03-17 19:11:03.844 T:1899900176   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.amazon-test/)
2019-03-17 19:11:03.844 T:1899900176   DEBUG:   ParentPath = [plugin://plugin.video.amazon-test/]
2019-03-17 19:11:03.845 T:1899900176   DEBUG: Loading items: 5, directory: plugin://plugin.video.amazon-test/ sort method: 0, ascending: false
2019-03-17 19:11:03.877 T:1763164912   DEBUG: CAddonDatabase::SetLastUsed[plugin.video.amazon-test] took 33 ms
2019-03-17 19:11:03.884 T:1529869040   DEBUG: Thread BackgroundLoader start, auto delete: false
2019-03-17 19:11:03.901 T:1529869040   DEBUG: Thread BackgroundLoader 1529869040 terminating
2019-03-17 19:11:06.697 T:1899900176    INFO: CheckIdle - Closing session to http://www.msftncsi.com (easy=0x70079eb8, multi=(nil))
2019-03-17 19:11:09.056 T:1899900176   DEBUG: ------ Window Deinit (DialogNotification.xml) ------
2019-03-17 19:11:33.878 T:1763164912   DEBUG: Thread JobWorker 1763164912 terminating (autodelete)
2019-03-17 19:11:33.878 T:1544135408   DEBUG: Thread JobWorker 1544135408 terminating (autodelete)
2019-03-17 19:11:33.879 T:1754772208   DEBUG: Thread JobWorker 1754772208 terminating (autodelete)
2019-03-17 19:11:33.879 T:1774576368   DEBUG: Thread JobWorker 1774576368 terminating (autodelete)
```

If I search for individual series it will find them bun won't display episodes

**Comment by Varstahl** [comment]
Got to check that, looks weird.

**Comment by Ghembs** [comment]
If it can be of help I'm running it on a rpi3b+, new installation under RetroPie with pretty much default options.

**Comment by Varstahl** [comment]
I'm sorry for the delay dude, I'm just really, really, _really_ out of time lately, I have barely enough time to breathe. The "easy" fix would be to [delete the cache files](https://github.com/Sandmann79/xbmc/wiki/FAQ#where-are-kodis-logs--where-are-the-addons-cache-files) (both .pvcp and .pvdp). If this has happened after the update to version 0.7.0 then it's possible something went wrong/changed and the old data is not usable anymore.

Alternatively (possibly easier), from the search/catalog you can use the contextual menus on the series/season name and use the Refresh. Unless something's very wrong it should fix this way.

I just tried to search for Preacher and I'm in Italy too, so I don't see anything strange with the backend, it's just some very annoying cache corruption.

**Comment by Ghembs** [comment]
No problem: I'm making this as a gift for my girlfriend's birthday, which is on 4th of may, so I'm not under life threat for now ;)
Tried to delete cache but same problem after relaunching kodi or rebooting system, just tried to refresh after searching for a tv show: a message shows the name of the episodes (not all of them though) but none is listed in the season page

![IMG_3598](https://user-images.githubusercontent.com/20583278/54650590-8efa2080-4aaf-11e9-81db-af112a741460.JPG)
![IMG_3599](https://user-images.githubusercontent.com/20583278/54650592-93bed480-4aaf-11e9-89a8-936772ac386d.JPG)
![IMG_3600](https://user-images.githubusercontent.com/20583278/54650598-97525b80-4aaf-11e9-864b-64157edcd173.JPG)

I'm gonna try a clean install of both kodi and plugin and hope for the best...

**Comment by Varstahl** [comment]
That's very, very strange. It even says it found the episodes. I don't know, I'd need the debug logs.

**Comment by Varstahl** [comment]
Well, for one thing you're not alone. But the problem is that "everything works, but nothing does". I'd have to check the metadata, I would probably need the pvcp and pvdp from you guys zipped together and attached here. I'll take a look at them when I can.

**Comment by Ghembs** [comment]
I'm happy to report that a clean installation solved the issue, here's what I think could have caused it:
first time I tried to browse my video list first, had an error immediately on tv series folder, rebooted but error kept occurring both in my list and in general/search. This time I first loaded movies and series by accessing general folders, than I tried on my list and everything went fine.

Can't figure why deleting cache or refreshing had no effect but if I'm right about the cause the issue should be easy to reproduce/solve.

**Comment by Varstahl** [comment]
I'm baffled. If accessing the watchlist was the problem, cleaning the *.pvcp and *.pvdp would have solved the issue, 100%. I remove them all the time for tests, so that's improbable. Although, the error might be the starting cause, even though the effects are weird.

What exactly do you have on the "My Video List", as reported in PrimeVideo? If you could include both things available and out of catalog, maybe we can find some culprit.

**Comment by Ghembs** [comment]
Actually my list is pretty short, this is it:
![tvseries](https://user-images.githubusercontent.com/20583278/54868570-30be8d80-4d8e-11e9-97c4-7e3fc8797e36.PNG)

**Comment by augusto-botossi** [comment]
Sorry for stepping in this problem, but I am going through the exactly same thing. I am running raspbian stretch lite, kodi 18.1 and can't load the TV Shows, wither by the Watch List or by going straight in the TV Shows menu. Tried clean install, deleting the cache files, rebooting, resetting and so on.

I am running in portuguese but changed my profile to english to see if it will change something.

**Comment by rytecbe** [comment]
> 
> 
> Sorry for stepping in this problem, but I am going through the exactly same thing. I am running raspbian stretch lite, kodi 18.1 and can't load the TV Shows, wither by the Watch List or by going straight in the TV Shows menu. Tried clean install, deleting the cache files, rebooting, resetting and so on.
> 
> I am running in portuguese but changed my profile to english to see if it will change something.

Same issue here from Belgium.
I already have used 0.5.7 even with modified primevideo.py then deleted the cache files too but without succes so far.
Netflix and Plex are working fine.
I hope @Varstahl will have some time shortly to help us out here.
Just tell me what files you want from us to search for the failure.
I'm glad to help.

**Comment by rytecbe** [comment]
> 
> 
> I'm happy to report that a clean installation solved the issue, here's what I think could have caused it:
> first time I tried to browse my video list first, had an error immediately on tv series folder, rebooted but error kept occurring both in my list and in general/search. This time I first loaded movies and series by accessing general folders, than I tried on my list and everything went fine.
> 
> Can't figure why deleting cache or refreshing had no effect but if I'm right about the cause the issue should be easy to reproduce/solve.

What do you mean with a clean installation? Only the Amazon add-on or the complete OSMC with all add-ons and settings? And which version do you use of Amazon VOD?

BR
Ryan

**Comment by rytecbe** [comment]
After I have updated Amazon VOD to version 0.7.0 and after that rebooted the raspberry pi with Osmc and then deleted the cache files i started Amazon Video, browsed to movies and started the general folders there and I could load the movies and play them.
After that I went to TVseries, general folders and started loading. then you see some titles passing by but if you go into a serie, there saddly no seasons or episodes available, only two dotts are shown.

**Comment by augusto-botossi** [comment]
> Sorry for stepping in this problem, but I am going through the exactly same thing. I am running raspbian stretch lite, kodi 18.1 and can't load the TV Shows, wither by the Watch List or by going straight in the TV Shows menu. Tried clean install, deleting the cache files, rebooting, resetting and so on.
> 
> I am running in portuguese but changed my profile to english to see if it will change something.

I have an update: I uninstall the VOD version, changed my Prime Video default language to english, reinstall the Amazon VOD add-on and now it's working. I am only having a hard time using it because when I choose a TV Show I am not able to list episodes. When I select any TV Show it starts playing from the episode I was watching last.

**Comment by rytecbe** [comment]
> 
> 
> > Sorry for stepping in this problem, but I am going through the exactly same thing. I am running raspbian stretch lite, kodi 18.1 and can't load the TV Shows, wither by the Watch List or by going straight in the TV Shows menu. Tried clean install, deleting the cache files, rebooting, resetting and so on.
> > I am running in portuguese but changed my profile to english to see if it will change something.
> 
> I have an update: I uninstall the VOD version, changed my Prime Video default language to english, reinstall the Amazon VOD add-on and now it's working. I am only having a hard time using it because when I choose a TV Show I am not able to list episodes. When I select any TV Show it starts playing from the episode I was watching last.

Did you changed the language in your settings from the website or in the Kodi unit?

**Comment by augusto-botossi** [comment]
> > > Sorry for stepping in this problem, but I am going through the exactly same thing. I am running raspbian stretch lite, kodi 18.1 and can't load the TV Shows, wither by the Watch List or by going straight in the TV Shows menu. Tried clean install, deleting the cache files, rebooting, resetting and so on.
> > > I am running in portuguese but changed my profile to english to see if it will change something.
> > 
> > 
> > I have an update: I uninstall the VOD version, changed my Prime Video default language to english, reinstall the Amazon VOD add-on and now it's working. I am only having a hard time using it because when I choose a TV Show I am not able to list episodes. When I select any TV Show it starts playing from the episode I was watching last.
> 
> Did you changed the language in your settings from the website or in the Kodi unit?

From the website.

**Comment by rytecbe** [comment]
OK, I will give that a try tonight. Thanks for the help and in what language is your kodi system? Mine is in Dutch because if I need the subtitles it has to be in Dutch ofcourse.

**Comment by augusto-botossi** [comment]
> OK, I will give that a try tonight. Thanks for the help and in what language is your kodi system? Mine is in Dutch because if I need the subtitles it has to be in Dutch ofcourse.

I was using english, but changed to portuguese. I tested and if my Prime Video language is in english, kodi's default language can be different (at least between english and portuguese).

**Comment by rytecbe** [comment]
yesterday evening I tried this with the website language in English but I had no luck.
And I find the loading of Amazon Prime slowly compared to Netflix.
And i had no sound from Amazon movies, what could be the reason of that before I start a new topic maybe it's just something little in the config from Amazon add-on?

**Comment by rytecbe** [comment]
I must say that this afternoon I tried it again and went to the website through my laptop and then this evening I opened some TV series and now I was able to see some episodes and I could open them. So far this works but it's playing in slow motion. What can I do about that?

**Comment by augusto-botossi** [comment]
Try lowering your resolution in the Inputstream add on.

**Comment by rytecbe** [comment]
Hello, 

Yes I did and it works but lowering the resolution in the Inputstream is also then for Netflix and Plex and I would love them as 1080p

Thanks

**Comment by otrionn** [comment]
Hello all

I've the same problem, but i try all of stuff but nothing ....

I explain few day ago i install a new media center (  OS + kodi +addon)
at first all work TV shows films.... and a day ,  no serie but just ( prime original i could see old like criminal mind) 
i reboot and since nothing . 
clean install ( expect os )
clear cache
change language... nothing work 
just a little issue i try to change pv setting in account.lst ( original = true , change to false). it's work can't play any video do to regional restriction

could you help me
sorry for my english ( i'm french)

**Comment by MrPedroG** [comment]
I have just done a clean install of Kodi 18.1 x64, then installed Amazon VOD following the instructions. I am in Spain BTW.

Movies work fine, they sync completely in the menus and play perfectly via inputstream.

BUT: TV shows just sync the show name, and when you go in there, in 95% of the cases, there are no seasons or episodes. Just the 2 dots.
I see the occasional "Season X found" message on top of the screen, but it does not make any difference.

The strange thing is that inside one or two TV shows I am getting perhaps what appears to be one random season number, but when you click on it is just a random episode that starts playing. Or, in a couple of cases, right under the TV show name, instead of the seasons, perhaps one isolated episode without any season classification.

Your help is very much appreciated!
