### ISSUE TITLE
No surround since 0.6.8

### ISSUE THREAD

**Issue by v44r** [Sandmann79/xbmc#287]
I'm using the amazon vod plugin in OSMC in a Raspberry Pi 3. Until 0.6.7 movies played fine. Commit 6b99251d2a3fca8674f770a1b41b359df3819dda made DD+ tracks disappear. 

(The proxy has also introduced several other errors, such as random timeouts [ES: Client  from 127.0.0.1 timed out] which cause infinite waits, random cache corruptions that force long rebuilds and which seem to be related to the timeouts, and movies with 0 audio tracks unless "Audio descriptions" is enabled. I would stay on 0.6.7 but I always get 0 episodes for any TV series, so it's either broken surround or broken TV shows.)

**Comment by Varstahl** [comment]
Yeah, I know, update to 0.7.0-ter. All the other problems you're describing are already fixed. If you have some specific issue with 0.7.0-ter feel free to share, but in detail and with logs. Also, the surround disappearing for some areas might depend on local services, I can assure you surround works just fine. At least, if it worked with 0.6.7, it will still work for 0.7.0, unless amazon changed something in their backend, _which they did_, but since every area has its own quirks I can't preemptively know.

**Comment by v44r** [comment]
All those bugs *do* happen with 0.7.0-ter. For example, when I try to play "21" with Audio Descriptions disabled I get a timeout and 0 audio streams:

```
2019-03-18 20:55:59.575 T:1500508912  NOTICE: [Amazon VOD] postURL: http://127.0.0.1:58487/gpr/https%3A%2F%2Fatv-ps-eu.primevideo.com%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3Damzn1.dv.gti.caad9dbb-2bc0-4d1e-81c6-1ca84c672da1%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3D4ca8d922bf31b91947a5c8aa420c375d60290ad2570f748ccc435f1b%26marketplaceID%3DA3K6Y4MI8GDYMT%26format%3Djson%26version%3D1%26gascEnabled%3Dtrue%26subtitleFormat%3DTTMLv2%26operatingSystemName%3DWindows%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%26supportedDRMKeyScheme%3DDUAL_KEY
2019-03-18 20:56:01.499 T:1500508912  NOTICE: [Amazon VOD] Using Host: Cloudfront
2019-03-18 20:56:01.500 T:1500508912  NOTICE: [Amazon VOD] checkURL: https://s3-dub-2.cf.dash.row.aiv-cdn.net/dm/2$x-AKS1571t-rmMy0sReKcq2BPA8~/d642/b306/fa0c/4809-81e6-0a003f7492ad/8edadfe8-1340-4745-946e-120d0695b65d_corrected.mpd
2019-03-18 20:56:04.117 T:1500508912  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.3.15
2019-03-18 20:56:04.270 T:1916208688  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?mode=PlayVideo&name=0R5KP3DMUWJV83H2I6E76TO3OH&asin=amzn1.dv.gti.caad9dbb-2bc0-4d1e-81c6-1ca84c672da1
2019-03-18 20:56:04.272 T:1456276208  NOTICE: Creating InputStream
2019-03-18 20:56:59.912 T:1613714160  NOTICE: ES: Client  from 127.0.0.1 timed out
2019-03-18 20:57:35.154 T:1456276208   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
2019-03-18 20:57:35.154 T:1456276208 WARNING: CCurlFile::FillBuffer - Reconnect, (re)try 1
2019-03-18 20:57:50.845 T:1456276208   ERROR: CCurlFile::FillBuffer - Failed: Requested range was not delivered by the server(33)
2019-03-18 20:57:53.800 T:1456276208  NOTICE: Creating Demuxer
2019-03-18 20:57:53.801 T:1456276208  NOTICE: Opening stream: 1 source: 256
2019-03-18 20:57:54.663 T:1456276208  NOTICE: Creating video codec with codec id: 27
2019-03-18 20:57:54.680 T:1456276208  NOTICE: Creating video thread
2019-03-18 20:57:54.680 T:1483731696  NOTICE: running thread: video_thread
2019-03-18 20:57:54.681 T:1456276208  NOTICE: Opening stream: 0 source: 1024
2019-03-18 20:58:04.682 T:1801863920   ERROR: Traceback (most recent call last):
2019-03-18 20:58:04.682 T:1801863920   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2019-03-18 20:58:04.683 T:1801863920   ERROR:     self.finish_request(request, client_address)
2019-03-18 20:58:04.683 T:1801863920   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2019-03-18 20:58:04.683 T:1801863920   ERROR:     self.RequestHandlerClass(request, client_address, self)
2019-03-18 20:58:04.684 T:1801863920   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
2019-03-18 20:58:04.684 T:1801863920   ERROR:     self.finish()
2019-03-18 20:58:04.684 T:1801863920   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
2019-03-18 20:58:04.684 T:1801863920   ERROR:     self.wfile.close()
2019-03-18 20:58:04.684 T:1801863920   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2019-03-18 20:58:04.708 T:1801863920   ERROR:     self.flush()
2019-03-18 20:58:04.708 T:1801863920   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2019-03-18 20:58:04.786 T:1801863920   ERROR:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
2019-03-18 20:58:04.786 T:1801863920   ERROR: error: [Errno 32] Broken pipe
2019-03-18 20:58:05.377 T:1456276208 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
2019-03-18 20:58:05.397 T:1916208688 WARNING: OnMessage: Suspiciously long time to handle GUI_MSG_PLAYBACK_STARTED (121.11s)
2019-03-18 20:58:07.171 T:1500508912  NOTICE: [Amazon VOD] Starting Playback: 1.54100012779/7362.00048828
2019-03-18 20:58:07.173 T:1500508912  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/usage/UpdateStream?asin=amzn1.dv.gti.caad9dbb-2bc0-4d1e-81c6-1ca84c672da1&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=4ca8d922bf31b91947a5c8aa420c375d60290ad2570f748ccc435f1b&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&subtitleFormat=TTMLv2&event=START&timecode=1.54100012779
2019-03-18 20:58:16.063 T:1500508912  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/usage/UpdateStream?asin=amzn1.dv.gti.caad9dbb-2bc0-4d1e-81c6-1ca84c672da1&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=4ca8d922bf31b91947a5c8aa420c375d60290ad2570f748ccc435f1b&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&subtitleFormat=TTMLv2&event=STOP&timecode=1.54100012779
2019-03-18 20:58:18.910 T:1446519536   ERROR: Traceback (most recent call last):
2019-03-18 20:58:18.911 T:1446519536   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2019-03-18 20:58:18.911 T:1446519536   ERROR:     self.finish_request(request, client_address)
2019-03-18 20:58:18.911 T:1446519536   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2019-03-18 20:58:18.911 T:1446519536   ERROR:     self.RequestHandlerClass(request, client_address, self)
2019-03-18 20:58:18.911 T:1446519536   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
2019-03-18 20:58:18.911 T:1446519536   ERROR:     self.finish()
2019-03-18 20:58:18.911 T:1446519536   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
2019-03-18 20:58:18.911 T:1446519536   ERROR:     self.wfile.close()
2019-03-18 20:58:18.911 T:1446519536   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2019-03-18 20:58:18.911 T:1446519536   ERROR:     self.flush()
2019-03-18 20:58:18.911 T:1446519536   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2019-03-18 20:58:18.911 T:1446519536   ERROR:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
2019-03-18 20:58:18.912 T:1446519536   ERROR: error: [Errno 32] Broken pipe
```

With Audio Descriptions enabled, no problem, but I only get 18 audio streams (none DD+):

```
2019-03-18 20:47:32.801 T:1522766576  NOTICE: [Amazon VOD] postURL: http://127.0.0.1:44689/gpr/https%3A%2F%2Fatv-ps-eu.primevideo.com%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3Damzn1.dv.gti.caad9dbb-2bc0-4d1e-81c6-1ca84c672da1%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3D4ca8d922bf31b91947a5c8aa420c375d60290ad2570f748ccc435f1b%26marketplaceID%3DA3K6Y4MI8GDYMT%26format%3Djson%26version%3D1%26gascEnabled%3Dtrue%26subtitleFormat%3DTTMLv2%26operatingSystemName%3DWindows%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%26supportedDRMKeyScheme%3DDUAL_KEY
2019-03-18 20:47:35.365 T:1522766576  NOTICE: [Amazon VOD] Using Host: Cloudfront
2019-03-18 20:47:35.367 T:1522766576  NOTICE: [Amazon VOD] checkURL: https://s3-dub-2.cf.dash.row.aiv-cdn.net/dm/2$x-AKS1571t-rmMy0sReKcq2BPA8~/d642/b306/fa0c/4809-81e6-0a003f7492ad/8edadfe8-1340-4745-946e-120d0695b65d_corrected.mpd
2019-03-18 20:47:38.017 T:1522766576  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.3.15
2019-03-18 20:47:38.045 T:1915418160  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?mode=PlayVideo&name=0R5KP3DMUWJV83H2I6E76TO3OH&asin=amzn1.dv.gti.caad9dbb-2bc0-4d1e-81c6-1ca84c672da1
2019-03-18 20:47:38.047 T:1457324784  NOTICE: Creating InputStream
```

With 0.6.7, I get 27 streams (several DD+):
```
2019-03-18 20:51:27.040 T:1502311152  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.caad9dbb-2bc0-4d1e-81c6-1ca84c672da1&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=4ca8d922bf31b91947a5c8aa420c375d60290ad2570f748ccc435f1b&marketplaceID=A3K6Y4MI8GDYMT&format=json&version=1&gascEnabled=true&subtitleFormat=TTMLv2&operatingSystemName=Windows&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&videoMaterialType=Feature&desiredResources=PlaybackUrls,SubtitleUrls,ForcedNarratives&supportedDRMKeyScheme=DUAL_KEY
2019-03-18 20:51:27.955 T:1502311152  NOTICE: [Amazon VOD] Using Host: Cloudfront
2019-03-18 20:51:27.955 T:1502311152  NOTICE: [Amazon VOD] checkURL: https://s3-dub-2.cf.dash.row.aiv-cdn.net/dm/2$SewgMzndb0mU36LrMb1naJZjcjA~/d642/b306/fa0c/4809-81e6-0a003f7492ad/8edadfe8-1340-4745-946e-120d0695b65d_corrected.mpd
2019-03-18 20:51:28.706 T:1502311152  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.3.15
2019-03-18 20:51:28.839 T:1915418160  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/pv/browse/root/Pel%C3%ADculas?mode=PrimeVideo_Browse&path=root-!!-Pel%C3%ADculas-!!-Pel%C3%ADculas+de+suspense-!!-0R5KP3DMUWJV83H2I6E76TO3OH
2019-03-18 20:51:28.840 T:1385165552  NOTICE: Creating InputStream


```

**Comment by Varstahl** [comment]
55 seconds is a bit insane, although it might make some sense on a slower connection.

Sucks, but it is what it is. The timeout problem will be automatically fixed with the introduction of a new feature at a later date, nothing I can do atm.

For the time being, you can revert the proxy injection by simply reverting [line 165](https://github.com/Sandmann79/xbmc/blob/0aee79cadbcf727fbc44d5aad9e4a632d9c9515e/plugin.video.amazon-test/resources/lib/playback.py#L165) of playback.py with the following:

```
                return (urlset['url'], subUrls) if retmpd else (True, _extrFr(data))
```

Mostly everything with the exception of a few advanced language features will work correctly.

**Comment by Varstahl** [comment]
**Note to self:** we might hack language coding/parsing by (ab)using the data provided in GPR, that could avoid pre-caching, speed up video loading and avoid time outs.

**Comment by v44r** [comment]
Regarding the connection, I forgot to mention this is on symmetrical 100Mbps fiber.

Thanks for the simple proxy bypass, it works great on 0.7.0-ter. Now all the streams are there (DD+ included) and the delay when I start playing is shorter than with proxy + audio descriptions (similar to 0.6.7).

**Comment by Varstahl** [comment]
Yeah, but we kind of need the proxy to begin with, although I may have thought of a way to heavily reduce the problem. We'll see as soon as I can get to work on it :P

**Comment by Varstahl** [comment]
As of a584ccaa20925a71ee099867652281ff8b0201ec there is an option available when using InputStream that allows disabling proxy MPD alterations. Patching is no longer necessary.
