### ISSUE TITLE
Watchlist not working anymore

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#310]
I guess Amazon changed something again in the HTML, now I get an error when I try to access the watchlist:
```
09:23:30.581 T:1192  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/watchlist/
09:23:31.341 T:1192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
                                                EntryPoint()
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 58, in EntryPoint
                                                elif 'browse' == verb: g.pv.Browse(path)
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 248, in Browse
                                                node, nodeName, ancestorNode, ancestorName = self._TraverseCatalog(path)
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 166, in _TraverseCatalog
                                                self._LazyLoad(node[nodeName], nodeName, ancestorNode, ancestorName)
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 685, in _LazyLoad
                                                r'((<a href="[^"]+"[^>]*>[^<]+</a>)+)', cnt, flags=re.DOTALL).group(2)
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
```

**Comment by Varstahl** [comment]
I've noticed last night, waiting to see if it's a fluke on their servers (happened before) or if it's a real issue.

**Comment by Paco8** [comment]
I've just made the following modification which seems to work for me:

```
--- primevideo-orig.py	2019-06-10 23:36:55.602056307 +0200
+++ primevideo.py	2019-06-10 23:37:51.533353155 +0200
@@ -681,7 +681,7 @@
                         ''' New type of watchlist nobody asked for '''
                         Log('New watchlist', Log.DEBUG)
                         if ('Watchlist' == objName):
-                            entries = re.search(r'<div class="DVWebNode-watchlist-wrapper">(<div[^>]*>)<div[^>]*>.*?</div><div[^>]*><div[^>]*>'
+                            entries = re.search(r'<div\s+class="DVWebNode-watchlist-wrapper">\s*(<div[^>]*>)<div[^>]*>.*?</div><div[^>]*><div[^>]*>'
                                                 r'((<a href="[^"]+"[^>]*>[^<]+</a>)+)', cnt, flags=re.DOTALL).group(2)
                             for entry in re.findall(r'href="([^"]+)"[^>]*>(.*?)</a', entries, flags=re.DOTALL):
                                 o[Unescape(entry[1])] = {'title': Unescape(entry[1]), 'lazyLoadURL': self._g.BaseUrl + entry[0]}
```

**Comment by Varstahl** [comment]
Thanks man, I'll check it asap. I've been wrapped with my E3 coverage this year, I'm spending too many sleepless nights to code :D

**Comment by alKODIque** [comment]
Nice! I’m not the only one to experiment this issue.
Many thanks to developer!

**Comment by Paco8** [comment]
It looks like they changed the HTML again and my previous patch is not working anymore :(

**Comment by Varstahl** [comment]
Somehow you look surprised. You must be new to this :D

There's a reason why I don't rush fixes anymore…

**Comment by Paco8** [comment]
It still doesn't work for me. I guess they changed the HTML of another page. Now it doesn't work any section, not only the watchlist:

```
21:37:39.386 T:7628   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/Pel%C3%ADculas) failed
21:37:42.646 T:10836  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/watchlist/tv/ref=atv_wtlp_tv?page=1&amp;sort=DATE_ADDED_DESC
21:37:43.427 T:10836  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/detail/0M6KG10TR7AWFMI0S8XMYUZR18/ref=atv_wtlp_wtl_0
21:37:44.007 T:10836   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
                                                EntryPoint()
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 58, in EntryPoint
                                                elif 'browse' == verb: g.pv.Browse(path)
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 248, in Browse
                                                node, nodeName, ancestorNode, ancestorName = self._TraverseCatalog(path)
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 166, in _TraverseCatalog
                                                self._LazyLoad(node[nodeName], nodeName, ancestorNode, ancestorName)
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 701, in _LazyLoad
                                                gres = MultiRegexParsing(re.search(r'<section\s+[^>]*class="[ap]v-detail-section"[^>]*>\s*(.*?)\s*</section>', cnt, flags=re.DOTALL).group(1), {
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
```

**Comment by Varstahl** [comment]
Should have not pushed the update. I swear, they have a bot watching my commits. It was working this morning when I pushed it. Guess I'll wait a few more days, at least the watchlist ~is~ was working. They broke the movie listing page. Guess I'll wait a few more days.

**Comment by Paco8** [comment]
I tried to fix it myself but it seems this time they changed a lot of things, so this isn't something I can fix just by changing one line.

I noticed that the HTML pages include a lot of information in json format. Title name, release year, actors, links to other seasons... Wouldn't be easier to get the required data from it?

**Comment by Varstahl** [comment]
We already have the API endpoints to (potentially) discard the entire HTML parsing, but as soon as we fix whatever they're doing now they're going to break everything again. Last time this happened they spent 1 or 2 weeks constantly changing things, so I'm just going to wait while I'm working on something else.

**Comment by horusint** [comment]
Hi, same Issue from 1 week, Resuming Amazon VOD Addon for Kodi not working. Any news?, Thanks.

**Comment by Varstahl** [comment]
Honestly didn't touch it in the slightest, starting to work on it now, seems completely broken, no ETA.

**Comment by Varstahl** [comment]
Update's out, fixed for now.
