### ISSUE TITLE
Amazon error when adding to watchlist

### ISSUE THREAD

**Issue by dm2912** [Sandmann79/xbmc#312]
getting error on both fire tv and android tablet when trying to add film or show to watchlist.

error log:

```
NOTICE: [Amazon VOD] getURL: https://www.amazon.co.uk/gp/video/hover/B06XG9S786?format=json&refTag=dv-hover&requesterPageType=Detail
 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
            Error Type: <type 'exceptions.IndexError'>
            Error Contents: list index out of range
            Traceback (most recent call last):
              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                EntryPoint()
              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 80, in EntryPoint
                g.amz.WatchList(args.get('url', ''), int(args.get('opt', '0')))
              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/amazontld.py", line 468, in WatchList
                par = self.getParams(asin, cookie)
              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/amazontld.py", line 494, in getParams
                data = re.compile('(<form.*</form>)').findall(data)[0]
            IndexError: list index out of range
```

**Comment by Varstahl** [comment]
The dev who managed that part of the code has been missing for quite a while now, I don't think it's going to get a fix any time soon. Just out of curiosity, if you add to the watchlist from the amazon server, does it appear in the addon's watchlist?

**Comment by dm2912** [comment]
yes, anything i browse on amazon website or my fire tablet and add to my watchlist appears fine in the addon

just when browsing the tv and movie lists on the addon its not working to add to watchlist.

**Comment by Acidzero2020** [comment]
https://github.com/Sandmann79/xbmc/blob/2810456e2ce0a5b7196f0c1a3906017d4f03d6e2/plugin.video.amazon-test/resources/lib/amazontld.py#L492
 
here you got something like 

`["hover-body","\u003cdiv id=\"av-hover-body\" >\u003cdiv ....`

if you try it like this
```
        data = getURL(url, useCookie=cookie, rjson=False)
        if data:
            data = data.encode('utf-8')
            data = data.decode('unicode_escape')
            data = re.compile('(<form.*</form>)').findall(data)[0]
```

it looks like you can delete items from the watchlist, but if you try add a tv show you get "csrf_token_was_not_valid" 

I hope someone with more knowledge ca fix it.
