### ISSUE TITLE
No table check if database has been manually created (MariaDB / MySQL)

### ISSUE THREAD

**Issue by cihanoecal** [Sandmann79/xbmc#314]
**CoreElec 9.0.3 (Amlogic.arm)**
**Kodi 18.3 Git:18.3-Leia**

Hi,

I installed your addon today and it worked very well with default settings. Then I wanted to use my MariaDB server, but unfortunately i get an error. It seems, that the addon tries to lookup _tables_ which have not been created before.

I have manually created both databases _amazon_movie_ and _amazon_tv_ and granted my db user _'kodi'.%_ all permissions on both databases. The db settings for _plugin.video.amazon_ are imported 
from _advancedsettings.xml_ (which work fine for the rest of kodi). i have also manually tested a _create table_ statement on _amazon_movie.testtable_ with user _kodi_, which worked fine.

I think, these are the important lines from the log:
```
2019-07-07 12:40:05.332 T:3644584816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
        - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <class 'mysql.connector.errors.ProgrammingError'>
    Error Contents: 1146 (42S02): Table 'amazon_tv.seasons' doesn't exist
    Traceback (most recent call last):
        File "/storage/.kodi/addons/plugin.video.amazon/default.py", line 52, in <module>
        modes()
        File "/storage/.kodi/addons/plugin.video.amazon/default.py", line 49, in modes
        exec 'sitemodule.%s()' % var.args.get('sitemode')
        File "<string>", line 1, in <module>
        File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/appfeed.py", line 352, in updateAll
        tvresult = tv.addTVdb(False, cj=cj)
        File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/tv.py", line 307, in addTVdb
        cleanDB()
        File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/tv.py", line 250, in cleanDB
        seasonasins = getTVdbAsins('seasons', 2, value='asin')
        File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/tv.py", line 269, in getTVdbAsins
        for item in db.cur_exec(c, sqlstring).fetchall():
        File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/db.py", line 73, in cur_exec
        res = cur.execute(query, param)
        File "/storage/.kodi/addons/script.module.myconnpy/lib/mysql/connector/cursor.py", line 491, in execute
        self._handle_result(self._connection.cmd_query(stmt))
        File "/storage/.kodi/addons/script.module.myconnpy/lib/mysql/connector/connection.py", line 635, in cmd_query
        statement))
        File "/storage/.kodi/addons/script.module.myconnpy/lib/mysql/connector/connection.py", line 553, in _handle_result
        raise errors.get_exception(packet)
    ProgrammingError: 1146 (42S02): Table 'amazon_tv.seasons' doesn't exist
    -->End of Python script error report<--
```

[Click here ](https://pastebin.com/aBes3zRq) for a complete log file

Kind regards
Gee

**Comment by Varstahl** [comment]
I'm not the maintainer of that code so I'm not a 100% sure, however it seems like it's currently running some scraping/updating, but without the tables it crashes obviously. I'm not familiar with the addon itself, but I guess there's an easy solution.

Could you try to manually create the tables taking the definitions from [here](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon/resources/lib/db.py#L153)?

**Comment by cihanoecal** [comment]
Thank you very much! Looking at the code from your link, I got the idea, that maybe I should not have created both databases manually. And indeed that was the cause of my problem. It seems that the script only checks if the database exists and not the tables. So if the database already exists, it doesn't create tables in it.

I _dropped_ the 2 databases and after a restart of kodi both databases and their tables have been created automatically.

**Comment by Varstahl** [comment]
Makes sense, I might add a table check just for safety in the future, thanks for reporting.
