### ISSUE TITLE
Crash if I add this particular video to the watchlist

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#317]
If I add this video to the watchlist, the addon crashes when it tries to parse the html page:
https://www.primevideo.com/detail/0MRXDHQAZLMQM7TEBHD7LLEMIG/

```
22:35:09.985 T:19112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
                                                EntryPoint()
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 59, in EntryPoint
                                                elif 'refresh' == verb: g.pv.Refresh(path)
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 432, in Refresh
                                                self._LazyLoad(r[0], r[1], r[2], r[3], r[4])
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 849, in _LazyLoad
                                                ][(revision << 1) + (0 if bSingle else 1)], cnt, flags=re.DOTALL).group(1))
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
```

**Comment by Varstahl** [comment]
As soon as I can I'm gonna push the final stretch for the new release, so I don't think this will ever get fixed.
