### ISSUE TITLE
SD Streams just started to fail on Inputstream openfile

### ISSUE THREAD

**Issue by r-oldenburg** [Sandmann79/xbmc#319]
Just some hours ago watching Amazon VOD was working fine. (Raspi 2, Libreelec with Kodi) 
But now it fails with this in kodi.log:

```
2019-07-19 21:45:42.822 T:1737618288  NOTICE: [Amazon VOD] Using Host: Akamai
2019-07-19 21:45:42.826 T:1737618288  NOTICE: [Amazon VOD] checkURL: https://a134avoddashs3ww-a.akamaihd.net/d/2$3rRXLlwNEh4rTSt-VOZHa7rDwMg~/ondemand/ww_dub/3297/3497/c5b2/43f3-b23b-e5d2d32b628d/7c99f099-aee0-4d9b-a590-716d50b29ea3_corrected.mpd
2019-07-19 21:45:43.462 T:1737618288  NOTICE: [Amazon VOD] http://127.0.0.1:36815/mpd/https%3A%2F%2Fa134avoddashs3ww-a.akamaihd.net%2Fd%2F2%243rRXLlwNEh4rTSt-VOZHa7rDwMg%2Fondemand%2Fww_dub%2F3297%2F3497%2Fc5b2%2F43f3-b23b-e5d2d32b628d%2F7c99f099-aee0-4d9b-a590-716d50b29ea3_corrected.mpd
2019-07-19 21:45:43.572 T:1737618288  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 999.2.3.16
2019-07-19 21:45:43.881 T:1936463168  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B00IK97JAM&mode=PlayVideo&adult=0&name=17+-+Die+M%C3%BCllinsel&trailer=0&selbitrate=0
2019-07-19 21:45:43.883 T:1213195120  NOTICE: Creating InputStream
2019-07-19 21:45:44.017 T:1196409712  NOTICE: [Amazon VOD] [PS] Requested GET path [u'mpd', u'https%3A%2F%2Fa134avoddashs3ww-a.akamaihd.net%2Fd%2F2%243rRXLlwNEh4rTSt-VOZHa7rDwMg%2Fondemand%2Fww_dub%2F3297%2F3497%2Fc5b2%2F43f3-b23b-e5d2d32b628d%2F7c99f099-aee0-4d9b-a590-716d50b29ea3_corrected.mpd']
2019-07-19 21:45:44.050 T:1196409712  NOTICE: [Amazon VOD] [PS] Forwarding the GET request towards https://a134avoddashs3ww-a.akamaihd.net/d/2$3rRXLlwNEh4rTSt-VOZHa7rDwMg/ondemand/ww_dub/3297/3497/c5b2/43f3-b23b-e5d2d32b628d/7c99f099-aee0-4d9b-a590-716d50b29ea3_corrected.mpd
2019-07-19 21:45:46.323 T:1196409712  NOTICE: [Amazon VOD] [PS] Chunked transfer: prepping
2019-07-19 21:45:46.328 T:1213195120   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
2019-07-19 21:45:46.328 T:1213195120   ERROR: CCurlFile::Open failed with code 400 for http://127.0.0.1:36815/mpd/https%3A%2F%2Fa134avoddashs3ww-a.akamaihd.net%2Fd%2F2%243rRXLlwNEh4rTSt-VOZHa7rDwMg%2Fondemand%2Fww_dub%2F3297%2F3497%2Fc5b2%2F43f3-b23b-e5d2d32b628d%2F7c99f099-aee0-4d9b-a590-716d50b29ea3_corrected.mpd:
2019-07-19 21:45:46.329 T:1213195120   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://127.0.0.1:36815/mpd/https%3A%2F%2Fa134avoddashs3ww-a.akamaihd.net%2Fd%2F2%243rRXLlwNEh4rTSt-VOZHa7rDwMg%2Fondemand%2Fww_dub%2F3297%2F3497%2Fc5b2%2F43f3-b23b-e5d2d32b628d%2F7c99f099-aee0-4d9b-a590-716d50b29ea3_corrected.mpd
2019-07-19 21:45:46.329 T:1213195120   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://127.0.0.1:36815/mpd/https%3A%2F%2Fa134avoddashs3ww-a.akamaihd.net%2Fd%2F2%243rRXLlwNEh4rTSt-VOZHa7rDwMg%2Fondemand%2Fww_dub%2F3297%2F3497%2Fc5b2%2F43f3-b23b-e5d2d32b628d%2F7c99f099-aee0-4d9b-a590-716d50b29ea3_corrected.mpd)
2019-07-19 21:45:46.333 T:1213195120   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.amazon-test/?asin=B00IK97JAM&mode=PlayVideo&adult=0&name=17+-+Die+M%C3%BCllinsel&trailer=0&selbitrate=0]
2019-07-19 21:45:46.334 T:1213195120  NOTICE: CVideoPlayer::OnExit()
2019-07-19 21:45:46.350 T:1196409712   ERROR: Traceback (most recent call last):
2019-07-19 21:45:46.350 T:1196409712   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2019-07-19 21:45:46.351 T:1196409712   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2019-07-19 21:45:46.352 T:1196409712   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
2019-07-19 21:45:46.353 T:1196409712   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
2019-07-19 21:45:46.353 T:1196409712   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2019-07-19 21:45:46.354 T:1196409712   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2019-07-19 21:45:46.354 T:1196409712   ERROR: error: [Errno 32] Broken pipe
2019-07-19 21:45:46.603 T:1936463168  NOTICE: CVideoPlayer::CloseFile()

```

**Comment by r-oldenburg** [comment]
Btw: GREAAAT Plugin!!!!!! 
Forgot to mention. ;-)

**Comment by Paco8** [comment]
The same problem here with a nvidia shield (HD streams).

```
23:02:50.825 T:16548  NOTICE: [Amazon VOD] Using Host: Akamai
23:02:50.826 T:16548  NOTICE: [Amazon VOD] checkURL: https://a289avoddashs3ww-a.akamaihd.net/d/2$MPLvuFHe_nTC6UJGlvsREwONNtc~/ondemand/ww_dub/de51/da30/976e/484f-ac96-d9342f359ab8/7353624e-69b2-46cb-b120-dff58bf200d5_corrected.mpd
23:02:51.397 T:16548  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.3.13
23:02:51.465 T:16376  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?mode=PlayVideo&name=0JGJ8HKSVTYJBZ6FADZY99GF27&asin=amzn1.dv.gti.48b0d3d8-e9f8-472e-39ef-15121349fd3f
23:02:51.466 T:16574  NOTICE: Creating InputStream
23:02:51.503 T:16574   ERROR: AddOnLog: InputStream Adaptive: Key system request: com.widevine.alpha
23:02:53.756 T:16574   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
23:02:53.756 T:16574   ERROR: CCurlFile::Open failed with code 400 for http://127.0.0.1:40921/mpd/https%3A%2F%2Fa289avoddashs3ww-a.akamaihd.net%2Fd%2F2%24MPLvuFHe_nTC6UJGlvsREwONNtc%2Fondemand%2Fww_dub%2Fde51%2Fda30%2F976e%2F484f-ac96-d9342f359ab8%2F7353624e-69b2-46cb-b120-dff58bf200d5_corrected.mpd:
23:02:53.757 T:16574   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://127.0.0.1:40921/mpd/https%3A%2F%2Fa289avoddashs3ww-a.akamaihd.net%2Fd%2F2%24MPLvuFHe_nTC6UJGlvsREwONNtc%2Fondemand%2Fww_dub%2Fde51%2Fda30%2F976e%2F484f-ac96-d9342f359ab8%2F7353624e-69b2-46cb-b120-dff58bf200d5_corrected.mpd
23:02:53.757 T:16574   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://127.0.0.1:40921/mpd/https%3A%2F%2Fa289avoddashs3ww-a.akamaihd.net%2Fd%2F2%24MPLvuFHe_nTC6UJGlvsREwONNtc%2Fondemand%2Fww_dub%2Fde51%2Fda30%2F976e%2F484f-ac96-d9342f359ab8%2F7353624e-69b2-46cb-b120-dff58bf200d5_corrected.mpd)
23:02:53.759 T:16574   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.amazon-test/?mode=PlayVideo&name=0JGJ8HKSVTYJBZ6FADZY99GF27&asin=amzn1.dv.gti.48b0d3d8-e9f8-472e-39ef-15121349fd3f]
```

**Comment by Blackclaws** [comment]
Can confirm for host Akamai. Works fine when host is set to auto.

**Comment by Paco8** [comment]
I tried setting the host to auto but it still doesn't work for me. I tried all possible values for the host option but none of them work :(

**Comment by Blackclaws** [comment]
Does the other amazon addon work at all? HTTP 400 is Bad request... its weird that it would give that response. Try logging in and out as well, even though I would have expected a 403 Forbidden if permissions were a problem at all

**Comment by Varstahl** [comment]
I see no problem on my end, as @Blackclaws said might be a temporary outage somewhere, it happens sometimes.

**Comment by Paco8** [comment]
It doesn't work for me with any of the hosts. Maybe this is one of those changes that Amazon deploys gradually.

The videos play with the official application so this doesn't look like  an outage of the service.

**Comment by Varstahl** [comment]
Might be. Admittedly I've been using the new alpha build lately, but everything seems to be working so far. They might just be moving in to kill all outside efforts once and for all, totally possible.

**Comment by r-oldenburg** [comment]
Ok. Changing to "auto" did not help. 
BUT: I did re-login and set hosts to "cloudfront" and now it does work again.
Thanks for the pointers!

**Comment by Paco8** [comment]
Unfortunately this doesn't work for me :(

**Comment by Paco8** [comment]
I'm trying to find the problem.
It seems the mpd url contains the character ~. That character is missing in the url received by the function  _AlterMPD in proxy.py

**Comment by Varstahl** [comment]
That's normal, it's the usual way to strip the cache and get dolby surround streams and the like. You can disable it by enabling the option inside addon's Setting > Audio > Audio Descriptions.

**Comment by Paco8** [comment]
Well, it seems if the ~ is necessary otherwise the mpd url fails to load.
Enabling the audio descriptions option works as workaround and now the videos play again :)

**Comment by Varstahl** [comment]
Ok, since everyone solved their problems I'm closing this, time will tell if it was a canary deployment.

**Comment by Paco8** [comment]
It seems it was a temporary problem with the amazon servers after all. Today the urls without the "~" load again for me and the audio surround tracks are available again.
