### ISSUE TITLE
Problems with database update

### ISSUE THREAD

**Issue by Blackclaws** [Sandmann79/xbmc#320]
So I've been playing around with an Nvidia Shield I just got and on a fresh Kodi installation the database update does not seem to go through even after quite some time. This means that there are only outdated series available with the normal Amazon addon.

Is there anything obvious I'm missing for android?

I've attached some debug log:

2019-07-22 01:37:56.735 T:8269  NOTICE: ADDON: audioencoder.kodi.builtin.aac v1.0.0 installed
2019-07-22 01:37:56.735 T:8269  NOTICE: ADDON: audioencoder.kodi.builtin.wma v1.0.0 installed
2019-07-22 01:37:56.735 T:8269  NOTICE: ADDON: game.controller.default v1.0.8 installed
2019-07-22 01:37:56.735 T:8269  NOTICE: ADDON: game.controller.snes v1.0.8 installed
2019-07-22 01:37:56.735 T:8269  NOTICE: ADDON: inputstream.adaptive v2.3.22 installed
2019-07-22 01:37:56.735 T:8269  NOTICE: ADDON: kodi.binary.global.audioengine v1.0.1 installed
2019-07-22 01:37:56.735 T:8269  NOTICE: ADDON: kodi.binary.global.filesystem v1.0.2 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.global.general v1.0.3 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.global.gui v5.12.0 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.global.main v1.0.14 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.global.network v1.0.0 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.instance.audiodecoder v2.0.0 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.instance.audioencoder v2.0.0 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.instance.game v1.1.0 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.instance.imagedecoder v2.0.0 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.instance.inputstream v2.0.8 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.instance.peripheral v1.3.7 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.instance.pvr v5.10.3 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.instance.screensaver v2.0.0 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.instance.vfs v2.0.0 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.instance.videocodec v1.0.1 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.binary.instance.visualization v2.0.1 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: kodi.resource v1.0.0 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: metadata.album.universal v3.1.2 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: metadata.artists.universal v4.3.2 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: metadata.common.allmusic.com v3.2.0 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: metadata.common.fanart.tv v3.6.1 installed
2019-07-22 01:37:56.736 T:8269  NOTICE: ADDON: metadata.common.imdb.com v3.1.4 installed
2019-07-22 01:37:56.737 T:8269  NOTICE: ADDON: metadata.common.musicbrainz.org v2.2.1 installed
2019-07-22 01:37:56.737 T:8269  NOTICE: ADDON: metadata.common.theaudiodb.com v2.0.2 installed
2019-07-22 01:37:56.738 T:8269  NOTICE: ADDON: metadata.common.themoviedb.org v3.1.9 installed
2019-07-22 01:37:56.738 T:8269  NOTICE: ADDON: metadata.local v1.0.0 installed
2019-07-22 01:37:56.738 T:8269  NOTICE: ADDON: metadata.themoviedb.org v5.1.7 installed
2019-07-22 01:37:56.738 T:8269  NOTICE: ADDON: metadata.tvshows.themoviedb.org v3.1.1 installed
2019-07-22 01:37:56.738 T:8269  NOTICE: ADDON: peripheral.joystick v1.4.7 installed
2019-07-22 01:37:56.738 T:8269  NOTICE: ADDON: plugin.video.amazon v2.0.3 installed
2019-07-22 01:37:56.739 T:8269  NOTICE: ADDON: plugin.video.youtube v6.5.0 installed
2019-07-22 01:37:56.739 T:8269  NOTICE: ADDON: plugin.video.zdf_de_2016 v1.0.15 installed
2019-07-22 01:37:56.739 T:8269  NOTICE: ADDON: repository.sandmann79.plugins v1.0.2 installed
2019-07-22 01:37:56.739 T:8269  NOTICE: ADDON: repository.xbmc.org v3.1.5 installed
2019-07-22 01:37:56.739 T:8269  NOTICE: ADDON: resource.images.weathericons.default v1.1.8 installed
2019-07-22 01:37:56.739 T:8269  NOTICE: ADDON: resource.language.en_gb v2.0.1 installed
2019-07-22 01:37:56.739 T:8269  NOTICE: ADDON: resource.uisounds.kodi v1.0.0 installed
2019-07-22 01:37:56.739 T:8269  NOTICE: ADDON: screensaver.xbmc.builtin.black v1.0.32 installed
2019-07-22 01:37:56.739 T:8269  NOTICE: ADDON: screensaver.xbmc.builtin.dim v1.0.55 installed
2019-07-22 01:37:56.739 T:8269  NOTICE: ADDON: script.module.amazon.database v0.1.1 installed
2019-07-22 01:37:56.739 T:8269  NOTICE: ADDON: script.module.beautifulsoup v3.2.1 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.certifi v2019.3.9 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.chardet v3.0.4 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.future v0.16.0.4 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.idna v2.8 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.inputstreamhelper v0.3.4 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.kodi-six v0.1.0 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.libmediathek3 v1.5.0 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.libzdf v2.1.7 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.mechanize v0.2.6 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.myconnpy v1.1.7 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.pil v1.1.7 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.pycryptodome v3.4.3 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.pydes v2.0.1 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.pyxbmct v1.3.0 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.requests v2.22.0 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.six v1.11.0 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: script.module.urllib3 v1.25.3 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: service.xbmc.versioncheck v0.4.6 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: skin.estouchy v2.0.24 installed
2019-07-22 01:37:56.740 T:8269  NOTICE: ADDON: skin.estuary v2.0.23 installed
2019-07-22 01:37:56.741 T:8269  NOTICE: ADDON: webinterface.default v18.x-2.4.6 installed
2019-07-22 01:37:56.741 T:8269  NOTICE: ADDON: xbmc.addon v18.3.0 installed
2019-07-22 01:37:56.741 T:8269  NOTICE: ADDON: xbmc.core v0.1.0 installed
2019-07-22 01:37:56.741 T:8269  NOTICE: ADDON: xbmc.gui v5.14.0 installed
2019-07-22 01:37:56.741 T:8269  NOTICE: ADDON: xbmc.json v10.3.0 installed
2019-07-22 01:37:56.741 T:8269  NOTICE: ADDON: xbmc.metadata v2.1.0 installed
2019-07-22 01:37:56.742 T:8269  NOTICE: ADDON: xbmc.python v2.26.0 installed
2019-07-22 01:37:56.742 T:8269  NOTICE: ADDON: xbmc.webinterface v1.0.0 installed
2019-07-22 01:37:58.671 T:8374  NOTICE: [Amazon] Switching UserAgent
2019-07-22 01:37:58.672 T:8374  NOTICE: [Amazon] Loading list of common UserAgents
2019-07-22 01:37:58.675 T:8374  NOTICE: [Amazon] getURL: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
2019-07-22 01:37:58.930 T:8374  NOTICE: [Amazon] Error 503
2019-07-22 01:37:58.930 T:8374   ERROR: [Amazon] Error reason: 429 (HTTPError)
2019-07-22 01:38:08.931 T:8374  NOTICE: [Amazon] Attempt #2. Too many requests - Pause 10 sec
2019-07-22 01:38:08.931 T:8374  NOTICE: [Amazon] getURL: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
2019-07-22 01:38:09.166 T:8374  NOTICE: [Amazon] Error 503
2019-07-22 01:38:09.166 T:8374   ERROR: [Amazon] Error reason: 429 (HTTPError)
2019-07-22 01:38:19.166 T:8374  NOTICE: [Amazon] Attempt #3. Too many requests - Pause 10 sec
2019-07-22 01:38:19.167 T:8374  NOTICE: [Amazon] getURL: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
2019-07-22 01:38:19.425 T:8374  NOTICE: [Amazon] Error 503
2019-07-22 01:38:19.425 T:8374   ERROR: [Amazon] Error reason: 429 (HTTPError)
2019-07-22 01:38:29.426 T:8374  NOTICE: [Amazon] Attempt #4. Too many requests - Pause 10 sec
2019-07-22 01:38:29.431 T:8374  NOTICE: [Amazon] Using UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
2019-07-22 01:38:29.432 T:8374  NOTICE: [Amazon] Args: {}
2019-07-22 01:38:29.460 T:8374  NOTICE: [Amazon] AmazonDB: Service Start
2019-07-22 01:38:31.257 T:8396  NOTICE: [Amazon] Args: {}
2019-07-22 01:38:31.300 T:8396  NOTICE: [Amazon] Version: 2.0.3
2019-07-22 01:38:31.300 T:8396  NOTICE: [Amazon] Unicode filename support: False
2019-07-22 01:38:31.300 T:8374  NOTICE: [Amazon] AmazonDB: Starting DBUpdate (1970-01-01 00:00:00 / 2019-07-22 01:38:29.474104)
2019-07-22 01:38:33.091 T:8457  NOTICE: [Amazon] Args: {'sitemode': 'updateAll', 'mode': 'appfeed'}
2019-07-22 01:38:33.294 T:8457  NOTICE: [Amazon] Login
2019-07-22 01:38:39.188 T:8474  NOTICE: [Amazon] Args: {'ask': 'true', 'sitemode': 'MechanizeLogin', 'mode': 'common'}
2019-07-22 01:38:39.275 T:8474  NOTICE: [Amazon] Login
2019-07-22 01:39:31.303 T:8374  NOTICE: [Amazon] AmazonDB: Starting DBUpdate (1970-01-01 00:00:00 / 2019-07-22 01:39:31.301460)
2019-07-22 01:39:33.074 T:8491  NOTICE: [Amazon] Args: {'sitemode': 'updateAll', 'mode': 'appfeed'}
2019-07-22 01:39:33.141 T:8491  NOTICE: [Amazon] Login
2019-07-22 01:39:38.823 T:8474   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon/resources/lib/common.py:474: UserWarning: gzip transfer encoding is experimental!
                                              br.set_handle_gzip(True)
2019-07-22 01:39:38.823 T:8474  NOTICE: [Amazon] Connect to SignIn Page 5 attempts left
2019-07-22 01:39:45.991 T:8508  NOTICE: [Amazon] Args: {}
2019-07-22 01:39:46.022 T:8508  NOTICE: [Amazon] Version: 2.0.3
2019-07-22 01:39:46.022 T:8508  NOTICE: [Amazon] Unicode filename support: False
2019-07-22 01:40:31.307 T:8374  NOTICE: [Amazon] AmazonDB: Starting DBUpdate (1970-01-01 00:00:00 / 2019-07-22 01:40:31.305548)
2019-07-22 01:40:31.368 T:8508  NOTICE: [Amazon] Starting DBUpdate
2019-07-22 01:40:33.574 T:8721  NOTICE: [Amazon] Args: {}
2019-07-22 01:40:33.606 T:8721  NOTICE: [Amazon] Version: 2.0.3
2019-07-22 01:40:33.606 T:8721  NOTICE: [Amazon] Unicode filename support: False
2019-07-22 01:42:21.002 T:8508  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=51cbc747e76d4c9e25eb00ccc7620f11fe0d9762d09d8d02db48879c&format=json&StartIndex=16&NumberOfResults=1&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=MostPopular&OfferGroups=B0043YVHMY&ContractID=UX*&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
2019-07-22 01:42:22.858 T:8508  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=51cbc747e76d4c9e25eb00ccc7620f11fe0d9762d09d8d02db48879c&format=json&StartIndex=0&NumberOfResults=140&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=Title&OfferGroups=B0043YVHMY&ContractID=UX*&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
2019-07-22 01:42:23.263 T:8508  NOTICE: Previous line repeats 3 times.
2019-07-22 01:42:23.263 T:8508  NOTICE: [Amazon] Waiting 5min
2019-07-22 01:44:35.862 T:8237   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
foster:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp $ tail -f kodi.log
2019-07-22 01:40:31.307 T:8374  NOTICE: [Amazon] AmazonDB: Starting DBUpdate (1970-01-01 00:00:00 / 2019-07-22 01:40:31.305548)
2019-07-22 01:40:31.368 T:8508  NOTICE: [Amazon] Starting DBUpdate
2019-07-22 01:40:33.574 T:8721  NOTICE: [Amazon] Args: {}
2019-07-22 01:40:33.606 T:8721  NOTICE: [Amazon] Version: 2.0.3
2019-07-22 01:40:33.606 T:8721  NOTICE: [Amazon] Unicode filename support: False
2019-07-22 01:42:21.002 T:8508  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=51cbc747e76d4c9e25eb00ccc7620f11fe0d9762d09d8d02db48879c&format=json&StartIndex=16&NumberOfResults=1&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=MostPopular&OfferGroups=B0043YVHMY&ContractID=UX*&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
2019-07-22 01:42:22.858 T:8508  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=51cbc747e76d4c9e25eb00ccc7620f11fe0d9762d09d8d02db48879c&format=json&StartIndex=0&NumberOfResults=140&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=Title&OfferGroups=B0043YVHMY&ContractID=UX*&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
2019-07-22 01:42:23.263 T:8508  NOTICE: Previous line repeats 3 times.
2019-07-22 01:42:23.263 T:8508  NOTICE: [Amazon] Waiting 5min
2019-07-22 01:44:35.862 T:8237   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-07-22 01:47:23.263 T:8508  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=51cbc747e76d4c9e25eb00ccc7620f11fe0d9762d09d8d02db48879c&format=json&StartIndex=-45&NumberOfResults=2&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=MostPopular&OfferGroups=B0043YVHMY&ContractID=UX*&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
2019-07-22 01:47:24.232 T:8508  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=51cbc747e76d4c9e25eb00ccc7620f11fe0d9762d09d8d02db48879c&format=json&StartIndex=0&NumberOfResults=140&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=Title&OfferGroups=B0043YVHMY&ContractID=UX*&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
2019-07-22 01:47:24.618 T:8508  NOTICE: Previous line repeats 3 times.
2019-07-22 01:47:24.619 T:8508  NOTICE: [Amazon] Waiting 5min
2019-07-22 01:48:47.279 T:8237   ERROR: Control 55 in window 10025 has been asked to focus, but it can't

**Comment by Varstahl** [comment]
I'm not too familiar with that version, but it seems like you have some sort of connection issues. There are several URLs that need to be fetched 3-4 times, that by itself isn't normal.

**Comment by UglyBarnacle** [comment]
got the same behaviour too, database seems not to update.
neither when using mysql/mariadb/sqlite, kodi 18.2, windows10/libreelec(raspi3).
update seems to run for hours, if lucky it updates one or 2 tv series before crashing.
worked perfectly fine a while ago.

**Comment by Sandmann79** [comment]
This issue occurs on all devices. 
That's a general issue with this addon or more preciously with amazon servers. 
After fetching some titles, the server response is empty, 
although titles still need to exist. That's the reason why the addon adds this 5 minutes of wait time.
This works sometimes and sometimes not.
Recently, after a certain number of queries, an HTTP 500 error is returned. After that, the forced wait time will not help anymore.
Already tried to change the query parameters with randomised values on every request, but it doesn't help.
I have no idea what else i can do.

Without an solution for this issue, the addon is completely useless and will be dropped in the future.

**Comment by mlc42** [comment]
I´ve tried to check the getURL command in firefox

https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=8a753b09edf940f0aa8de0d08f39f4cb20b7f824cc0a1e875820aced&format=json&StartIndex=20&NumberOfResults=1&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=Title&OfferGroups=B0043YVHMY&ContractID=UX*&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2

with StartIndex 1..18 it returns titles
from 19 to 49 it returns empty titles 
from 50 to ...  it again returns titles.

doesn´t appear randomly, i could reproduce it again an again. 
 Don´t know if it is possible to jump over such entrys

**Comment by mlc42** [comment]
I´ve tested the new version. Series will be filled. I delete the db files before to see what 
will happen.  Tv.db is filled (after 2 hours > 25000 entrys, and is stilll going on). Movies.db isn´t filled. 
Many kodi.log entrys sometime http 500 

2019-10-06 14:16:28.023 T:1524425600  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=32397e00a897961c034aa486bbde5d4b503b1113640dd72aafa718d6&format=json&StartIndex=0&NumberOfResults=5&ContentType=TVEpisode&OrderBy=MostPopular&OfferGroups=B0043YVHMY&Detailed=T&SeasonASIN=B00JZOUQMO,B00JZOURY6,B00JZOUU70,B00JZOUW3M,&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
2019-10-06 14:16:28.720 T:1524425600  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=32397e00a897961c034aa486bbde5d4b503b1113640dd72aafa718d6&format=json&StartIndex=1906&NumberOfResults=100&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=Title&OfferGroups=B0043YVHMY&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
2019-10-06 14:16:29.772 T:1524425600   ERROR: [Amazon] Error reason: 500 (HTTPError)
2019-10-06 14:16:29.773 T:1524425600  NOTICE: [Amazon] HTTP Error 500

**Comment by Atomisirsi** [comment]
I get HTTP Error 410 instead. Here is an excerpt from my kodi.log:

```
2019-11-07 22:42:10.475 T:4090834960  NOTICE: -----------------------------------------------------------------------
2019-11-07 22:42:10.475 T:4090834960  NOTICE: Starting Kodi (18.2 Git:18.2-Leia). Platform: Linux ARM 32-bit
2019-11-07 22:42:10.475 T:4090834960  NOTICE: Using Release Kodi x32 build
2019-11-07 22:42:10.475 T:4090834960  NOTICE: Kodi compiled 2019-05-04 by GCC 8.2.0 for Linux ARM 32-bit version 3.14.29 (200221)
2019-11-07 22:42:10.475 T:4090834960  NOTICE: Running on LibreELEC (official): 9.0.2, kernel: Linux ARM 64-bit version 3.14.29
2019-11-07 22:42:10.476 T:4090834960  NOTICE: FFmpeg version/source: 4.0.3-Kodi
2019-11-07 22:42:10.476 T:4090834960  NOTICE: Host CPU: AArch64 Processor rev 4 (aarch64), 4 cores available
2019-11-07 22:42:10.476 T:4090834960  NOTICE: ARM Features: Neon enabled
2019-11-07 22:42:10.476 T:4090834960  NOTICE: special://xbmc/ is mapped to: /usr/share/kodi/
2019-11-07 22:42:10.476 T:4090834960  NOTICE: special://xbmcbin/ is mapped to: /usr/lib/kodi
2019-11-07 22:42:10.476 T:4090834960  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/lib/kodi/addons
2019-11-07 22:42:10.476 T:4090834960  NOTICE: special://masterprofile/ is mapped to: /storage/.kodi/userdata
2019-11-07 22:42:10.476 T:4090834960  NOTICE: special://envhome/ is mapped to: /storage
2019-11-07 22:42:10.476 T:4090834960  NOTICE: special://home/ is mapped to: /storage/.kodi
2019-11-07 22:42:10.476 T:4090834960  NOTICE: special://temp/ is mapped to: /storage/.kodi/temp
2019-11-07 22:42:10.476 T:4090834960  NOTICE: special://logpath/ is mapped to: /storage/.kodi/temp
2019-11-07 22:42:10.476 T:4090834960  NOTICE: The executable running is: /usr/lib/kodi/kodi.bin
2019-11-07 22:42:10.476 T:4090834960  NOTICE: Local hostname: Wetek
2019-11-07 22:42:10.476 T:4090834960  NOTICE: Log File is located: /storage/.kodi/temp/kodi.log
2019-11-07 22:42:10.476 T:4090834960  NOTICE: -----------------------------------------------------------------------
...
2019-11-07 22:42:10.678 T:4090834960  NOTICE: ADDON: plugin.video.amazon v2.0.3 installed
2019-11-07 22:42:10.678 T:4090834960  NOTICE: ADDON: plugin.video.amazon-test v0.6.0 installed
...
2019-11-07 22:47:50.950 T:3389584240  NOTICE: [Amazon] Starting DBUpdate
2019-11-07 22:47:50.950 T:3389584240  NOTICE: [Amazon] cleaning db
2019-11-07 22:49:32.667 T:3552969584  NOTICE: [Amazon] Args: {}
2019-11-07 22:49:32.670 T:3882378096  NOTICE: [Amazon] DB Update already running
2019-11-07 22:49:32.714 T:3552969584  NOTICE: [Amazon] Version: 2.0.3
2019-11-07 22:49:32.714 T:3552969584  NOTICE: [Amazon] Unicode filename support: False
2019-11-07 22:49:33.098 T:3552969584  NOTICE: [Amazon] DB Update already running
2019-11-07 22:49:39.711 T:3389584240  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=hidden&format=json&StartIndex=19&NumberOfResults=1&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=MostPopular&OfferGroups=B0043YVHMY&ContractID=UX*&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
2019-11-07 22:49:40.050 T:3389584240  NOTICE: [Amazon] Error 410 
2019-11-07 22:49:40.051 T:3389584240   ERROR: [Amazon] Error reason: 429 (HTTPError)
2019-11-07 22:49:50.051 T:3389584240  NOTICE: [Amazon] Attempt #2. Too many requests - Pause 10 sec 
2019-11-07 22:49:50.052 T:3389584240  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=hidden&format=json&StartIndex=19&NumberOfResults=1&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=MostPopular&OfferGroups=B0043YVHMY&ContractID=UX*&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
2019-11-07 22:49:50.124 T:3389584240  NOTICE: [Amazon] Error 410 
2019-11-07 22:49:50.124 T:3389584240   ERROR: [Amazon] Error reason: 429 (HTTPError)
2019-11-07 22:50:00.126 T:3389584240  NOTICE: [Amazon] Attempt #3. Too many requests - Pause 10 sec 
2019-11-07 22:50:00.126 T:3389584240  NOTICE: [Amazon] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=hidden&format=json&StartIndex=19&NumberOfResults=1&ContentType=TVEpisode&RollUpToSeason=T&OrderBy=MostPopular&OfferGroups=B0043YVHMY&ContractID=UX*&IncludeBlackList=T&HideNum=T&AID=1&IncludeNonWeb=T&IncludeAll=T&version=2
2019-11-07 22:50:00.205 T:3389584240  NOTICE: [Amazon] Error 410 
2019-11-07 22:50:00.206 T:3389584240   ERROR: [Amazon] Error reason: 429 (HTTPError)
2019-11-07 22:50:10.206 T:3389584240  NOTICE: [Amazon] Attempt #4. Too many requests - Pause 10 sec 
2019-11-07 22:50:10.221 T:3389584240   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: list indices must be integers, not unicode
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon/default.py", line 52, in <module>
                                                modes()
                                              File "/storage/.kodi/addons/plugin.video.amazon/default.py", line 49, in modes
                                                exec 'sitemodule.%s()' % var.args.get('sitemode')
                                              File "<string>", line 1, in <module>
                                              File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/appfeed.py", line 352, in updateAll
                                                tvresult = tv.addTVdb(False, cj=cj)
                                              File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/tv.py", line 320, in addTVdb
                                                approx = jsondata['message']['body'].get('approximateSize', 0)
                                            TypeError: list indices must be integers, not unicode
                                            -->End of Python script error report<--
2019-11-07 22:50:32.672 T:3882378096  NOTICE: [Amazon] DB Update already running
```

**Comment by Atomisirsi** [comment]
The latest commit 96fce732776608ffec0550042e3c8a244d488798 seems to fix the issues.
I was able to successfully update the local database!
