### ISSUE TITLE
Dynamic Challenge Question (DCQ) causes crash

### ISSUE THREAD

**Issue by damepatr** [Sandmann79/xbmc#325]
The Add-On kept crashing for me when it received a Dynamic Challenge Question (DCQ) from Amazon. I was able to get past the issue by answering the question on a separate computer, then using the Add-On. Here's part of the logs:
```
2019-09-08 21:13:17.843 T:1540342640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.prime_instant/default.py", line 1444, in <module>
                                                login()
                                              File "/storage/.kodi/addons/plugin.video.prime_instant/default.py", line 1092, in login
                                                elif signoutmatch[0].strip() != "null":
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2019-09-08 21:13:17.956 T:1531949936   ERROR: GetDirectory - Error getting plugin://plugin.video.prime_instant/
2019-09-08 21:13:17.958 T:1937392288   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.prime_instant/) failed
2019-09-08 21:13:23.946 T:1937392288   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-09-08 21:13:26.967 T:1589420912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.prime_instant/default.py", line 1444, in <module>
                                                login()
                                              File "/storage/.kodi/addons/plugin.video.prime_instant/default.py", line 1092, in login
                                                elif signoutmatch[0].strip() != "null":
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2019-09-08 21:13:27.091 T:1597813616   ERROR: GetDirectory - Error getting plugin://plugin.video.prime_instant/
2019-09-08 21:13:27.102 T:1937392288   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.prime_instant/) failed
```

**Comment by damepatr** [comment]
Seems like it may be related to #318. Let me know if you need more information.

**Comment by Varstahl** [comment]
Sorry to disappoint but that is not one of our addons, you're in the wrong place.
