### ISSUE TITLE
Kodi crashes after starting any video

### ISSUE THREAD

**Issue by JeansHH** [Sandmann79/xbmc#331]
**OS: Libreelec 9 (kodi 18.2)**

Hi,

since a few days/weeks amazon vod is crashing when I want to start any video. Browsing is working fine. This is the log file:

> 
                                              InsecureRequestWarning)
2019-10-03 16:08:58.601 T:1458578288  NOTICE: [Amazon VOD] Finished Fanart Update
2019-10-03 16:08:58.954 T:1483756400  NOTICE: LoadJpeg: unable to load http://www.thetvdb.com/banners/seasons/78901-13-2.jpg
2019-10-03 16:09:00.523 T:1458578288  NOTICE: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/catalog/Browse?firmware=fmw:17-app:2.0.45.1210&deviceTypeID=A2M4YX06LWP8WI&deviceID=7d17edf8d06fa97b4165e6b8133e1c467b0f5e2203ee81f946ecb223&format=json&version=2&formatVersion=3&marketplaceId=A1PA6795UKMFR9&IncludeAll=T&AID=1&version=2&SeasonASIN=B07C7H1HB3,B07C7H2CGZ,B07C7H675J,B07CGJ6W85&OfferGroups=B0043YVHMY&IncludeAll=T&AID=T&Detailed=T&tag=1&ContentType=TVEpisode&IncludeBlackList=T&NumberOfResults=40&StartIndex=0&Detailed=T&mobileClient=true
2019-10-03 16:09:00.564 T:1458578288   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
2019-10-03 16:09:04.616 T:1458578288  NOTICE: [Amazon VOD] Starting Fanart Update
2019-10-03 16:09:04.657 T:1458578288  NOTICE: [Amazon VOD] Finished Fanart Update
2019-10-03 16:18:36.252 T:1458578288  NOTICE: [Amazon VOD] postURL: http://127.0.0.1:48573/gpr/https%3A%2F%2Fatv-ps-eu.amazon.de%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3DB07C7557F4%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3D7d17edf8d06fa97b4165e6b8133e1c467b0f5e2203ee81f946ecb223%26marketplaceID%3DA1PA6795UKMFR9%26format%3Djson%26version%3D1%26gascEnabled%3Dfalse%26subtitleFormat%3DTTMLv2%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%26supportedDRMKeyScheme%3DDUAL_KEY
2019-10-03 16:18:38.776 T:1483756400   ERROR: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
2019-10-03 16:18:38.850 T:1483756400   ERROR: Traceback (most recent call last):
2019-10-03 16:18:38.850 T:1483756400   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2019-10-03 16:18:38.850 T:1483756400   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2019-10-03 16:18:38.850 T:1483756400   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2019-10-03 16:18:38.850 T:1483756400   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2019-10-03 16:18:38.850 T:1483756400   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2019-10-03 16:18:38.850 T:1483756400   ERROR:   File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 195, in do_POST
2019-10-03 16:18:38.856 T:1483756400   ERROR:     self._AlterGPR(unquote(path[1]), headers, data)
2019-10-03 16:18:38.856 T:1483756400   ERROR:   File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 227, in _AlterGPR
2019-10-03 16:18:38.856 T:1483756400   ERROR:     content = json.loads(content)
2019-10-03 16:18:38.856 T:1483756400   ERROR:   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
2019-10-03 16:18:38.857 T:1483756400   ERROR:   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
2019-10-03 16:18:38.857 T:1483756400   ERROR:   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
2019-10-03 16:18:38.857 T:1483756400   ERROR: ValueError: No JSON object could be decoded
2019-10-03 16:18:38.859 T:1458578288   ERROR: [Amazon VOD] Error reason: ('Connection aborted.', BadStatusLine("''",)) (ConnectionError)
2019-10-03 16:18:39.082 T:1936633872  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B07C7557F4&mode=PlayVideo&adult=0&name=1+-+Megan+Hunt&trailer=0&selbitrate=0
2019-10-03 16:18:39.085 T:1798280048  NOTICE: Creating InputStream
2019-10-03 16:18:39.100 T:1798280048  NOTICE: Creating Demuxer
2019-10-03 16:18:39.332 T:1936633872  NOTICE: CVideoPlayer::CloseFile()
2019-10-03 16:18:39.332 T:1936633872  NOTICE: VideoPlayer: waiting for threads to exit
2019-10-03 16:18:39.487 T:1798280048  NOTICE: Opening stream: 0 source: 256
2019-10-03 16:18:39.488 T:1798280048  NOTICE: Creating video codec with codec id: 13
2019-10-03 16:18:39.488 T:1798280048   ERROR: CMMALVideo::Open : Video codec unknown: d
2019-10-03 16:18:39.488 T:1798280048  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: raw video
2019-10-03 16:18:39.513 T:1798280048  NOTICE: Creating video thread
2019-10-03 16:18:39.514 T:1789887344  NOTICE: running thread: video_thread
2019-10-03 16:18:39.514 T:1798280048  NOTICE: CVideoPlayer::OnExit()
2019-10-03 16:18:39.514 T:1798280048  NOTICE: Closing stream player 2
2019-10-03 16:18:39.514 T:1798280048  NOTICE: waiting for video thread to exit
2019-10-03 16:18:39.514 T:1789887344   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2019-10-03 16:18:39.515 T:1789887344  NOTICE: thread end: video_thread
2019-10-03 16:18:39.515 T:1798280048  NOTICE: deleting video codec
2019-10-03 16:18:39.515 T:1936633872  NOTICE: VideoPlayer: finished waiting
2019-10-03 16:18:39.515 T:1936633872  NOTICE: CVideoPlayer::CloseFile()
2019-10-03 16:18:39.515 T:1936633872  NOTICE: VideoPlayer: waiting for threads to exit
2019-10-03 16:18:39.515 T:1936633872  NOTICE: VideoPlayer: finished waiting
2019-10-03 16:25:51.757 T:1936633872  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B07C7557F4&mode=PlayVideo&adult=0&name=1+-+Megan+Hunt&trailer=0&selbitrate=0
2019-10-03 16:25:51.760 T:1442837360  NOTICE: Creating InputStream
2019-10-03 16:25:51.764 T:1442837360  NOTICE: Creating Demuxer
2019-10-03 16:25:51.771 T:1442837360  NOTICE: Opening stream: 0 source: 256
2019-10-03 16:25:51.772 T:1442837360  NOTICE: Creating video codec with codec id: 13
2019-10-03 16:25:51.772 T:1442837360   ERROR: CMMALVideo::Open : Video codec unknown: d
2019-10-03 16:25:51.772 T:1442837360  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: raw video
2019-10-03 16:25:51.776 T:1442837360  NOTICE: Creating video thread
2019-10-03 16:25:51.776 T:1806672752  NOTICE: running thread: video_thread
2019-10-03 16:25:51.777 T:1442837360  NOTICE: CVideoPlayer::OnExit()
2019-10-03 16:25:51.777 T:1442837360  NOTICE: VideoPlayer: eof, waiting for queues to empty
2019-10-03 16:25:51.778 T:1442837360  NOTICE: Closing stream player 2
2019-10-03 16:25:51.778 T:1442837360  NOTICE: waiting for video thread to exit
2019-10-03 16:25:51.778 T:1806672752   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2019-10-03 16:25:51.778 T:1806672752  NOTICE: thread end: video_thread
2019-10-03 16:25:51.778 T:1442837360  NOTICE: deleting video codec
2019-10-03 16:25:52.299 T:1458578288  NOTICE: [Amazon VOD] postURL: http://127.0.0.1:48573/gpr/https%3A%2F%2Fatv-ps-eu.amazon.de%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3DB07CN1RZK3%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3D7d17edf8d06fa97b4165e6b8133e1c467b0f5e2203ee81f946ecb223%26marketplaceID%3DA1PA6795UKMFR9%26format%3Djson%26version%3D1%26gascEnabled%3Dfalse%26subtitleFormat%3DTTMLv2%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%26supportedDRMKeyScheme%3DDUAL_KEY

############### END LOG FILE ################

**Comment by DrSky2007** [comment]
Same problem here: Kodi 18.4 on an AMD C-50 Debian system.
