### ISSUE TITLE
Unable to load Watchlist

### ISSUE THREAD

**Issue by CGarces** [Sandmann79/xbmc#332]
I'm using Amazon test addon 0.7.4

Watchlist no longer works for me.
Log of the error
```
2019-10-12 19:55:43.591 T:3605119856  NOTICE: [Amazon VOD] Requested /pv/browse/root/Watchlist/TV+Shows
2019-10-12 19:55:43.704 T:3605119856  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/watchlist/tv/ref=atv_wtlp_tv?page=1&amp;sort=DATE_ADDED_DESC
2019-10-12 19:55:44.138 T:3605119856  NOTICE: [Amazon VOD] New watchlist
2019-10-12 19:55:44.170 T:3605119856  NOTICE: [Amazon VOD] getURL: https://www.primevideo.com/detail/0I5NVUP9P2NHV64TABMCXGC3F6/ref=atv_wl_hom_c_unkc_1_1
2019-10-12 19:55:45.015 T:3605119856  NOTICE: [Amazon VOD] Season page rev3
2019-10-12 19:55:45.081 T:3605119856  NOTICE: [Amazon VOD] postURL: https://atv-ps-eu.primevideo.com/cdp/catalog/GetPlaybackResources?asin=amzn1.dv.gti.e4b2f72f-8a6e-405e-44fe-bedba416d622&deviceTypeID=AOAGZA014O5RE&firmware=1&deviceID=6a8a03cd5a206da7d1d8ddb581d4486ff919f8e38a3fe7ad9a4252d3&marketplaceID=A2MFUE2XK8ZSSY&format=json&version=1&gascEnabled=true&resourceUsage=ImmediateConsumption&consumptionType=Streaming&deviceDrmOverride=CENC&deviceStreamingTechnologyOverride=DASH&deviceProtocolOverride=Https&deviceBitrateAdaptationsOverride=CVBR%2CCBR&audioTrackId=all&languageFeature=MLFv2&videoMaterialType=Feature&desiredResources=CatalogMetadata&titleDecorationScheme=primary-content
2019-10-12 19:55:47.734 T:3605119856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'group'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 58, in EntryPoint
                                                elif 'browse' == verb: g.pv.Browse(path)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 248, in Browse
                                                node, nodeName, ancestorNode, ancestorName = self._TraverseCatalog(path)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 166, in _TraverseCatalog
                                                self._LazyLoad(node[nodeName], nodeName, ancestorNode, ancestorName)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 850, in _LazyLoad
                                                ][(revision << 1) + (0 if bSingle else 1)], cnt, flags=re.DOTALL).group(1))
                                            AttributeError: 'NoneType' object has no attribute 'group'
                                            -->End of Python script error report<--
2019-10-12 19:55:48.024 T:3605119856 WARNING: CPythonInvoker(10, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon4xbmc7MonitorE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon7xbmcgui6DialogE
2019-10-12 19:55:48.026 T:3978478448   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/TV+Shows
2019-10-12 19:55:48.031 T:4090536736   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/TV+Shows) failed

```

Content of the URL that fails

`{"catalogMetadata":{"catalog":{"entityType":"TV Show","episodeNumber":1,"id":"amzn1.dv.gti.e4b2f72f-8a6e-405e-44fe-bedba416d622","runtimeSeconds":3321,"synopsis":"Months after the dramatic events that prompted Carrie to undergo Electroconvulsive Therapy, the former CIA case officer has found a modicum of peace in her family’s suburban embrace.","title":"The Smile","type":"EPISODE","version":"1.0"},"family":{"tvAncestors":[{"catalog":{"id":"amzn1.dv.gti.32b2ec9d-5d43-4fe0-7e4f-c4d5e9a31052","seasonNumber":2,"title":"Homeland - Season 2","type":"SEASON","version":"1.0"},"version":"1"},{"catalog":{"id":"amzn1.dv.gti.c8b2d812-7ea7-6b33-ae74-08abb760fe3c","title":"Homeland","type":"SHOW","version":"1.0"},"version":"1"}],"version":"1.0"},"images":{"imageUrls":{"episode":"https://images-eu.ssl-images-amazon.com/images/S/sgp-catalog-images/boxart_images/b71e7092-0db9-43fa-9ec6-0705c0e58e34-36d662cc-44c0-4c38-9bb3-44564688409c_RGB_SD._UY500_UX667_UY500_RI_VwyPqNRr720m803NQVlYAxZCmOKBB0Hd_TTW_.jpg","title":"https://images-eu.ssl-images-amazon.com/images/S/sgp-catalog-images/boxart_images/b71e7092-0db9-43fa-9ec6-0705c0e58e34-36d662cc-44c0-4c38-9bb3-44564688409c_RGB_SD._UY500_UX667_UY500_RI_VwyPqNRr720m803NQVlYAxZCmOKBB0Hd_TTW_.jpg"},"version":"1.0"},"playback":{"accessControls":{"pinLength":5,"restrictions":[]},"audioTracks":[{"displayName":"English","id":"en-us_dialog_0","isOriginalLanguage":false,"language":"en_US","type":"dialog"},{"displayName":"Español","id":"es-es_dialog_0","isOriginalLanguage":false,"language":"es_ES","type":"dialog"},{"displayName":"Italiano","id":"it-it_dialog_0","isOriginalLanguage":false,"language":"it_IT","type":"dialog"}],"summary":{"displayString":"Included with Prime {lineBreak}Play now","isPlayable":true},"version":"2.0"},"version":"1"},"returnedTitleRendition":{"asin":"amzn1.dv.gti.e4b2f72f-8a6e-405e-44fe-bedba416d622","audioQuality":"Stereo","audioTrackId":"all","contentId":"amzn1.dv.vcid.50606e95-747d-4d52-a27f-4143d0317088","selectedEntitlement":{"consumptionExpiration":"1571162224748","entitlementType":"PRIME_SUBSCRIPTION","grantedByCustomerId":"AU46WLJSHLHAP"},"titleId":"amzn1.dv.gti.e4b2f72f-8a6e-405e-44fe-bedba416d622","videoMaterialType":"Feature","videoQuality":"SD"}}
`

**Comment by Paco8** [comment]
Could you test if it works with this patched version of primevideo.py?

https://github.com/Paco8/xbmc/raw/Paco8-patch-1/plugin.video.amazon-test/resources/lib/primevideo.py

**Comment by Varstahl** [comment]
Don't over stress too much on this, I'm back on the case. I'll have the new, faster, API version of the addon finished by this week, even if it kills me.

**Comment by CGarces** [comment]
Thanks @Paco8, issue solved with your patch
