### ISSUE TITLE
Amazon VOD: Unexpected keyword argument 'transport_encoding'

### ISSUE THREAD

**Issue by Harshish** [Sandmann79/xbmc#337]
Hi, I just downloaded this plugin to my RPi and following is the error which I'm getting:

```
2019-10-24 13:04:16.017 T:1523561344  NOTICE: [Amazon VOD] Connect to SignIn Page 5 attempts left
2019-10-24 13:04:18.853 T:1523561344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: parse() got an unexpected keyword argument 'transport_encoding'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 89, in EntryPoint
                                                exec '%s()' % mode
                                              File "<string>", line 1, in <module>
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 453, in LogIn
                                                if 'signIn' not in [i.name for i in br.forms()]:
                                              File "/storage/.kodi/addons/script.module.mechanize/lib/mechanize/_mechanize.py", line 526, in forms
                                                return self._factory.forms()
                                              File "/storage/.kodi/addons/script.module.mechanize/lib/mechanize/_html.py", line 320, in forms
                                                self._current_forms, self._current_global_form = self._get_forms()
                                              File "/storage/.kodi/addons/script.module.mechanize/lib/mechanize/_html.py", line 335, in _get_forms
                                                if self.root is None:
                                              File "/storage/.kodi/addons/script.module.mechanize/lib/mechanize/_html.py", line 300, in root
                                                transport_encoding=transport_encoding)
                                              File "/storage/.kodi/addons/script.module.mechanize/lib/mechanize/_html.py", line 195, in content_parser
                                                return parse(data, **kw)
                                            TypeError: parse() got an unexpected keyword argument 'transport_encoding'
                                            -->End of Python script error report<--
2019-10-24 13:04:19.156 T:1523561344 WARNING: CPythonInvoker(69, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: 
```
I tried to resolve it by downgrading the html5lib, but python site-packages become read-only on SD card (there is a workaround but I don't wanna get into it). Hoping for a fix soon. Thanks

**Comment by Varstahl** [comment]
There have been updates to the mechanize package, but it mostly revolve around the update to Python 3. What you're experiencing might be due to an install of a Kodi that made the switch already, such as the nightly, a version for py3 not compatible with py2.7, or and old broken mechanize.

Long story short, there's no easy way around. There is going to be an update that gets rid of mechanize soon-ish, but then you will face the problem of a broken core Kodi python module, so you'll need to manually update the python script by hand.

**Comment by Harshish** [comment]
Alright, looks like it is easier to use an older version of Kodi then. Thanks for the prompt reply.

**Comment by Varstahl** [comment]
If you install Leia then you might want to [grab this](https://github.com/Sandmann79/xbmc/issues/322#issuecomment-533677362) instead of the official package, as the latest version is deprecated and the new build is still being finished.
