### ISSUE TITLE
AmbiguityError more than one control matching name u'email'

### ISSUE THREAD

**Issue by nubjub** [Sandmann79/xbmc#341]
After changing my amazon password I'm failing to Sign in and create a new accounts.lst file. I have the region set to USA (which is where I am) I receive the following:

2019-10-29 23:26:39.728 T:140001855820672   DEBUG: ------ Window Deinit () ------
2019-10-29 23:26:39.735 T:139999925311232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'mechanize._form_controls.AmbiguityError'>
                                            Error Contents: more than one control matching name u'email'
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/xbmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 89, in EntryPoint
                                                exec '%s()' % mode
                                              File "<string>", line 1, in <module>
                                              File "/home/xbmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 486, in LogIn
                                                br = _MFACheck(br, email, soup)
                                              File "/home/xbmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 352, in _MFACheck
                                                br['email'] = wnd.email
                                              File "/home/xbmc/.kodi/addons/script.module.mechanize/lib/mechanize/_mechanize.py", line 796, in __setitem__
                                                self.form[name] = val
                                              File "/home/xbmc/.kodi/addons/script.module.mechanize/lib/mechanize/_form_controls.py", line 1963, in __setitem__
                                                control = self.find_control(name)
                                              File "/home/xbmc/.kodi/addons/script.module.mechanize/lib/mechanize/_form_controls.py", line 2355, in find_control
                                                return self._find_control(name, type, kind, id, label, predicate, nr)
                                              File "/home/xbmc/.kodi/addons/script.module.mechanize/lib/mechanize/_form_controls.py", line 2446, in _find_control
                                                description)
                                            AmbiguityError: more than one control matching name u'email'
                                            -->End of Python script error report<--
2019-10-29 23:26:39.735 T:139999925311232   DEBUG: onExecutionDone(6, /home/xbmc/.kodi/addons/plugin.video.amazon-test/default.py)

This is a linux based install.

**Comment by nubjub** [comment]
After changing: /home/xbmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 352 from
```
br['email'] = wnd.email
```
to
```
br.find_control(name="email", nr=1).value = wnd.email
```
I was able to generate the accounts.lst. Hopefully this is helpful, seems like amazon updated the page?

**Comment by Varstahl** [comment]
Yeah, a bit, but we're also dropping mechanize, so I'll keep this open until the development branch gets merged into production.

**Comment by bb010g** [comment]
How long will it probably be until the development merge? It'd be nice to have US logins working with a hack until then if it's going to be over a week's delay.

**Comment by Varstahl** [comment]
Honestly it's probably going to take a while. There are many changes needed for the codebase due to both primevideo.com changes and Kodi Matrix support, plus a few more things that need ironing before declaring it stable. I wouldn't want to rush it, and although development lagged for a few months, we need to make things proper.

**Comment by bb010g** [comment]
Could we please get a fix backported to master, then? The plugin's unusable for new accounts until then.

**Comment by Varstahl** [comment]
Even if we did it wouldn't work because Amazon changed their backend, so that'd be pointless. Either sit tight or work a little bit and grab the addons from the `add-py3` development branch, you can find the information on other open issues, I forgot which atm.
