### ISSUE TITLE
"Cannot execute CSS selectors because the soupsieve package is not installed."

### ISSUE THREAD

**Issue by LichtiMC** [Sandmann79/xbmc#352]
**Amazon Account (select one)**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Amlogic S905W
- OS Version: CoreELEC 9.2.0
- Kodi Version 18.4
- Addon amazon-test

**Upload Logs**
```2019-11-16 00:31:37.411 T:3163603840  NOTICE: [Amazon VOD] Service: Proxy bound to 127.0.0.1:59649
2019-11-16 00:31:37.414 T:3163603840  NOTICE: [Amazon VOD] Service: Proxy server started
2019-11-16 00:31:37.415 T:3163603840  NOTICE: [Amazon VOD] Service started
2019-11-16 00:31:48.884 T:3701711744   ERROR: CCurlFile::Stat - Failed: SSL peer certificate or SSH remote key was not OK(60) for http://supremacy.org.uk/zip/plugin/script.module.pyxbmct/icon.png
2019-11-16 00:32:02.629 T:3155211136   ERROR: Previous line repeats 1 times.
2019-11-16 00:32:02.630 T:3155211136   ERROR: /storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
                                              'The soupsieve package is not installed. CSS selectors cannot be used.'
2019-11-16 00:32:03.349 T:3155211136  NOTICE: [Amazon VOD] Switching UserAgent
2019-11-16 00:32:03.351 T:3155211136  NOTICE: [Amazon VOD] Loading list of common UserAgents
2019-11-16 00:32:03.359 T:3155211136  NOTICE: [Amazon VOD] getURL: http://www.skydubh.com/pub/useragents.json
2019-11-16 00:32:03.498 T:3155211136  NOTICE: [Amazon VOD] Using UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
2019-11-16 00:32:03.643 T:3155211136  NOTICE: [Amazon VOD] Retrieve territoral config
2019-11-16 00:32:03.715 T:3155211136  NOTICE: [Amazon VOD] getURL: https://na.api.amazonvideo.com/cdp/usage/v2/GetAppStartupConfig?deviceTypeID=A28RQHJKHM2A2W&deviceID=360421879c84cd9ef433903f25dc720c77e6b5f957461de73c6f6872&firmware=1&version=1&format=json
2019-11-16 00:32:18.044 T:3155211136  NOTICE: [Amazon VOD] Connect to SignIn Page 5 attempts left
2019-11-16 00:32:22.442 T:3155211136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NotImplementedError'>
                                            Error Contents: Cannot execute CSS selectors because the soupsieve package is not installed.
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 95, in EntryPoint
                                                exec('{}()'.format(mode))
                                              File "<string>", line 1, in <module>
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 467, in LogIn
                                                form = br.select_form('form[name="signIn"]')
                                              File "/storage/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/stateful_browser.py", line 202, in select_form
                                                limit=nr + 1)
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py", line 1373, in select
                                                "Cannot execute CSS selectors because the soupsieve package is not installed."
                                            NotImplementedError: Cannot execute CSS selectors because the soupsieve package is not installed.
                                            -->End of Python script error report<--
2019-11-16 00:32:22.795 T:3155211136 WARNING: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE
```

After confirming password the above message appears in log.

**Comment by Varstahl** [comment]
Hmm, where are you getting the beautifulsoup4 module from? The one in Kodi's repository have soupsieve embedded in it, it's impossible to get this kind of errors. Can you try [downloading it from the official repos](https://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/)? Maybe you have a different version installed from another repository.

**Comment by LichtiMC** [comment]
I installed from the official repo. I even deleted the addon-folder of beautifulsoup4 via ssh and let the repository reinstall it...

**Comment by Varstahl** [comment]
I have it installed on a Leia 18.4 myself that I used while developing the python 3 support, let me know if downloading it from the repo works. If it doesn't I'll look into it, this is pretty strange.

**Comment by LichtiMC** [comment]
You were right, apparently there was some other version of beautifulsoup4 installed (even if the version nr. was the same).

Thanks for the help!

**Comment by Varstahl** [comment]
No problems, glad you got it working.

**Comment by silvatyrant** [comment]
Just to further explain the issue and resolution...

I've just experienced this issue recently on v0.9.1. It seems when BeautifulSoap (I went from 4.6.2 to 4.9.3) gets updated, for some reason the soapsieve module cannot be detected. I did the following to resolve:
1) Uninstalled BeautifulSoap by going to Add-ons >> My add-ons >> Video add-ons >> Amazon VOD >>Dependencies >> BeautifulSoap4 (check version here - if != 4.6.2, then proceed) >> Uninstall
2) SSH into Kodi and curl the correct from the [Leia repo](https://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/) - P.S. Note where you've downloaded the file to for installing via Kodi's UI.
`curl -vOL https://mirrors.kodi.tv/addons/leia/script.module.beautifulsoup4/script.module.beautifulsoup4-4.6.2.zip`
3) Go to Add-ons >> Install from zip file >> (browse to the location the module's been saved to and install)
4) $$$

I hope this is helpful to others.

**Comment by jaum20** [comment]
Thank you, @silvatyrant. Also, there is no need to uninstall beautifulsoup4, just install the older version from zip file that it will be downgraded.

**Comment by solarjoe** [comment]
I fixed this issue by just Add-ons >> My add-ons >> Video add-ons >> Amazon VOD >>Dependencies >> BeautifulSoup4 (4.6.2) >> Update >> Select 4.9.3 >> 

Now the dependencies list shows "BeautifulSoup4 (4.6.2) installed", which is incorrect now, but when I select it, the details state 4.9.3 installed.
Maybe I need to restart, but it works now.
