### ISSUE TITLE
Addon not working anymore (KeyError: u'widgets')

### ISSUE THREAD

**Issue by Paco8** [Sandmann79/xbmc#360]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.7.8~beta

**Prime Video Account (select one)**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PC
- OS Version: Windows 10
- Kodi Version 18.4

**Upload Logs**
```
2019-11-19 20:15:20.274 T:1344  NOTICE: [Amazon VOD] service.py:24 Service: Proxy bound to 127.0.0.1:54730
2019-11-19 20:15:20.359 T:1344  NOTICE: [Amazon VOD] service.py:33 Service: Proxy server started
2019-11-19 20:15:20.360 T:1344  NOTICE: [Amazon VOD] service.py:46 Service started
2019-11-19 20:15:29.347 T:6904  NOTICE: [Amazon VOD] startup.py:39 Requested {}
2019-11-19 20:15:29.910 T:6904  NOTICE: [Amazon VOD] startup.py:66 Version: 0.7.8~beta
2019-11-19 20:15:29.911 T:6904  NOTICE: [Amazon VOD] startup.py:67 Unicode filename support: True
2019-11-19 20:15:29.912 T:6904  NOTICE: [Amazon VOD] startup.py:68 Locale: es-es / Language: en
2019-11-19 20:15:29.916 T:6904  NOTICE: [Amazon VOD] network.py:143 getURL: https://www.primevideo.com
2019-11-19 20:15:32.568 T:6904   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'widgets'
                                            Traceback (most recent call last):
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
                                                EntryPoint()
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 70, in EntryPoint
                                                g.pv.BrowseRoot()
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 371, in BrowseRoot
                                                if not self.BuildRoot():
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 378, in BuildRoot
                                                home = self._GrabJSON(self._g.BaseUrl)
                                              File "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\primevideo.py", line 295, in _GrabJSON
                                                m = m['widgets']['Storefront']
                                            KeyError: u'widgets'
                                            -->End of Python script error report<--
2019-11-19 20:15:32.678 T:6904 WARNING: CPythonInvoker(3, C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py): the python script "C:\Users\Paco\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::Dialog,class XBMCAddon::xbmcaddon::Addon,class PythonBindings::XBMCAddon_xbmc_Monitor_Director
2019-11-19 20:15:32.683 T:5992   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.amazon-test/
2019-11-19 20:15:32.697 T:192   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed

```
**Describe the bug**
The addon doesn't work for me anymore, when I try to enter in the addon it shows "Amazon VOD error". Log above. I guess amazon changed something.

**Comment by Varstahl** [comment]
Yep, with the precision of a ticking bomb they broke everything, looking into it.
