### ISSUE TITLE
Exported items do not play

### ISSUE THREAD

**Issue by loggin** [Sandmann79/xbmc#380]
Exported items fail to play from library, but are fine when playing within the plugin browser

```
<addon id="plugin.video.amazon-test"
       name="Amazon VOD"
       version="0.8.1"
       provider-name="Sandmann79, Varstahl">
```

```
2019-12-14 20:41:43.442 T:596  NOTICE: [Amazon VOD] postURL: http://127.0.0.1:61936/gpr/https%3A%2F%2Fatv-ps-eu.amazon.co.uk%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3DB082LXLCPP%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3D894ebb612923729e3193202fc1584f111c67b10d67f431b094a69652%26marketplaceID%3DA1F83G8C2ARO7P%26format%3Djson%26version%3D1%26gascEnabled%3Dfalse%26subtitleFormat%3DTTMLv2%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%26supportedDRMKeyScheme%3DDUAL_KEY
2019-12-14 20:41:43.598 T:596  NOTICE: [Amazon VOD] Using Host: Cloudfront
2019-12-14 20:41:43.598 T:596  NOTICE: [Amazon VOD] checkURL: https://pop-dub-ww.cf.dash.row.aiv-cdn.net/dm/2$YZHjqZ-aGhbHA7As5L9ldFe2wCo~/8d86/f4e1/e39f/4bfc-951d-92b719825e61/eae7d85f-974e-4bbf-8262-c81ac9d95910_corrected.mpd
2019-12-14 20:41:43.785 T:596  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.4.2
2019-12-14 20:41:43.785 T:596  NOTICE: [Amazon VOD] 12524
2019-12-14 20:41:43.791 T:596   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: '\n'
                                            Traceback (most recent call last):
                                              File "C:\Users\Mark\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
                                                EntryPoint()
                                              File "C:\Users\Mark\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 80, in EntryPoint
                                                PlayVideo(args.get('name', ''), args.get('asin'), args.get('adult', '0'), int(args.get('trailer', '0')), int(args.get('selbitrate', '0')))
                                              File "C:\Users\Mark\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\playback.py", line 479, in PlayVideo
                                                playable = _IStreamPlayback(asin, name, streamtype, isAdult, extern)
                                              File "C:\Users\Mark\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\playback.py", line 446, in _IStreamPlayback
                                                player.resolve(listitem)
                                              File "C:\Users\Mark\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\playback.py", line 622, in resolve
                                                if self.extern and not self.checkResume():
                                              File "C:\Users\Mark\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\playback.py", line 648, in checkResume
                                                self.getResumePoint()
                                              File "C:\Users\Mark\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\playback.py", line 664, in getResumePoint
                                                items = pickle.load(fp)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\pickle.py", line 1384, in load
                                                return Unpickler(file).load()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\pickle.py", line 864, in load
                                                dispatch[key](self)
                                            KeyError: '\n'
                                            -->End of Python script error report<--
2019-12-14 20:41:43.854 T:596 WARNING: CPythonInvoker(76, C:\Users\Mark\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py): the python script "C:\Users\Mark\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon,class PythonBindings::XBMCAddon_xbmc_Monitor_Director,class XBMCAddon::xbmcgui::Dialog
2019-12-14 20:41:43.867 T:12892   ERROR: Playlist Player: skipping unplayable item: 0, path [C:\Users\Mark\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.amazon-test\TV\The Grand Tour\The Grand Tour - S04E01 - The Grand Tour presents… Seamen.strm]

```

this has been bugging me for a few weeks now

**Comment by Sandmann79** [comment]
You can try to delete `%appdata%\Kodi\userdata\addon_data\plugin.video.amazon-test\resume.db` Sometimes this file gets corrupted.

**Comment by ahpatel** [comment]
I can confirm I had the same error and that deleting the resume.db resolved the issue for me.
