### ISSUE TITLE
Widget error

### ISSUE THREAD

**Issue by ochriste** [Sandmann79/xbmc#383]
hello
I just tried to access Amazon VOD but I get the following error and the add-on cant display any Amazon content:

2019-12-16 18:27:49.901 T:1406137216  NOTICE: [Amazon VOD] Version: 0.7.7
2019-12-16 18:27:49.902 T:1406137216  NOTICE: [Amazon VOD] Unicode filename support: False
2019-12-16 18:27:49.904 T:1406137216  NOTICE: [Amazon VOD] Locale: en-us / Language: en
2019-12-16 18:27:51.734 T:1406137216   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'widgets'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 70, in EntryPoint
                                                g.pv.BrowseRoot()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 371, in BrowseRoot
                                                if not self.BuildRoot():
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 378, in BuildRoot
                                                home = self._GrabJSON(self._g.BaseUrl)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 295, in _GrabJSON
                                                m = m['widgets']['Storefront']
                                            KeyError: u'widgets'
                                            -->End of Python script error report<--
2019-12-16 18:27:51.896 T:1406137216 WARNING: CPythonInvoker(21, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE
2019-12-16 18:27:51.900 T:1802666880   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/
2019-12-16 18:27:51.901 T:1937433648   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed

I tested this add-on some weeks ago and I was working, 
I do not know if it is related but LibreELEC updated itself since then

thanks for any help

**Comment by Varstahl** [comment]
Yup, sounds about right. There has been another canary deployment, another known case in Italy (#381). Two things:
1. from which country are you trying to use the service?
2. could you open a browser, navigate to www.primevideo.com, save the HTML file and attach it to an answer, here?

**Comment by Varstahl** [comment]
It seems I initially misread the logs. This error doesn't make sense. Is it still not working?

**Comment by Varstahl** [comment]
Btw, you're using version 0.7.7 which is extremely outdated, that might be the reason why. The current version's 0.8.1. Update the addon and test again, report if still not working.

**Comment by ochriste** [comment]
hi
I could not update the add-on from the repository, it was telling me the add-on was up-to-date, even after updating the repository.
So I updated manually by downloading the .zip for 0.8.1, uploaded it to my raspi and installed it from the .zip, after that it is working again.

So ok for 0.8.1 with manual install, but update from repo doesnt seem to be working anymore.

**Comment by Sandmann79** [comment]
The problem must be on your end. Autoupdate works fine for me. 

![Screenshot_2020-01-06-09-47-28-934_org xbmc kodi](https://user-images.githubusercontent.com/4076968/71806769-f6e31d00-3069-11ea-9b2a-ceb41fb80f85.jpg)

**Comment by ochriste** [comment]
thats very possible, I will check the logs again and see if I see something related to updating.

**Comment by Varstahl** [comment]
Closing for inactivity.
