### ISSUE TITLE
Exception in BeautifulSoup.py ...

### ISSUE THREAD

**Issue by bimsarck** [Sandmann79/xbmc#4]
if http response code is 404.
```
15:26:11 3766.082031 T:140705935443712  NOTICE: [Amazon] Movie Update: Updating Fanart
15:27:41 3856.013916 T:140705935443712  NOTICE: [Amazon] Movie Update: Updating Fanart Finished
15:27:45 3860.463379 T:140705935443712  NOTICE: [Amazon] TV Update: Updating Fanart
15:28:02 3876.836182 T:140705935443712   ERROR: [Amazon] Error reason: HTTP Error 404: Not Found
15:28:02 3876.845703 T:140705935443712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon/default.py", line 41, in <module>
                                                modes()
                                              File "/storage/.kodi/addons/plugin.video.amazon/default.py", line 39, in modes
                                                exec 'sitemodule.%s()' % common.args.sitemode
                                              File "<string>", line 1, in <module>
                                              File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/appfeed.py", line 295, in updateAll
                                                tv.updateFanart()
                                              File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/tv.py", line 624, in updateFanart
                                                tvid, poster, fanart = appfeed.getTVDBImages(title, seasons=seasons)
                                              File "/storage/.kodi/addons/plugin.video.amazon/resources/lib/appfeed.py", line 236, in getTVDBImages
                                                soup = BeautifulSoup(result)
                                              File "/storage/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 1522, in __init__
                                                BeautifulStoneSoup.__init__(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 1147, in __init__
                                                self._feed(isHTML=isHTML)
                                              File "/storage/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 1171, in _feed
                                                smartQuotesTo=self.smartQuotesTo, isHTML=isHTML)
                                              File "/storage/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 1773, in __init__
                                                self._detectEncoding(markup, isHTML)
                                              File "/storage/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 1918, in _detectEncoding
                                                '^<\?.*encoding=[\'"](.*?)[\'"].*\?>').match(xml_data)
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--

```

.bimsarck

**Comment by Sandmann79** [comment]
Should be fixed in fd47d019fe31678a4e441f0c498f6f54aebc353d.
If not, just reopen the issue
