### ISSUE TITLE
Error during MFA parsing

### ISSUE THREAD

**Issue by Varstahl** [Sandmann79/xbmc#401]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)

Addon Version: 0.8.1

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

[Log](https://paste.kodi.tv/bedudiludu.kodi). [Forum post](https://forum.kodi.tv/showthread.php?tid=349255&pid=2917851#pid2917851).

```
 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
        - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.AttributeError'>
    Error Contents: 'NoneType' object has no attribute 'get_text'
    Traceback (most recent call last):
        File "C:\Users\bubamara\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\default.py", line 5, in <module>
        EntryPoint()
        File "C:\Users\bubamara\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\startup.py", line 97, in EntryPoint
        exec('{}()'.format(mode))
        File "<string>", line 1, in <module>
        File "C:\Users\bubamara\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\network.py", line 497, in LogIn
        br = _MFACheck(br, email, soup)
        File "C:\Users\bubamara\AppData\Roaming\Kodi\addons\plugin.video.amazon-test\resources\lib\network.py", line 371, in _MFACheck
        msg = soup.find('div', attrs={'class': 'a-row a-spacing-micro cvf-widget-input-code-label'}).get_text(strip=True)
    AttributeError: 'NoneType' object has no attribute 'get_text'
    -->End of Python script error report<--
```

Additionally, user reports:
>> **Überprüfung erforderlich**
>> Wir senden Ihnen per E-Mail einen Code zur Überprüfung Ihrer Identität …

> But there is never an Email with the code nor any place where I could enter such code.

**Comment by Varstahl** [comment]
It's in the `fwcim-form` section. I know nothing about these validation methods used by TLDs, so I'll leave this up to you, @Sandmann79.

Also, the user has been messing with banned addons so we can't provide support either.

**Comment by Sandmann79** [comment]
This identity check should be achieved by the addon. Maybe Amazon changed something..
But without further logs (login/login-mfa) it's not possible for me to investigate on this.

**Comment by Varstahl** [comment]
Fair enough, forgot to ask the dude.

**Comment by Varstahl** [comment]
* [kodi.log](https://pastebin.com/rtGX8McL)
* [avod-login.log](https://pastebin.com/nSRH00Kq)
* [avod-login-mfa.log](https://pastebin.com/zeBAcdUN)

Another user popped up with the same error on RPi, quote:

> I get the Captcha, I supply my password and the captcha fine. The problems happens after I choose the method I want to receive the verification. It pops the error a second or two after I choose the method. I've tried all methods with the same result.

@Sandmann79 can you take a look at the login logs when you have a moment?
