### ISSUE TITLE
Unable to play video

### ISSUE THREAD

**Issue by damgot** [Sandmann79/xbmc#402]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Amazon (plugin.video.amazon)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [0.8.1]

**Prime Video Account (select one)**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [RPi 3+]
- OS Version: [LibreElec 9.2.0]
- Kodi Version [18.5]

**Upload Logs**
```
2020-01-20 20:20:00.566 T:1435497344  NOTICE: [Amazon VOD] Using Host: Cloudfront
2020-01-20 20:20:00.568 T:1435497344  NOTICE: [Amazon VOD] checkURL: xxx
2020-01-20 20:20:02.052 T:1435497344  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.4.2.1
2020-01-20 20:20:02.953 T:1937413168  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?mode=PlayVideo&name=xxxx
2020-01-20 20:20:02.958 T:1362465664  NOTICE: Creating InputStream
2020-01-20 20:20:03.073 T:1362465664   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2020-01-20 20:20:31.337 T:1362465664   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
2020-01-20 20:20:31.337 T:1362465664 WARNING: CCurlFile::FillBuffer - Reconnect, (re)try 1
2020-01-20 20:20:36.920 T:1362465664   ERROR: CCurlFile::FillBuffer - Failed: Requested range was not delivered by the server(33)
2020-01-20 20:20:39.567 T:1362465664  NOTICE: Creating Demuxer
2020-01-20 20:20:39.568 T:1362465664  NOTICE: Opening stream: 1 source: 256
2020-01-20 20:20:39.881 T:1362465664  NOTICE: Creating video codec with codec id: 27
2020-01-20 20:20:39.893 T:1362465664  NOTICE: Creating video thread
2020-01-20 20:20:39.893 T:1445983104  NOTICE: running thread: video_thread
2020-01-20 20:20:39.896 T:1362465664  NOTICE: Opening stream: 0 source: 1024
2020-01-20 20:20:40.176 T:1379251072   ERROR: Traceback (most recent call last):
2020-01-20 20:20:40.177 T:1379251072   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
2020-01-20 20:20:40.177 T:1379251072   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2020-01-20 20:20:40.178 T:1379251072   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
2020-01-20 20:20:40.179 T:1379251072   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
2020-01-20 20:20:40.180 T:1379251072   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2020-01-20 20:20:40.180 T:1379251072   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2020-01-20 20:20:40.180 T:1379251072   ERROR: error: [Errno 32] Broken pipe
2020-01-20 20:20:45.378 T:1362465664 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
2020-01-20 20:20:45.894 T:1435497344  NOTICE: [Amazon VOD] Starting Playback: xxxx
2020-01-20 20:20:45.897 T:1435497344  NOTICE: [Amazon VOD] postURL: xxx
2020-01-20 20:21:13.444 T:1937413168  NOTICE: CVideoPlayer::CloseFile()
2020-01-20 20:21:13.450 T:1362465664  NOTICE: CVideoPlayer::OnExit()
2020-01-20 20:21:13.450 T:1362465664  NOTICE: Closing stream player 2
2020-01-20 20:21:13.452 T:1362465664  NOTICE: waiting for video thread to exit
2020-01-20 20:21:13.495 T:1445983104  NOTICE: thread end: video_thread
2020-01-20 20:21:13.496 T:1362465664  NOTICE: deleting video codec
2020-01-20 20:21:13.497 T:1937413168  NOTICE: VideoPlayer: waiting for threads to exit
2020-01-20 20:21:14.175 T:1362465664  NOTICE: Closing stream player 3
2020-01-20 20:21:14.230 T:1937413168  NOTICE: VideoPlayer: finished waiting
2020-01-20 20:21:14.230 T:1937413168  NOTICE: CVideoPlayer::CloseFile()
2020-01-20 20:21:14.230 T:1937413168  NOTICE: VideoPlayer: waiting for threads to exit
2020-01-20 20:21:14.230 T:1937413168  NOTICE: VideoPlayer: finished waiting
2020-01-20 20:21:14.268 T:1937413168   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2020-01-20 20:21:14.738 T:1435497344  NOTICE: [Amazon VOD] postURL: xxx
2020-01-20 20:21:28.581 T:1354072960  NOTICE: Previous line repeats 1 times.
2020-01-20 20:21:28.582 T:1354072960   ERROR: Traceback (most recent call last):
2020-01-20 20:21:28.582 T:1354072960   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
2020-01-20 20:21:28.583 T:1354072960   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2020-01-20 20:21:28.583 T:1354072960   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
2020-01-20 20:21:28.584 T:1354072960   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
2020-01-20 20:21:28.584 T:1354072960   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2020-01-20 20:21:28.584 T:1354072960   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2020-01-20 20:21:28.584 T:1354072960   ERROR: error: [Errno 32] Broken pipe
2020-01-20 20:21:28.904 T:1435497344 WARNING: CPythonInvoker(15, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: xxx
```

**Describe the bug**
When I try to start a video, the wheel start turning infinitely but the video never start. See log above.

Thanks

**Comment by damgot** [comment]
The directory /usr/lib/kodi/addons/inputstream.adaptive/ doesn't exist.

Inputstream.adaptive was installed in ~/.kodi/addons/inputstream.adaptive

**Comment by Varstahl** [comment]
There are a lot of information missing, including but not limited to the installed addons list and the URL endpoints. In any case this looks like an incorrectly configured Kodi. Uninstall and reinstall IS.A and check if it fixes things. Also, IS.A is outdated, so pretty much everything here is out of place.

**Comment by damgot** [comment]
Hello, thanks for your answer.

I've installed nothing else than Amazon VOD (and all its depedencies).
The list is :
- AAC encoder
- Amazon Vod
- Black
- Default Controller
- Dim
- English
- Estuary
- French
- InputStream Adaptive
- InputStream Helper
- Joystick Support
- Kodi Add-on Repository
- Kodi Game add-on Repository
- Kodi UI Sounds
- Kodi Web interface- chorus2
- LibreElec add-ons
- LibreElec Configuration
- LibreElec Module Drivers
- Local information onlu
- Sandmann79s Repository
- SNES Controller
- The Movie Database
- The TVDB
- Universal Album Scraper
- Universal Artist Scraper
- Weather Icons - Default
- WMA encoder
- Yahoo! Weather

ISA was installed by Amazon VOD... If it's not the good version, I guess the problem come from Amazon VOD...

So Close directly the issue without trying understand anything is a little bit rushed...

**Comment by Varstahl** [comment]
The addon doesn't manage the installation of addons, just emulates user interaction, if you will. In any case, as I said, it's a configuration/networking problem not directly caused by the addon, so whatever solution you might need won't come from an addon fix. If the problem is IS.A, then there's a problem with Kodi installation.

Most likely though, it seems to be some sort of networking/connection/VPN issue, which I can't help you address.

Additionally, the log is missing key parts that we need to be able to help you, so without full log and a problem relative to the addon this issue is invalid.
