### ISSUE TITLE
Updates to stable?

### ISSUE THREAD

**Issue by yknivag** [Sandmann79/xbmc#408]
Firstly, thank you for the work you do with this add on.

I wonder if there has been any progress on bringing the latest updates into the stable version?

Or will [this](https://github.com/Sandmann79/xbmc/issues/343#issuecomment-549246720) always be the installation process going forward?

**Comment by Varstahl** [comment]
The new branch has been already merged and released, it works on both Kodi 18 and Kodi 19, and is python 3 ready. The addons are not yet on the official repository as I wanted to road test them a bit longer and then got side tracked, but other then the classic repo installation there's no manual work to do. Just follow [these instructions](https://github.com/Sandmann79/xbmc) to install the repo, install Amazon VOD, and you're good to go.

**Comment by yknivag** [comment]
Hi, thanks for getting back.  I was having problems still after upgrading in Kodi, but having read this and now having deleted credentials and cookie and logged back in all is working well on v.0.8.1 directly from the repo.

Incidentally I tried the latest v.0.8.2-beta (via the instructions in Issue#343) and that didn't work for me.  Log below if it is useful.

`2020-02-03 17:42:39.286 T:1763701472  NOTICE: [Amazon VOD] postURL: http://127.0.0.1:41263/gpr/https%3A%2F%2Fatv-ps-eu.amazon.co.uk%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3DB07Q8VMHYJ%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3D4b5d1b5580f9bbc04172ce1d2c730dc154e745802eced0ffce089d9f%26marketplaceID%3DA1F83G8C2ARO7P%26format%3Djson%26version%3D1%26gascEnabled%3Dfalse%26subtitleFormat%3DTTMLv2%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%26supportedDRMKeyScheme%3DDUAL_KEY
2020-02-03 17:42:41.143 T:1576006368   ERROR: Traceback (most recent call last):
2020-02-03 17:42:41.144 T:1576006368   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2020-02-03 17:42:41.148 T:1576006368   ERROR:     self.finish_request(request, client_address)
2020-02-03 17:42:41.148 T:1576006368   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2020-02-03 17:42:41.149 T:1576006368   ERROR:     self.RequestHandlerClass(request, client_address, self)
2020-02-03 17:42:41.149 T:1576006368   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2020-02-03 17:42:41.149 T:1576006368   ERROR:     self.handle()
2020-02-03 17:42:41.150 T:1576006368   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2020-02-03 17:42:41.154 T:1576006368   ERROR:     self.handle_one_request()
2020-02-03 17:42:41.154 T:1576006368   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2020-02-03 17:42:41.154 T:1576006368   ERROR:     method()
2020-02-03 17:42:41.155 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 205, in do_POST
2020-02-03 17:42:41.155 T:1576006368   ERROR:     self._AlterGPR(unquote(path[1]), headers, data)
2020-02-03 17:42:41.155 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 239, in _AlterGPR
2020-02-03 17:42:41.155 T:1576006368   ERROR:     status_code, headers, content = self._ForwardRequest('get', endpoint, headers, data)
2020-02-03 17:42:41.155 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 85, in _ForwardRequest
2020-02-03 17:42:41.156 T:1576006368   ERROR:     from resources.lib.network import MechanizeLogin
2020-02-03 17:42:41.156 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 9, in <module>
2020-02-03 17:42:41.160 T:1576006368   ERROR:     import mechanicalsoup
2020-02-03 17:42:41.161 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/__init__.py", line 2, in <module>
2020-02-03 17:42:41.162 T:1576006368   ERROR:     from .browser import Browser
2020-02-03 17:42:41.162 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/browser.py", line 2, in <module>
2020-02-03 17:42:41.165 T:1576006368   ERROR:     import bs4
2020-02-03 17:42:41.165 T:1576006368   ERROR: ValueError: bad marshal data (unknown type code)
2020-02-03 17:42:41.170 T:1763701472   ERROR: [Amazon VOD] Error reason: ('Connection aborted.', BadStatusLine("''",)) (ConnectionError)
2020-02-03 17:42:42.155 T:1915545136  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B07Q8VMHYJ&mode=PlayVideo&adult=0&name=1+-+Beginnings&trailer=0&selbitrate=0
2020-02-03 17:42:42.159 T:1755308768  NOTICE: Creating InputStream
2020-02-03 17:42:42.215 T:1755308768  NOTICE: Creating Demuxer
2020-02-03 17:42:42.380 T:1915545136  NOTICE: CVideoPlayer::CloseFile()
2020-02-03 17:42:42.381 T:1915545136  NOTICE: VideoPlayer: waiting for threads to exit
2020-02-03 17:42:42.557 T:1755308768  NOTICE: Opening stream: 0 source: 256
2020-02-03 17:42:42.557 T:1755308768  NOTICE: Creating video codec with codec id: 13
2020-02-03 17:42:42.557 T:1755308768   ERROR: CMMALVideo::Open : Video codec unknown: d
2020-02-03 17:42:42.558 T:1755308768  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: raw video
2020-02-03 17:42:42.562 T:1755308768  NOTICE: Creating video thread
2020-02-03 17:42:42.562 T:1442231008  NOTICE: running thread: video_thread
2020-02-03 17:42:42.563 T:1755308768  NOTICE: CVideoPlayer::OnExit()
2020-02-03 17:42:42.563 T:1755308768  NOTICE: Closing stream player 2
2020-02-03 17:42:42.564 T:1755308768  NOTICE: waiting for video thread to exit
2020-02-03 17:42:42.564 T:1442231008   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2020-02-03 17:42:42.564 T:1442231008  NOTICE: thread end: video_thread
2020-02-03 17:42:42.564 T:1755308768  NOTICE: deleting video codec
2020-02-03 17:42:42.565 T:1915545136  NOTICE: VideoPlayer: finished waiting
2020-02-03 17:42:42.565 T:1915545136  NOTICE: CVideoPlayer::CloseFile()
2020-02-03 17:42:42.566 T:1915545136  NOTICE: VideoPlayer: waiting for threads to exit
2020-02-03 17:42:42.566 T:1915545136  NOTICE: VideoPlayer: finished waiting
2020-02-03 17:44:14.945 T:1763701472  NOTICE: [Amazon VOD] postURL: http://127.0.0.1:41263/gpr/https%3A%2F%2Fatv-ps-eu.amazon.co.uk%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3DB07Q8VMHYJ%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3D4b5d1b5580f9bbc04172ce1d2c730dc154e745802eced0ffce089d9f%26marketplaceID%3DA1F83G8C2ARO7P%26format%3Djson%26version%3D1%26gascEnabled%3Dfalse%26subtitleFormat%3DTTMLv2%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%26supportedDRMKeyScheme%3DDUAL_KEY
2020-02-03 17:44:15.057 T:1755308768   ERROR: Traceback (most recent call last):
2020-02-03 17:44:15.058 T:1755308768   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2020-02-03 17:44:15.059 T:1755308768   ERROR:     self.finish_request(request, client_address)
2020-02-03 17:44:15.059 T:1755308768   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2020-02-03 17:44:15.060 T:1755308768   ERROR:     self.RequestHandlerClass(request, client_address, self)
2020-02-03 17:44:15.060 T:1755308768   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2020-02-03 17:44:15.061 T:1755308768   ERROR:     self.handle()
2020-02-03 17:44:15.061 T:1755308768   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2020-02-03 17:44:15.062 T:1755308768   ERROR:     self.handle_one_request()
2020-02-03 17:44:15.062 T:1755308768   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2020-02-03 17:44:15.063 T:1755308768   ERROR:     method()
2020-02-03 17:44:15.063 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 205, in do_POST
2020-02-03 17:44:15.064 T:1755308768   ERROR:     self._AlterGPR(unquote(path[1]), headers, data)
2020-02-03 17:44:15.064 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 239, in _AlterGPR
2020-02-03 17:44:15.065 T:1755308768   ERROR:     status_code, headers, content = self._ForwardRequest('get', endpoint, headers, data)
2020-02-03 17:44:15.066 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 85, in _ForwardRequest
2020-02-03 17:44:15.066 T:1755308768   ERROR:     from resources.lib.network import MechanizeLogin
2020-02-03 17:44:15.066 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 9, in <module>
2020-02-03 17:44:15.067 T:1755308768   ERROR:     import mechanicalsoup
2020-02-03 17:44:15.067 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/__init__.py", line 2, in <module>
2020-02-03 17:44:15.068 T:1755308768   ERROR:     from .browser import Browser
2020-02-03 17:44:15.068 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/browser.py", line 5, in <module>
2020-02-03 17:44:15.069 T:1755308768   ERROR:     from .form import Form
2020-02-03 17:44:15.069 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/form.py", line 5, in <module>
2020-02-03 17:44:15.072 T:1755308768   ERROR:     from bs4 import BeautifulSoup
2020-02-03 17:44:15.073 T:1755308768   ERROR: ImportError: cannot import name BeautifulSoup
2020-02-03 17:44:15.078 T:1763701472   ERROR: [Amazon VOD] Error reason: ('Connection aborted.', BadStatusLine("''",)) (ConnectionError)
2020-02-03 17:44:15.270 T:1915545136  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B07Q8VMHYJ&mode=PlayVideo&adult=0&name=1+-+Beginnings&trailer=0&selbitrate=0
2020-02-03 17:44:15.272 T:1576006368  NOTICE: Creating InputStream
2020-02-03 17:44:15.279 T:1576006368  NOTICE: Creating Demuxer
2020-02-03 17:44:15.282 T:1576006368  NOTICE: Opening stream: 0 source: 256
2020-02-03 17:44:15.283 T:1576006368  NOTICE: Creating video codec with codec id: 13
2020-02-03 17:44:15.283 T:1576006368   ERROR: CMMALVideo::Open : Video codec unknown: d
2020-02-03 17:44:15.284 T:1576006368  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: raw video
2020-02-03 17:44:15.288 T:1576006368  NOTICE: Creating video thread
2020-02-03 17:44:15.289 T:1522528992  NOTICE: running thread: video_thread
2020-02-03 17:44:15.290 T:1576006368  NOTICE: CVideoPlayer::OnExit()
2020-02-03 17:44:15.290 T:1576006368  NOTICE: VideoPlayer: eof, waiting for queues to empty
2020-02-03 17:44:15.291 T:1576006368  NOTICE: Closing stream player 2
2020-02-03 17:44:15.291 T:1576006368  NOTICE: waiting for video thread to exit
2020-02-03 17:44:15.291 T:1522528992   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2020-02-03 17:44:15.291 T:1522528992  NOTICE: thread end: video_thread
2020-02-03 17:44:15.291 T:1576006368  NOTICE: deleting video codec
2020-02-03 17:44:15.607 T:1915545136  NOTICE: CVideoPlayer::CloseFile()
2020-02-03 17:44:15.607 T:1915545136  NOTICE: VideoPlayer: waiting for threads to exit
2020-02-03 17:44:15.607 T:1915545136  NOTICE: VideoPlayer: finished waiting
2020-02-03 17:44:15.607 T:1915545136  NOTICE: CVideoPlayer::CloseFile()
2020-02-03 17:44:15.607 T:1915545136  NOTICE: VideoPlayer: waiting for threads to exit
2020-02-03 17:44:15.607 T:1915545136  NOTICE: VideoPlayer: finished waiting
2020-02-03 17:44:24.504 T:1763701472  NOTICE: [Amazon VOD] postURL: http://127.0.0.1:41263/gpr/https%3A%2F%2Fatv-ps-eu.amazon.co.uk%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3DB07Q8VMHYJ%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3D4b5d1b5580f9bbc04172ce1d2c730dc154e745802eced0ffce089d9f%26marketplaceID%3DA1F83G8C2ARO7P%26format%3Djson%26version%3D1%26gascEnabled%3Dfalse%26subtitleFormat%3DTTMLv2%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%26supportedDRMKeyScheme%3DDUAL_KEY
2020-02-03 17:44:24.583 T:1755308768   ERROR: Traceback (most recent call last):
2020-02-03 17:44:24.584 T:1755308768   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2020-02-03 17:44:24.584 T:1755308768   ERROR:     self.finish_request(request, client_address)
2020-02-03 17:44:24.584 T:1755308768   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2020-02-03 17:44:24.585 T:1755308768   ERROR:     self.RequestHandlerClass(request, client_address, self)
2020-02-03 17:44:24.585 T:1755308768   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2020-02-03 17:44:24.585 T:1755308768   ERROR:     self.handle()
2020-02-03 17:44:24.585 T:1755308768   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2020-02-03 17:44:24.585 T:1755308768   ERROR:     self.handle_one_request()
2020-02-03 17:44:24.586 T:1755308768   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2020-02-03 17:44:24.586 T:1755308768   ERROR:     method()
2020-02-03 17:44:24.586 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 205, in do_POST
2020-02-03 17:44:24.586 T:1755308768   ERROR:     self._AlterGPR(unquote(path[1]), headers, data)
2020-02-03 17:44:24.586 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 239, in _AlterGPR
2020-02-03 17:44:24.587 T:1755308768   ERROR:     status_code, headers, content = self._ForwardRequest('get', endpoint, headers, data)
2020-02-03 17:44:24.587 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 85, in _ForwardRequest
2020-02-03 17:44:24.587 T:1755308768   ERROR:     from resources.lib.network import MechanizeLogin
2020-02-03 17:44:24.587 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 9, in <module>
2020-02-03 17:44:24.587 T:1755308768   ERROR:     import mechanicalsoup
2020-02-03 17:44:24.587 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/__init__.py", line 2, in <module>
2020-02-03 17:44:24.588 T:1755308768   ERROR:     from .browser import Browser
2020-02-03 17:44:24.588 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/browser.py", line 5, in <module>
2020-02-03 17:44:24.588 T:1755308768   ERROR:     from .form import Form
2020-02-03 17:44:24.588 T:1755308768   ERROR:   File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/form.py", line 5, in <module>
2020-02-03 17:44:24.589 T:1755308768   ERROR:     from bs4 import BeautifulSoup
2020-02-03 17:44:24.589 T:1755308768   ERROR: ImportError: cannot import name BeautifulSoup
2020-02-03 17:44:24.593 T:1763701472   ERROR: [Amazon VOD] Error reason: ('Connection aborted.', BadStatusLine("''",)) (ConnectionError)
2020-02-03 17:44:24.777 T:1915545136  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B07Q8VMHYJ&mode=PlayVideo&adult=0&name=1+-+Beginnings&trailer=0&selbitrate=0
2020-02-03 17:44:24.779 T:1522528992  NOTICE: Creating InputStream
2020-02-03 17:44:24.784 T:1522528992  NOTICE: Creating Demuxer
2020-02-03 17:44:24.788 T:1522528992  NOTICE: Opening stream: 0 source: 256
2020-02-03 17:44:24.788 T:1522528992  NOTICE: Creating video codec with codec id: 13
2020-02-03 17:44:24.789 T:1522528992   ERROR: CMMALVideo::Open : Video codec unknown: d
2020-02-03 17:44:24.789 T:1522528992  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: raw video
2020-02-03 17:44:24.796 T:1522528992  NOTICE: Creating video thread
2020-02-03 17:44:24.797 T:1451225824  NOTICE: running thread: video_thread
2020-02-03 17:44:24.799 T:1522528992  NOTICE: CVideoPlayer::OnExit()
2020-02-03 17:44:24.799 T:1522528992  NOTICE: VideoPlayer: eof, waiting for queues to empty
2020-02-03 17:44:24.799 T:1522528992  NOTICE: Closing stream player 2
2020-02-03 17:44:24.800 T:1522528992  NOTICE: waiting for video thread to exit
2020-02-03 17:44:24.800 T:1451225824   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2020-02-03 17:44:24.800 T:1451225824  NOTICE: thread end: video_thread
2020-02-03 17:44:24.800 T:1522528992  NOTICE: deleting video codec
2020-02-03 17:44:25.123 T:1915545136  NOTICE: CVideoPlayer::CloseFile()
2020-02-03 17:44:25.123 T:1915545136  NOTICE: VideoPlayer: waiting for threads to exit
2020-02-03 17:44:25.124 T:1915545136  NOTICE: VideoPlayer: finished waiting
2020-02-03 17:44:25.124 T:1915545136  NOTICE: CVideoPlayer::CloseFile()
2020-02-03 17:44:25.124 T:1915545136  NOTICE: VideoPlayer: waiting for threads to exit
2020-02-03 17:44:25.124 T:1915545136  NOTICE: VideoPlayer: finished waiting
2020-02-03 17:45:42.399 T:1763701472  NOTICE: [Amazon VOD] postURL: http://127.0.0.1:41263/gpr/https%3A%2F%2Fatv-ps-eu.amazon.co.uk%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3DB07Q8VMHYJ%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3D4b5d1b5580f9bbc04172ce1d2c730dc154e745802eced0ffce089d9f%26marketplaceID%3DA1F83G8C2ARO7P%26format%3Djson%26version%3D1%26gascEnabled%3Dfalse%26subtitleFormat%3DTTMLv2%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%26supportedDRMKeyScheme%3DDUAL_KEY
2020-02-03 17:45:42.477 T:1576006368   ERROR: Traceback (most recent call last):
2020-02-03 17:45:42.477 T:1576006368   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2020-02-03 17:45:42.478 T:1576006368   ERROR:     self.finish_request(request, client_address)
2020-02-03 17:45:42.478 T:1576006368   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
2020-02-03 17:45:42.478 T:1576006368   ERROR:     self.RequestHandlerClass(request, client_address, self)
2020-02-03 17:45:42.479 T:1576006368   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
2020-02-03 17:45:42.479 T:1576006368   ERROR:     self.handle()
2020-02-03 17:45:42.479 T:1576006368   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
2020-02-03 17:45:42.479 T:1576006368   ERROR:     self.handle_one_request()
2020-02-03 17:45:42.480 T:1576006368   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
2020-02-03 17:45:42.480 T:1576006368   ERROR:     method()
2020-02-03 17:45:42.480 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 205, in do_POST
2020-02-03 17:45:42.480 T:1576006368   ERROR:     self._AlterGPR(unquote(path[1]), headers, data)
2020-02-03 17:45:42.480 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 239, in _AlterGPR
2020-02-03 17:45:42.481 T:1576006368   ERROR:     status_code, headers, content = self._ForwardRequest('get', endpoint, headers, data)
2020-02-03 17:45:42.481 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 85, in _ForwardRequest
2020-02-03 17:45:42.481 T:1576006368   ERROR:     from resources.lib.network import MechanizeLogin
2020-02-03 17:45:42.481 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 9, in <module>
2020-02-03 17:45:42.481 T:1576006368   ERROR:     import mechanicalsoup
2020-02-03 17:45:42.482 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/__init__.py", line 2, in <module>
2020-02-03 17:45:42.482 T:1576006368   ERROR:     from .browser import Browser
2020-02-03 17:45:42.482 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/browser.py", line 5, in <module>
2020-02-03 17:45:42.482 T:1576006368   ERROR:     from .form import Form
2020-02-03 17:45:42.482 T:1576006368   ERROR:   File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/form.py", line 5, in <module>
2020-02-03 17:45:42.483 T:1576006368   ERROR:     from bs4 import BeautifulSoup
2020-02-03 17:45:42.483 T:1576006368   ERROR: ImportError: cannot import name BeautifulSoup
2020-02-03 17:45:42.487 T:1763701472   ERROR: [Amazon VOD] Error reason: ('Connection aborted.', BadStatusLine("''",)) (ConnectionError)
2020-02-03 17:45:42.749 T:1915545136  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B07Q8VMHYJ&mode=PlayVideo&adult=0&name=1+-+Beginnings&trailer=0&selbitrate=0
2020-02-03 17:45:42.765 T:1432351456  NOTICE: Creating InputStream
2020-02-03 17:45:42.772 T:1432351456  NOTICE: Creating Demuxer
2020-02-03 17:45:42.776 T:1432351456  NOTICE: Opening stream: 0 source: 256
2020-02-03 17:45:42.778 T:1432351456  NOTICE: Creating video codec with codec id: 13
2020-02-03 17:45:42.778 T:1432351456   ERROR: CMMALVideo::Open : Video codec unknown: d
2020-02-03 17:45:42.779 T:1432351456  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: raw video
2020-02-03 17:45:42.785 T:1432351456  NOTICE: Creating video thread
2020-02-03 17:45:42.786 T:1442231008  NOTICE: running thread: video_thread
2020-02-03 17:45:42.788 T:1432351456  NOTICE: CVideoPlayer::OnExit()
2020-02-03 17:45:42.789 T:1432351456  NOTICE: VideoPlayer: eof, waiting for queues to empty
2020-02-03 17:45:42.790 T:1432351456  NOTICE: Closing stream player 2
2020-02-03 17:45:42.791 T:1432351456  NOTICE: waiting for video thread to exit
2020-02-03 17:45:42.791 T:1442231008   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2020-02-03 17:45:42.791 T:1442231008  NOTICE: thread end: video_thread
2020-02-03 17:45:42.792 T:1432351456  NOTICE: deleting video codec
2020-02-03 17:45:43.098 T:1915545136  NOTICE: CVideoPlayer::CloseFile()
2020-02-03 17:45:43.099 T:1915545136  NOTICE: VideoPlayer: waiting for threads to exit
2020-02-03 17:45:43.099 T:1915545136  NOTICE: VideoPlayer: finished waiting
2020-02-03 17:45:43.099 T:1915545136  NOTICE: CVideoPlayer::CloseFile()
2020-02-03 17:45:43.099 T:1915545136  NOTICE: VideoPlayer: waiting for threads to exit
2020-02-03 17:45:43.099 T:1915545136  NOTICE: VideoPlayer: finished waiting
2020-02-03 17:46:01.227 T:1915545136   ERROR: Corrupt archive: special://temp/archive_cache/10025-7d592ece.fi
2020-02-03 17:46:01.259 T:1763701472  NOTICE: [Amazon VOD] Version: 0.8.2~beta
2020-02-03 17:46:01.261 T:1763701472  NOTICE: [Amazon VOD] Unicode filename support: False
2020-02-03 17:46:01.263 T:1763701472  NOTICE: [Amazon VOD] Locale: en-gb / Language: en
`

I'll close this though as the stable is working fine now.  Thank you.

**Comment by Varstahl** [comment]
The log you provided reports these two errors:
```
 ERROR:     import bs4
 ERROR: ValueError: bad marshal data (unknown type code)
 ERROR:     from bs4 import BeautifulSoup
 ERROR: ImportError: cannot import name BeautifulSoup
```
Most likely you or some addon installed a version of BeautifulSoup4 which is not compatible with the version of Kodi you're running. Or there could have been a temporary problem with the official repositories, I don't know. It doesn't look like an addon problem though, but thanks for reporting anyway.

Enjoy your shows.

**Comment by Ralf-Jonas** [comment]
Hi. I'm a german user trying to install the Amazon VOD plugin in KODI on a freshly installed Raspi 4. I can't see any video from Amazon, because I always get these two lines in the log file when I press the play button:

NOTICE: Creating video codec with codec id: 13
 ERROR: CMMALVideo::Open : Video codec unknown: d

No other errors like those mentioned above by yknivag for example.

I know, the python sources for the plugin are in the .kodi subdirectory and I'm pretty sure to have the most recent sources from the stable tree. What do I have to change in these sources to get the videos running?

Thanks in advance

**Comment by yknivag** [comment]
@Ralf-Jonas you will get a quicker and better response to your specific problem is you start a new issue and fill in every section of the template along with a full log.

As I understand it there are some particular differences in the way Amazon provides the service in Germany and so it will help the developers to have the full information from you.

Hope you get up and running quickly.
