### ISSUE TITLE
Error when loading some series categories

### ISSUE THREAD

**Issue by fariouche** [Sandmann79/xbmc#457]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version [e.g. 0.7.5]

**Prime Video Account (select one)**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: [e.g. RPi]
x86_64 amd
- OS Version: [e.g. Windows 10]
gentoo 64
- Kodi Version [e.g. 18.4]
18.4

**Describe the bug**
When I try to enter some sections, like for example Comedy series, it starts to display loading page x... and after some time, when loading page 5, I get an error.
This is a french account, but I believe that there is something returned in the json the it does not like (is it related to the collision detected warning?).
Or maybe one of the episode is not formatted correctly with a missing field (parentTitle)

This is the relevant log:

2020-04-19 17:22:58.450 T:139766171375360   DEBUG: [Amazon VOD] Unable to parse month "janv. 01, 2016 01:00 CET" with language "fr_FR": trying english
2020-04-19 17:22:58.450 T:139766171375360 WARNING: [Amazon VOD] Unable to parse month "janv. 01, 2016 01:00 CET" with any known language combination
2020-04-19 17:22:58.696 T:139760383293184 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-04-19 17:23:01.298 T:139766171375360 WARNING: Previous line repeats 5 times.
2020-04-19 17:23:01.298 T:139766171375360 WARNING: [Amazon VOD] Collision detected during JSON objects merging, overwriting and praying (type: <type 'unicode'>)
2020-04-19 17:23:01.300 T:139766171375360 WARNING: Previous line repeats 11 times.
2020-04-19 17:23:01.300 T:139766171375360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'parentTitle'
                                            Traceback (most recent call last):
                                              File "/home/fariouche/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/fariouche/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 63, in EntryPoint
                                                elif 'browse' == verb: g.pv.Browse(path)
                                              File "/home/fariouche/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 451, in Browse
                                                node, breadcrumb = self._TraverseCatalog(path)
                                              File "/home/fariouche/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 371, in _TraverseCatalog
                                                self._LazyLoad(node[nodeName], pathList[0:1 + i])
                                              File "/home/fariouche/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 1182, in _LazyLoad
                                                bUpdatedVideoData |= AddSeason(breadcrumb[-1], o, title, iu)
                                              File "/home/fariouche/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 757, in AddSeason
                                                bUpdatedVideoData |= ParseSinglePage(oid, season, False, url=url)
                                              File "/home/fariouche/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 1049, in ParseSinglePage
                                                vd['metadata']['videometa']['tvshowtitle'] = item['parentTitle']
                                            KeyError: u'parentTitle'
                                            -->End of Python script error report<--
2020-04-19 17:23:01.300 T:139766171375360   DEBUG: onExecutionDone(30, /home/fariouche/.kodi/addons/plugin.video.amazon-test/default.py)
2020-04-19 17:23:01.316 T:139766734616960   DEBUG: ------ Window Init (DialogNotification.xml) ------
2020-04-19 17:23:01.353 T:139766171375360 WARNING: CPythonInvoker(30, /home/fariouche/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/fariouche/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon7xbmcgui6DialogE
2020-04-19 17:23:01.353 T:139766171375360    INFO: Python interpreter stopped
2020-04-19 17:23:01.353 T:139766171375360   DEBUG: Thread LanguageInvoker 139766171375360 terminating
2020-04-19 17:23:01.368 T:139766406305536   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/S%C3%A9ries/S%C3%A9ries+de+vos+Cha%C3%AEnes+
2020-04-19 17:23:01.368 T:139766406305536   DEBUG: Thread waiting 139766406305536 terminating
2020-04-19 17:23:01.381 T:139766734616960   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2020-04-19 17:23:01.381 T:139766734616960   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/S%C3%A9ries/S%C3%A9ries+de+vos+Cha%C3%AEnes+) failed
2020-04-19 17:23:01.381 T:139766734616960   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.amazon-test/pv/browse/root/S%C3%A9ries)
2020-04-19 17:23:01.381 T:139766734616960   DEBUG:   ParentPath = [plugin://plugin.video.amazon-test/]

**Comment by Varstahl** [comment]
It's already fixed in 92280e45d85b1a50c766279942daaa57f5aaccc6, update will be released shortly.

**Comment by fariouche** [comment]
Great! Thanks guys!  You rock

**Comment by croutor** [comment]
I'm also facing the same issue. Thanks for your good work!

**Comment by fariouche** [comment]
I confirm that this fixes the issue I've reported ;)
