### ISSUE TITLE
Watchlist API call returns 404

### ISSUE THREAD

**Issue by DasLampe** [Sandmann79/xbmc#465]
**Addon used**
- [ ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version 0.8.3

**Prime Video Account (select one)**
- [ ] primevideo.com
- [ x] amazon.de

**System Setup**
- Hardware: RPi
- OS Version: Raspbian Stretch
- Kodi Version 18.2

**Log**
```
 [Amazon VOD] Service: Proxy bound to 127.0.0.1:52119
2020-05-05 20:05:23.180 T:1684001504  NOTICE: [Amazon VOD] Service: Proxy server started
2020-05-05 20:05:23.181 T:1684001504  NOTICE: [Amazon VOD] Service started
2020-05-05 20:05:38.027 T:1502597856  NOTICE: [Amazon VOD] Version: 0.8.3
2020-05-05 20:05:38.028 T:1502597856  NOTICE: [Amazon VOD] Unicode filename support: False
2020-05-05 20:05:38.029 T:1502597856  NOTICE: [Amazon VOD] Locale: en-us / Language: en
2020-05-05 20:05:44.429 T:1502597856  NOTICE: [Amazon VOD] getURL: https://www.amazon.de/gp/video/api/watchlist/?ie=UTF8&sort=DATE_ADDED_DESC&contentType=TV&startIndex=0
2020-05-05 20:05:44.845 T:1502597856   ERROR: [Amazon VOD] Error reason: 404 error (NoRetries)
2020-05-05 20:05:44.853 T:1502597856   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: list indices must be integers, not unicode
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/root/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 77, in EntryPoint
                                                g.amz.listContent(args.get('cat'), url, int(args.get('page', '1')), args.get('opt', ''), int(args.get('export', '0')))
                                              File "/root/.kodi/addons/plugin.video.amazon-test/resources/lib/amazontld.py", line 380, in listContent
                                                titles, parent = self.getList(catalog, export, url, page)
                                              File "/root/.kodi/addons/plugin.video.amazon-test/resources/lib/amazontld.py", line 780, in getList
                                                asins = self._scrapeAsins(url, cj)
                                              File "/root/.kodi/addons/plugin.video.amazon-test/resources/lib/amazontld.py", line 768, in _scrapeAsins
                                                for item in json['content'].get('items', []):
                                            TypeError: list indices must be integers, not unicode
                                            -->End of Python script error report<--
2020-05-05 20:05:44.956 T:1502597856 WARNING: CPythonInvoker(3, /root/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/root/.kodi/addons/plugin.video.amazon-test/default.py" has left severa
l classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon9xbmcaddon5AddonE
2020-05-05 20:05:44.959 T:1510990560   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/?cat=watchlist&mode=listContent&opt&page=1&url=TV
2020-05-05 20:05:44.969 T:1901626208   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/?cat=watchlist&mode=listContent&opt&page=1&url=TV) failed
```

**Describe the bug**
Get an error when try to access Watchlist -> Televion or Watchlist -> Movies.
There is no Problem to access Movies directly.

**Comment by nxdefiant** [comment]
Same here, worked until yesterday.

**Comment by Varstahl** [comment]
As far as I could tell, Amazon removed watchlist a bit everywhere, and have somewhat streamlined it. The watchlist is gone from PrimeVideo as well. Now it's been replaced with "MyStuff", which includes the "Watchlist" sub-menu and the "Buy/Rent" sub-menu. Might be the same thing on the TLDs.

**Comment by Sandmann79** [comment]
They changed this [some month ago](22d35b4c535b4fd29949dd8560201588f357a267) for tlds, but I didn't know, why i revert it :confused:. 
Has been fixed with f3563e928fda67175f91d5ff6b6ad53afad2b668.

**Comment by Paco8** [comment]
Primevideo also fails for me with a 404 error since yesterday.
```
2020-05-07 09:06:13.342 T:14324    INFO: [Amazon VOD] startup.py:39 Requested /pv/browse/root/Mi+espacio/MOVIE
2020-05-07 09:06:13.353 T:14324    INFO: [Amazon VOD] network.py:144 getURL: https://www.primevideo.com/api/watchlist/ref=atv_wtlp_mv?startIndex=0&sort=DATE_ADDED_DESC&contentType=MOVIE&primeOnly=false
2020-05-07 09:06:13.416 T:5768   DEBUG: ------ Window Init (DialogBusy.xml) ------
2020-05-07 09:06:14.923 T:14324   ERROR: [Amazon VOD] network.py:183 Error reason: 404 error (NoRetries)
2020-05-07 09:06:14.927 T:14324   ERROR: [Amazon VOD] primevideo.py:1140 Unable to fetch the url: /api/watchlist/ref=atv_wtlp_mv?startIndex=0&sort=DATE_ADDED_DESC&contentType=MOVIE&primeOnly=false

```

Full log: https://pastebin.com/x9UA7MiC

**Comment by Sandmann79** [comment]
@Varstahl has already created issue #466 for PrimeVideo users

**Comment by Varstahl** [comment]
@Paco8 the endpoints changed.
