### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by fernandog** [Sandmann79/xbmc#469]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
- Addon Version: 0.8.4

**Prime Video Account (select one)**
- [x] primevideo.com
- [] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi
- OS Version: OSMC Linux ARM (Thumb) 32-bit (version for Raspberry Pi)
- Kodi Version: 18.6

**Upload Logs**
```
2020-05-10 12:46:01.184 T:1714209504  NOTICE: [Amazon VOD] Version: 0.8.4
2020-05-10 12:46:01.184 T:1714209504  NOTICE: [Amazon VOD] Unicode filename support: False
2020-05-10 12:46:01.186 T:1714209504  NOTICE: [Amazon VOD] Locale: pt-br / Language: en
2020-05-10 12:46:14.524 T:1714209504   ERROR: [Amazon VOD] Error reason: 404 error (NoRetries)
2020-05-10 12:46:14.562 T:1714209504   ERROR: [Amazon VOD] Unable to fetch the url: /api/watchlist/ref=atv_wtlp_tv?startIndex=0&sort=DATE_ADDED_DESC&contentType=TV&primeOnly=false
2020-05-10 12:46:17.796 T:1714209504   ERROR: [Amazon VOD] Error reason: 404 error (NoRetries)
2020-05-10 12:46:17.797 T:1714209504   ERROR: [Amazon VOD] Unable to fetch the url: /api/watchlist/ref=atv_wtlp_tv?startIndex=0&sort=DATE_ADDED_DESC&contentType=TV&primeOnly=false
2020-05-10 12:46:19.274 T:1714209504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 63, in EntryPoint
                                                elif 'browse' == verb: g.pv.Browse(path)
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 468, in Browse
                                                entry = node[key]
                                            TypeError: string indices must be integers
                                            -->End of Python script error report<--
```
**Describe the bug**
Nothing shows up after loading the addon but a error message asking to see logs. Yesterday was working great. Original mobile app works normal

**Comment by Varstahl** [comment]
Dupe #466
