### ISSUE TITLE
Accessing the "watchlist" generates an error

### ISSUE THREAD

**Issue by tkocou** [Sandmann79/xbmc#473]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4
- OS version: LibreELEC 9.2.0
- Kodi version number: 18.5

**Upload Logs**

**Describe the bug**

Accessing the Watchlist in the menu causes a VOD error. Going to the "TV Shows, Movies or via Search menu items" and the addon works as expected. The Kodi log talks about a JSON error.

[amazon.log](https://github.com/Sandmann79/xbmc/files/4663587/amazon.log)

**Comment by Varstahl** [comment]
Please enable debug logging and attach a full log, also you didn't specify the addon version.

**Comment by tkocou** [comment]
Amazon addon is the latest (0.8.5) packaged with the "sandman" repo archive. Enabled the debug as requested and attempted to access the watchlist -> TV Shows option. Log file is uploaded.
[kodi.log](https://github.com/Sandmann79/xbmc/files/4665405/kodi.log)

**Comment by tkocou** [comment]
The zipfile repository is called "repository.sandmann79.plugins-1.0.2.zip"

**Comment by samritkunja** [comment]
refer #466 . There is a master repository with some files you need to paste inside the directory of the addon. It works properly again.

**Comment by Varstahl** [comment]
@samritkunja 0.8.5 already contains the fixes, and also is about PrimeVideo, not amazon.com. Need to wait for @Sandmann79 to weigh in on this.

**Comment by tkocou** [comment]
@samritkunja, Which files do I need to paste into the addon?

**Comment by samritkunja** [comment]
Hey. as @Varstahl commented, the fix for me was different as I am using primevideo.com . If you still want to try, download the zip file https://github.com/Sandmann79/xbmc/archive/master.zip , and copy the contents of the folder plugin.video.amazon-test. In kodi, go to userdata/addon_data/plugin.video.amazon-test and paste the contents there. You will have to try and use the add on again, the go to the same location and delete the cache file *.pvcp . 

This only worked for me once I re-installed the add-on. Again, you may already have the latest version or have a problem different to mine. 

Cheers.

**Comment by zaphod24** [comment]
I've downloaded the latest master and replaced the plugin.video.amazon-test folder with the contents of plugin.video.amazon-test in the zip file, deleted the userdata/addon_data/plugin.video.amazon-test and configured logon again. I am still seeing this error when trying to access the watchlist:

020-05-24 11:31:45.151 T:3272991616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'titles'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 77, in EntryPoint
                                                g.amz.listContent(args.get('cat'), url, int(args.get('page', '1')), args.get('opt', ''), int(args.get('export', '0')))
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/amazontld.py", line 395, in listContent
                                                if not titles or not len(titles['titles']):
                                            KeyError: u'titles'
                                            -->End of Python script error report<--

**Comment by Sandmann79** [comment]
@zaphod24 that's a different bug, as of @tkocou. This should be fixed with https://github.com/Sandmann79/xbmc/commit/ce2a560ae7445c258d80d503de7a0b401b3a531e

@tkocou please enable verbose logging at addon settings, open watchlist again and upload avod-watchlist.log here.

**Comment by tkocou** [comment]
I enabled all logging that I could find through the Kodi interface and was unable to generate the avod-watchlist.log. I even rebooted the system in case the logging needed to be enabled during boot-up. No success. As a different thought, I zipped up the _/storage/.kodi/addons/plugin.video.amazon-test_  directory and have uploaded it for forensics.
[amazon-test.zip](https://github.com/Sandmann79/xbmc/files/4679618/amazon-test.zip)

As a side note: I downloaded the xbmc-master zip file and copied over the contents of the plugin.video.amazon-test directory to the /storage/.kodi/addons/plugin.video.amazon-test directory.
After rebooting, the watchlist problem was resolved. So feel free to close this thread.

**Comment by zaphod24** [comment]
I've replaced my plugin with the latest master and now have this in the logs:

2020-05-26 15:35:49.136 T:3378463616  NOTICE: [Amazon VOD] getURL: https://www.amazon.com/gp/video/api/myStuffWatchlist?viewType=watchlist&args={"watchlist":{"sort":"DATE_ADDED_DESC","libraryType":"Items","contentType":"TV","primeOnly":false,"startIndex":0},"shared":{"isPurchaseRow":0}}
2020-05-26 15:35:49.869 T:3378463616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 77, in EntryPoint
                                                g.amz.listContent(args.get('cat'), url, int(args.get('page', '1')), args.get('opt', ''), int(args.get('export', '0')))
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/amazontld.py", line 387, in listContent
                                                titles, parent = self.getList(catalog, export, url, page)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/amazontld.py", line 812, in getList
                                                info, asins = self._scrapeAsins(url, cj)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/amazontld.py", line 788, in _scrapeAsins
                                                json = getURL(url, useCookie=cj, binary=True)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 208, in getURL
                                                res = json.loads(response) if rjson else response
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
