### ISSUE TITLE
Amazon VOD crash on login attempt

### ISSUE THREAD

**Issue by joonty** [Sandmann79/xbmc#5]
I'm using the most recent Kodi nightly build for OSX (20160602), and am getting an error when trying to use the Amazon VOD app (UK, if that makes any difference). This error is triggered when an attempt is made to log in. The logs show the following Python exception:

```
11:58:02 T:123145302839296  NOTICE: [Amazon VOD] [('cat', 'Browse'), ('mode', 'getList'), ('page', '1'), ('url', 'watchlist')]
11:58:02 T:123145302839296  NOTICE: [Amazon VOD] Login
11:58:02 T:123145302839296   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: Invalid data length, data must be a multiple of 8 bytes
                                            .
                                            Traceback (most recent call last):
                                              File "/Users/jon/Library/Application Support/Kodi/addons/plugin.video.amazon-test/default.py", line 1630, in <module>
                                                elif mode == 'getList': getList(url, int(export))
                                              File "/Users/jon/Library/Application Support/Kodi/addons/plugin.video.amazon-test/default.py", line 669, in getList
                                                cj = MechanizeLogin()
                                              File "/Users/jon/Library/Application Support/Kodi/addons/plugin.video.amazon-test/default.py", line 1236, in MechanizeLogin
                                                succeeded = LogIn()
                                              File "/Users/jon/Library/Application Support/Kodi/addons/plugin.video.amazon-test/default.py", line 1252, in LogIn
                                                password = decode(addon.getSetting('login_pass'))
                                              File "/Users/jon/Library/Application Support/Kodi/addons/plugin.video.amazon-test/default.py", line 1330, in decode
                                                d = k.decrypt(base64.b64decode(data))
                                              File "/Users/jon/Library/Application Support/Kodi/addons/script.module.pydes/lib/pyDes.py", line 836, in decrypt
                                                block = self.__key3.crypt(iv,    DECRYPT)
                                              File "/Users/jon/Library/Application Support/Kodi/addons/script.module.pydes/lib/pyDes.py", line 572, in crypt
                                                raise ValueError("Invalid data length, data must be a multiple of " + str(self.block_size) + " bytes\n.")
                                            ValueError: Invalid data length, data must be a multiple of 8 bytes
                                            .
                                            -->End of Python script error report<--
```

I also tried with an earlier build (20160531), and the same. Do you know what could be causing this?

**Comment by Sandmann79** [comment]
This error appears if no MAC address or machine name can be determined. These are required for the password encoding. To get rid of this error, just disable "Remember Credentials" in settings. If the "Dont save cookie" option is disabled (default), the addon creates a cookie for later logins.

**Comment by joonty** [comment]
Hmm, ok. Any idea why it wouldn't be able to determine that? I've had no issue with other software detecting the MAC address or machine name.

Thanks
