### ISSUE TITLE
Amazon Login doesn´t work 

### ISSUE THREAD

**Issue by bewi93** [Sandmann79/xbmc#552]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.91

**Account type**
- [ ] primevideo.com
- [x ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Rasperrypi 3b
- OS version: OSMC November 2020 2020.11-1
- Kodi version number:18.9

**Upload Logs**
Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NotImplementedError'>
                                            Error Contents: Cannot execute CSS selectors because the soupsieve package is not installed.
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 102, in EntryPoint
                                                exec('{}()'.format(mode))
                                              File "<string>", line 1, in <module>
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 582, in LogIn
                                                form = br.select_form('form[name="signIn"]')
                                              File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/stateful_browser.py", line 202, in select_form
                                                limit=nr + 1)
                                              File "/home/osmc/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py", line 1871, in select
                                                "Cannot execute CSS selectors because the soupsieve package is not installed."
                                            NotImplementedError: Cannot execute CSS selectors because the soupsieve package is not installed.
                                            -->End of Python script error report<--
2021-03-26 17:01:09.174 T:1795158240 WARNING: CPythonInvoker(8, /home/osmc/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in me$
2021-03-26 17:01:09.181 T:1483337952   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/
2021-03-26 17:01:09.186 T:1916560304   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed
`

**Describe the bug**

Hello Guys,

today my Addon said, that my Userdata is wrong. So i deleted the userdatas and cookies from Amazon-addon and rebooted my Rp3. After that the login failed. As i can see from the code above there is a package soupsieve is missing. So i tried installing it manually via
 `sudo apt-get install python3-bs4`
but that didnt work either. Did you have an Idea what happend and how i can fix it?

**Comment by bewi93** [comment]
Okay sometimes it is the best idea to look for a solution on yourselfe :-)

I installed Pip Manager via 
`sudo apt-get install python-pip
`
and installed manually
`pip install soupsieve`

now its working again. Im hoping that helps, if someone else got this issue

**Comment by bewi93** [comment]
I installed Pip Manager via
`sudo apt-get install python-pip`
and installed manually
`pip install soupsieve`

Now i can login again, but after saying that im succesfully logged in, it get into an infinite loading screen. If i end this Loading screen and try again to open the Amazon-app i get in. After the first try i got the same issue "my Account details are wrong, please relog" or something like this. After the second try it worked! Looks like something is a bit buggy.
