### ISSUE TITLE
Not possible to connect Amazon prime video with french account

### ISSUE THREAD

**Issue by Jonathanr67** [Sandmann79/xbmc#556]
**Addon used**
- [ X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)
0.9.3 Amazon VOD
- Addon version: 
Amazon VOD 0.9.3

**Account type**
- [X ] primevideo.com French Account
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: raspberry pi 4
- OS version: librelec pi4 arm 9.2.6
- Kodi version number: 18.9 leia pi4

**Upload Logs**
Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NotImplementedError'>
                                            Error Contents: Cannot execute CSS selectors because the soupsieve package is not installed.
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 102, in EntryPoint
                                                exec('{}()'.format(mode))
                                              File "<string>", line 1, in <module>
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 582, in LogIn
                                                form = br.select_form('form[name="signIn"]')
                                              File "/storage/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/stateful_browser.py", line 215, in select_form
                                                limit=nr + 1)
                                              File "/storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py", line 1871, in select
                                                "Cannot execute CSS selectors because the soupsieve package is not installed."
                                            NotImplementedError: Cannot execute CSS selectors because the soupsieve package is not installed.
                                            -->End of Python script error report<--

Upload `kodi.log` somewhere and post the link here. If you need help finding it, read the appropriate entry in the FAQs (https://github.com/Sandmann79/xbmc/wiki/FAQ#what-is-debug-logging--how-can-i-enable-debug-logging-in-kodi).
For Login issues, enable advanced logging in the settings, upload the `(amazon/avod)-login` files from the Kodi Home (https://kodi.wiki/view/Special_protocol) folder, and paste the link here, as well.  -->

**Describe the bug**

Can not connect to my account, i have Amazon VOD error, please check your log
I have a french account and can not connect the amazon VOD addon in kodi with my email and password
I try to change region in Amazon VOD setting with no success.

**Comment by Varstahl** [comment]
A simple search for `soupsieve` in the issues would have told you that you installed BeautifulSoup from a different, non official, broken repository. Remove whatever version you have of it and install the module through the official repos.
