### ISSUE TITLE
Latest widevine update breakes streaming with inputstream

### ISSUE THREAD

**Issue by mhutzsch** [Sandmann79/xbmc#558]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 
0.9.3

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry PI 2
- OS version: libreelec 9.2.6
- Kodi version number: 18.9

**Upload Logs**

```bash
2021-05-09 13:02:05.544 T:1396511616   ERROR: /storage/.kodi/addons/script.module.beautifulsoup4/lib/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
                                              'The soupsieve package is not installed. CSS selectors cannot be used.'
2021-05-09 13:02:07.219 T:1396511616  NOTICE: [script.module.inputstreamhelper] Widevine update check was made on 2021-05-08 20:37
2021-05-09 13:02:07.266 T:1396511616  NOTICE: [Amazon VOD] postURL: http://127.0.0.1:54185/gpr/https%3A%2F%2Fatv-ps-eu.amazon.de%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3DB00H39RRYI%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3Ddfbf163f4e159ffafcd62bea0769917b055b83df0cb296fee7151321%26marketplaceID%3DA1PA6795UKMFR9%26format%3Djson%26version%3D1%26gascEnabled%3Dfalse%26subtitleFormat%3DTTMLv2%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%2CTransitionTimecodes%26supportedDRMKeyScheme%3DDUAL_KEY
2021-05-09 13:02:08.000 T:1396511616  NOTICE: [Amazon VOD] Using Host: Cloudfront
2021-05-09 13:02:08.005 T:1396511616  NOTICE: [Amazon VOD] checkURL: https://pop-dub-ww.cf.dash.row.aiv-cdn.net/dm/2$Ncpfc3djYnCY0cpI45XKURf-Vuc~/988e/4cd0/914d/409a-8ee7-d71f12d566b0/84fb21bc-8aa6-40c3-8b74-99c4215253d5_corrected.mpd
2021-05-09 13:02:08.793 T:1396511616  NOTICE: [Amazon VOD] Using inputstream.adaptive Version: 2.4.7.1
2021-05-09 13:02:09.431 T:1936957456  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B00H39RRYI&mode=PlayVideo&adult=0&name=Ich+-+Einfach+unverbesserlich&trailer=0&selbitrate=0
2021-05-09 13:02:09.434 T:1356505984  NOTICE: Creating InputStream
2021-05-09 13:02:09.484 T:1356505984   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
2021-05-09 13:02:37.593 T:1356505984   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
2021-05-09 13:02:37.594 T:1356505984 WARNING: CCurlFile::FillBuffer - Reconnect, (re)try 1
2021-05-09 13:02:44.768 T:1356505984   ERROR: CCurlFile::FillBuffer - Failed: Requested range was not delivered by the server(33)
 2021-05-09 13:02:44.797 T:1356505984   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)
2021-05-09 13:02:44.798 T:1356505984   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
2021-05-09 13:02:44.803 T:1356505984   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.amazon-test/?asin=B00H39RRYI&mode=PlayVideo&adult=0&name=Ich+-+Einfach+unverbesserlich&trailer=0&selbitrate=0]
2021-05-09 13:02:44.804 T:1356505984  NOTICE: CVideoPlayer::OnExit()
2021-05-09 13:02:44.889 T:1936957456  NOTICE: CVideoPlayer::CloseFile()
2021-05-09 13:02:44.890 T:1936957456  NOTICE: VideoPlayer: waiting for threads to exit
2021-05-09 13:02:44.890 T:1936957456  NOTICE: VideoPlayer: finished waiting
2021-05-09 13:02:51.605 T:1347429248   ERROR: Traceback (most recent call last):
2021-05-09 13:02:51.606 T:1347429248   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
2021-05-09 13:02:52.141 T:1347429248   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2021-05-09 13:02:52.144 T:1347429248   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
2021-05-09 13:02:52.145 T:1347429248   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
2021-05-09 13:02:52.145 T:1347429248   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2021-05-09 13:02:52.146 T:1347429248   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2021-05-09 13:02:52.146 T:1347429248   ERROR: error: [Errno 32] Broken pipe
2021-05-09 13:02:53.071 T:1374790528   ERROR: Traceback (most recent call last):
2021-05-09 13:02:53.071 T:1374790528   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
2021-05-09 13:02:53.073 T:1374790528   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
2021-05-09 13:02:53.074 T:1374790528   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
2021-05-09 13:02:53.074 T:1374790528   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
2021-05-09 13:02:53.074 T:1374790528   ERROR:   File "/usr/lib/python2.7/socket.py", line 283, in close
2021-05-09 13:02:53.075 T:1374790528   ERROR:   File "/usr/lib/python2.7/socket.py", line 307, in flush
2021-05-09 13:02:53.075 T:1374790528   ERROR: error: [Errno 32] Broken pipe
```

**Describe the bug**

I simply updated widevine and wanted to start a stream. Since this update it fails - I am not sure if the update broke the inputstream.
I tried to re-login, which suceeded, but did not help to start streams.
Several reboots / restarts did not help.

I checked the filesystem if the in the error log listed files exist:
```bash
LibreELEC:~/.kodi/cdm # ll
total 9104
drwxr-xr-x    3 root     root          1024 May  8 20:37 .
drwxr-xr-x    9 root     root          1024 Nov 29 16:44 ..
-rw-r--r--    1 root     root          1806 May  1 20:41 EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED.challenge
-rw-r--r--    1 root     root            89 May  1 20:41 EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED.init
-rw-r--r--    1 root     root          1843 May  1 20:41 EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED.response
-rw-r--r--    2 root     root           606 May  8 20:37 config.json
-rwxr--r--    2 root     root       8887360 May  8 20:37 libwidevinecdm.so
-rw-r--r--    1 root     root        172006 Jun  6  2020 recovery.conf.json
-rw-r--r--    2 root     root        250249 May  8 20:37 recovery.json
drwxr-xr-x   23 root     root          3072 Jul 11  2020 widevine
LibreELEC:~/.kodi/cdm # pwd
/storage/.kodi/cdm
LibreELEC:~/.kodi/cdm #
```
I found one possible problem, because the inputstream.adaptive directory does not exist in the expected path:
```bash
LibreELEC:~/.kodi/cdm # ll /usr/lib/kodi/addons/inputstream.adaptive/
ls: /usr/lib/kodi/addons/inputstream.adaptive/: No such file or directory
LibreELEC:~/.kodi/cdm # find / -name inputstream.adaptive
/storage/.kodi/userdata/addon_data/inputstream.adaptive
/storage/.kodi/addons/inputstream.adaptive
```
symlinking /storage/.kodi/addons/inputstream.adaptive to /usr/lib/kodi/addons/inputstream.adaptive/ is not possible, because / is mounted ro in libreelec.

Any Ideas how to the addon work again?

**Comment by BlackEdder** [comment]
Not sure if this is the same error or not, but for me it also stopped working after the latest widevine update. The relevant error message on my side is:

```
2021-05-09 14:55:03.010 T:1915769776  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B00HNGBGBQ&mode=PlayVideo&adult=0&name=4+-+Fry+and+the+Slurm+Factory&trailer=0&selbitrate=0
2021-05-09 14:55:03.016 T:1254093024  NOTICE: Creating InputStream
2021-05-09 14:55:03.610 T:1254093024   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/home/osmc/.kodi/cdm/libwidevinecdm.so)
2021-05-09 14:55:03.610 T:1254093024   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
2021-05-09 14:55:03.613 T:1254093024   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.amazon-test/?asin=B00HNGBGBQ&mode=PlayVideo&adult=0&name=4+-+Fry+and+the+Slurm+Factory&trailer=0&selbitrate=0]
2021-05-09 14:55:03.613 T:1254093024  NOTICE: CVideoPlayer::OnExit()
2021-05-09 14:55:03.753 T:1915769776  NOTICE: CVideoPlayer::CloseFile()
```

This error seems different than above, except for the: `ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/home/osmc/.kodi/cdm/libwidevinecdm.so)` part of the message.

The libwidevinecdm file does exists:

```
$ ls -alhtr .kodi/cdm/
total 8.8M
-rwxr--r-- 4 osmc osmc 8.5M May  9 14:52 libwidevinecdm.so
-rw-r--r-- 3 osmc osmc 245K May  9 14:52 recovery.json
-rw-r--r-- 3 osmc osmc  606 May  9 14:52 config.json
drwxr-xr-x 8 osmc osmc 4.0K May  9 14:52 ..
drwxr-xr-x 3 osmc osmc 4.0K May  9 14:52 widevine
drwxr-xr-x 3 osmc osmc 4.0K May  9 14:52 .
```

I did force a reinstall of widevine by moving that file, but that did not resolve the issue.

**Comment by Essam311** [comment]
@mhutzsch https://github.com/CastagnaIT/plugin.video.netflix/issues/1154#issuecomment-835842966

**Comment by mirh** [comment]
I would guess this is fixed now?

**Comment by BlackEdder** [comment]
> I would guess this is fixed now?

For me it has been solved.

**Comment by Sandmann79** [comment]
> > I would guess this is fixed now?
> 
> For me it has been solved.

So we should close this
