### ISSUE TITLE
error when automatically exporting the watchlist

### ISSUE THREAD

**Issue by broadcastyourseb** [Sandmann79/xbmc#559]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Rpi4
- OS version: OSMC 2020-11-26
- Kodi version number: 18.9

**Upload Logs**

log link : `https://paste.osmc.tv/nuludaxori`
[](https://paste.osmc.tv/nuludaxori)

**Describe the bug**

Enable automatically export the watchlist in the parameters. Restart the system. Error message at startup and no export of course.

2021-05-15 21:37:36.288 T:1508896992  NOTICE: [Amazon VOD] Service: Exporting the Watchlist
2021-05-15 21:37:36.312 T:1479880928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'amz'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 83, in EntryPoint
                                                g.amz.getListMenu(args.get('url', ''), int(args.get('export', '0')))
                                              File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/common.py", line 55, in __getattr__
                                                def __getattr__(self, name): return self._globals[name]
                                            KeyError: 'amz'
                                            -->End of Python script error report<--
2021-05-15 21:37:36.561 T:1479880928 WARNING: CPythonInvoker(13, /home/osmc/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon7xbmcgui6DialogE
2021-05-15 21:37:57.292 T:1500504288 WARNING: Attempt to use invalid handle 6

**Comment by Sandmann79** [comment]
The export features are not available for primevideo members. 
That's the reason. why this setting is inside the amazon.tld section.

**Comment by broadcastyourseb** [comment]
I think there is a misunderstanding about this feature. First, why am I able to turn on a feature not available for primevideo members or able to see amazon tld options ?
But it is not the meaning of my topic. I was looking for an export of my personal list (mystuff) like the netflix plugin does. It exports movie links in strm files inside well named folder with this kind of link : plugin://plugin.video.netflix/play_strm/movie/81127902/
In Kodi, I could add an extra source of video files which is great when you more than one video source.
By the way, great plugin you provide here. Thanks.
