### ISSUE TITLE
EXCEPTION when Amazon VOD tries to start 

### ISSUE THREAD

**Issue by ElPractical** [Sandmann79/xbmc#597]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.4

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3B
- OS version: LibreELEC-RPi2.arm-9.2.8
- Kodi version number: Kodi 18.9

**Upload Logs**

https://www.dropbox.com/s/o1aya75m7jvo2vs/kodi.log?dl=0

**Describe the bug**

After a click on the Amazon VOD button in the Addon-menu the load-symbol at the UI appears. After some seconds the UI switches to the VIDEO-folder. A message occours: "Amazon VOD Error". The Amazon VOD does not start.

**Comment by clement-analogue** [comment]
Exact same issue for me:

    Hardware: Pine64 RockPro64
    OS version: LibreELEC 10.0.0 and LibreELEC 10.0.1
    Kodi version number: Kodi 19.3

**Comment by Varstahl** [comment]
The provided log isn't really useful since it lacks context. Please enable debug logging (info on how to do it in the Wiki up here), and attach the full log to a comment reply.

**Comment by ElPractical** [comment]
Hi Varstahl, here is an updated Logfile:

[kodi.log](https://github.com/Sandmann79/xbmc/files/7553710/kodi.log)

**Comment by Varstahl** [comment]
Still not the full log and a bunch of information lacking. Instead of going to the addon straight try to open the settings, clear out any cookies (even if there are not) and try to log in from there.

**Comment by ElPractical** [comment]
Ok here a second try. I cleared the cookies and started debug logging. 
I opened the addon settings and pressed log in.

The Log contains everything from switching log level to debug until the error occurs

[kodi.log](https://github.com/Sandmann79/xbmc/files/7553985/kodi.log)

**Comment by thee233** [comment]
Same here.

```
NAME="LibreELEC"
VERSION="10.0.0"
ID="libreelec"
VERSION_ID="10.0"
PRETTY_NAME="LibreELEC (official): 10.0.0"
HOME_URL="https://libreelec.tv"
BUG_REPORT_URL="https://github.com/LibreELEC/LibreELEC.tv"
BUILD_ID="beaa0c7f252381459119feee42f2281d2e366215"
LIBREELEC_ARCH="RPi4.arm"
LIBREELEC_BUILD="official"
LIBREELEC_PROJECT="RPi"
LIBREELEC_DEVICE="RPi4"
```
`````


2021-11-28 17:49:46.975 T:1280  WARNING <general>: [Amazon VOD] Collision detected during JSON objects merging on key “pageType”, overwriting and praying (type: <class 'str'>)
2021-11-28 17:49:46.981 T:1280    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'name'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                       EntryPoint()
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 69, in EntryPoint
                                                       g.pv.BrowseRoot()
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 366, in BrowseRoot
                                                       if not self.BuildRoot():
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 378, in BuildRoot
                                                       self._UpdateProfiles(home)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 265, in _UpdateProfiles
                                                       'title': p['name'],
                                                   KeyError: 'name'
                                                   -->End of Python script error report<--
                                                   
2021-11-28 17:49:47.402 T:1280     INFO <general>: Python interpreter stopped
```
