### ISSUE TITLE
Error when trying to login

### ISSUE THREAD

**Issue by CodaCodalis** [Sandmann79/xbmc#598]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 
0.9.4+matrix.1

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 3
- OS version: Raspberry Pi OS (Debian Bullseye)
- Kodi version number: 19.3

**Upload Logs**

2021-11-27 11:20:24.713 T:1277     INFO <general>: [Amazon VOD] Login
2021-11-27 11:20:24.730 T:1277     INFO <general>: [Amazon VOD] Retrieve territoral config
2021-11-27 11:20:24.735 T:1277     INFO <general>: [Amazon VOD] getURL: https://na.api.amazonvideo.com/cdp/usage/v2/GetAppStartupConfig?deviceTypeID=[removed]&deviceID=[removed]&firmware=1&version=1&format=json
2021-11-27 11:20:24.933 T:662      INFO <general>: JSONRPC Server: New connection added
2021-11-27 11:20:25.147 T:1277    ERROR <general>: [Amazon VOD] Error reason: HTTPSConnectionPool(host='na.api.amazonvideo.com', port=443): Max retries exceeded with url: /cdp/usage/v2/GetAppStartupConfig?deviceTypeID=[removed]&deviceID=[removed]&firmware=1&version=1&format=json (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1123)'))) (SSLError)
2021-11-27 11:20:27.001 T:662      INFO <general>: JSONRPC Server: Disconnection detected
2021-11-27 11:20:39.959 T:662      INFO <general>: JSONRPC Server: New connection added
2021-11-27 11:20:44.279 T:662      INFO <general>: JSONRPC Server: Disconnection detected
2021-11-27 11:20:44.746 T:658     ERROR <general>: OpenConnection - could not opening a connection to the CEC adapter
2021-11-27 11:20:51.535 T:662      INFO <general>: JSONRPC Server: New connection added
2021-11-27 11:20:54.587 T:1277     INFO <general>: [Amazon VOD] Connect to SignIn Page 5 attempts left
2021-11-27 11:20:54.605 T:1277    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.MissingSchema'>
                                                   Error Contents: Invalid URL '/gp/aw/si.html': No schema supplied. Perhaps you meant http:///gp/aw/si.html?
                                                   Traceback (most recent call last):
                                                     File "/home/pi/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                       EntryPoint()
                                                     File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 102, in EntryPoint
                                                       exec('{}()'.format(mode))
                                                     File "<string>", line 1, in <module>
                                                     File "/home/pi/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 583, in LogIn
                                                       br.open(user['baseurl'] + ('/gp/aw/si.html' if not user['pv'] else '/auth-redirect/'))
                                                     File "/home/pi/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/stateful_browser.py", line 146, in open
                                                       resp = self.get(url, *args, **kwargs)
                                                     File "/home/pi/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/browser.py", line 124, in get
                                                       response = self.session.get(*args, **kwargs)
                                                     File "/home/pi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 555, in get
                                                       return self.request('GET', url, **kwargs)
                                                     File "/home/pi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 528, in request
                                                       prep = self.prepare_request(req)
                                                     File "/home/pi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 456, in prepare_request
                                                       p.prepare(
                                                     File "/home/pi/.kodi/addons/script.module.requests/lib/requests/models.py", line 316, in prepare
                                                       self.prepare_url(url, params)
                                                     File "/home/pi/.kodi/addons/script.module.requests/lib/requests/models.py", line 390, in prepare_url
                                                       raise MissingSchema(error)
                                                   requests.exceptions.MissingSchema: Invalid URL '/gp/aw/si.html': No schema supplied. Perhaps you meant http:///gp/aw/si.html?
                                                   -->End of Python script error report<--
                                                   
2021-11-27 11:20:54.829 T:1277     INFO <general>: Python interpreter stopped

**Describe the bug**

When I try to login with my credentials I just get an error message (translated from German) "Amazon VOD Error - for more information check log"

EDIT:
I forgot to mention that the same procedure worked fine with a Raspberry Pi 4 four weeks ago:
- flashed Raspberry Pi OS Lite image (this time the image from October 30th 2021)
- installed Kodi from official repository
- used Sandmann 79 repository to install Amazon VOD

**Comment by CodaCodalis** [comment]
I forgot to mention that the same procedure worked fine with a Raspberry Pi 4 two weeks ago:
- flashed Raspberry Pi OS Lite image from October 30th 2021
- installed Kodi from official repository 
- used Sandmann 79 repository to install Amazon VOD

**Comment by CodaCodalis** [comment]
I tried to change the region under settings > connection from Auto to Germany and it worked

**Comment by PeterPablo** [comment]
Pull request #590 sounds closely related. The mentioned OS release from end of october is the first one to be based on debian bullseye (from stretch). I had not tried to change the region -- possibly that setting causes that a slightly different code path is used.
