### ISSUE TITLE
Primevideo - Switching profile fails with 404

### ISSUE THREAD

**Issue by 23doors** [Sandmann79/xbmc#630]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: shield
- OS version: android tv
- Kodi version number: 19

**Upload Logs**

```
2022-06-23 13:50:18.268 T:74858750    INFO <general>: [Amazon VOD] startup.py:40 Requested /pv/profiles/list
2022-06-23 13:50:18.270 T:74858750    INFO <general>: [Amazon VOD] network.py:144 getURL: https://www.primevideo.com/gp/video/profiles
2022-06-23 13:50:18.463 T:74858750    INFO <general>: [Amazon VOD] network.py:228 Download Time: 0.19217842999995582
2022-06-23 13:50:18.474 T:74858750    INFO <general>: CPythonInvoker(17, /Users/V/Library/Application Support/Kodi/addons/plugin.video.amazon-test/default.py): script successfully run
2022-06-23 13:50:20.106 T:74858750    INFO <general>: initializing python engine.
2022-06-23 13:50:20.107 T:74858750    INFO <general>: [Amazon VOD] startup.py:40 Requested /pv/profiles/switch/amzn1.actor.person.oid.ADSHV26CZWEF5
2022-06-23 13:50:20.108 T:74858750    INFO <general>: [Amazon VOD] primevideo.py:308 https://www.primevideo.com/profiles/switch/ref=atv_pr_ww_swtch {'pid': 'amzn1.actor.person.oid.ADSHV26CZWEF5', 'csrfToken': 'gzjjCGHkEMKx6ehrAUdsK1SJLtQsFWIZBxcPdH8EyBXXAAAAAQAAAABitFN3cmF3AAAAAPgWC9WfHH8iB+olH/E9xQ==', 'rurl': '/storefront/kids/ref=atv_pr_ww_swtch'}
2022-06-23 13:50:20.109 T:74858750    INFO <general>: [Amazon VOD] network.py:144 postURL: https://www.primevideo.com/profiles/switch/ref=atv_pr_ww_swtch
2022-06-23 13:50:21.149 T:74858750   ERROR <general>: [Amazon VOD] network.py:198 Error reason: 404 error (NoRetries)
2022-06-23 13:50:21.150 T:74858750   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: argument of type 'NoneType' is not iterable
                                                   Traceback (most recent call last):
                                                     File "/Users/V/Library/Application Support/Kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                       EntryPoint()
                                                     File "/Users/V/Library/Application Support/Kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 63, in EntryPoint
                                                       g.pv.Route(verb, path)
                                                     File "/Users/V/Library/Application Support/Kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 283, in Route
                                                       elif 'profiles' == verb: g.pv.Profile(path)
                                                     File "/Users/V/Library/Application Support/Kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 321, in Profile
                                                       elif 'switch' == path[0]: Switch()
                                                     File "/Users/V/Library/Application Support/Kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 310, in Switch
                                                       self._UpdateProfiles(home)
                                                     File "/Users/V/Library/Application Support/Kodi/addons/plugin.video.amazon-test/resources/lib/primevideo.py", line 261, in _UpdateProfiles
                                                       if 'cerberus' in data:
                                                   TypeError: argument of type 'NoneType' is not iterable
                                                   -->End of Python script error report<--
```

**Describe the bug**

Switching profiles return 404 for some reason and fails to actually switch.

**Comment by 23doors** [comment]
Did some debugging. And for whatever reason - user-agent seems to be an issue. 
geturl used this UA for me: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
tried one from browser (where profile switching works): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
and still 404.

But, when I use no user-agent (or empty user-agent), then it works. Which is weird and feels more like a workaround (as normal UA works when in browser). Anyway, maybe you'll find it helpful.
```
        data = getURL(FQify(profile['switchLink']['partialURL']),
                      headers={'User-Agent': ''},
                      postdata=postdata, useCookie=True, rjson=False, check=True)
```

**Comment by Varstahl** [comment]
Thanks, it might be useful. I'll try to test this later today, it's also affecting desktops and probably other users.

**Comment by Varstahl** [comment]
This issue just got a lot more complicated. Apparently in trying stuff I can't login anymore. *wildly confused*. Have I been away too long? :°D

**Comment by 23doors** [comment]
That's weird. I even tried re-logging today to make sure it's not just some outdated cookie causing it and it worked fine (with 2FA enabled).

**Comment by Varstahl** [comment]
Yeah, it was a regression of the WebApi branch, just fixed it. Amazon keeps receiving API calls, returning JSON for half of them and raw HTML for others. Figures.

**Comment by Varstahl** [comment]
Speaking of which, we're using two different versions of the software, but the problem still stands. I would bet the problem lies within the new Cloudflare setup they seem to be using. I could be wrong of course. One thing's for certain, need to delay the troubleshooting to tomorrow.

**Comment by Varstahl** [comment]
I found the problem, but I think it's a bug in the requests python module… not quite sure how to proceed. The standard request `POST`s on `/profiles/switch`, that since an Amazon updates redirects to `eu.primevideo.com/ap/k/pickactor`, but for some reason the location host is discarded, and the request is sent to `www.primevideo.com/ap/k/pickactor`, which correctly returns the 404. Might need to drop the automatic redirect and need to handle it manually, which is a huge pain.

**Comment by 23doors** [comment]
how about not setting host header explicitly then?
as this seems to be causing this behavior according to: https://github.com/psf/requests/issues/3941

**Comment by 23doors** [comment]
Just tested and with the usual user-agent, skipping setting host in headers seems to be a proper fix. Host header is still properly set along all steps by requests library in this case as well.

**Comment by Varstahl** [comment]
… well, yeah, apparently Host overrides the URL, for some reason. Well thought. Need to check why we needed that in the first place, but that was the correct answer.
