### ISSUE TITLE
"Rings of Power" will not load. API issue?

### ISSUE THREAD

**Issue by lhassell** [Sandmann79/xbmc#647]
!-- ⚠️⚠️  DO NOT DELETE THIS  ⚠️⚠️ -->

**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.9.5+matrix.1

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Shield TV (2015)
- OS version: Current
- Kodi version number: 19.4

**Upload Logs**

**Describe the bug**

No error is returned, but when I select "Rings of Power," the list populates as empty. Can watch other recent shows (i.e. The Boys) with no issues, but it will not load the episode list for ROP.

**Comment by fabpolli** [comment]
Same behavior on rpi4 but with a right click on main title and  click on refresh menu element first two episodes appear correctly

**Comment by cpassuel** [comment]
I have an issue too when I try to view Rings of Power from my washlist: I soon as I select the Rings of Power folder, I have an error. It works ok when I search Rings of Power and I enter its folder.

Here is the error
```
2022-09-06 20:44:17.998 T:2783249216  NOTICE: [Amazon VOD] Service: Proxy bound to 127.0.0.1:54619
2022-09-06 20:44:18.025 T:2783249216  NOTICE: [Amazon VOD] Service: Proxy server started
2022-09-06 20:44:18.025 T:2783249216  NOTICE: [Amazon VOD] Service started
2022-09-06 20:44:18.775 T:2791641920   ERROR: ## LibreELEC Addon ## updates::get_rpi_flashing_state ## ERROR: (UnicodeDecodeError('ascii', '\xc3\xa0 jour: ', 0, 1, 'ordinal not in range(128)'))
2022-09-06 20:44:18.775 T:2791641920   ERROR: Traceback (most recent call last):
                                              File "/var/lib/jenkins/LE/build4/workspace/RPi4/LibreELEC.tv/build.LibreELEC-RPi4.arm-9.2.8/LibreELEC-settings-67f0b7ffbdee07283c751190bf6bda979ac28b9f/.install_pkg/usr/share/kodi/addons/service.libreelec.settings/resources/lib/modules/updates.py", line 639, in get_rpi_flashing_state
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
2022-09-06 20:46:53.433 T:2549605184  NOTICE: [Amazon VOD] Version: 0.9.5
2022-09-06 20:46:53.433 T:2549605184  NOTICE: [Amazon VOD] Unicode filename support: False
2022-09-06 20:46:53.434 T:2549605184  NOTICE: [Amazon VOD] Locale: en-us / Language: fr
2022-09-06 20:46:53.724 T:2549605184 WARNING: Attempt to use invalid handle 1
2022-09-06 20:47:21.274 T:2549605184 WARNING: Previous line repeats 3 times.
2022-09-06 20:47:21.274 T:2549605184   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'bool' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 62, in EntryPoint
                                                g.pv.Route(verb, path)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 279, in Route
                                                elif 'browse' == verb: g.pv.Browse(path)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 594, in Browse
                                                title = entry.get('title', nodeName)
                                            AttributeError: 'bool' object has no attribute 'get'
                                            -->End of Python script error report<--

```

When I llook at the related code in web_api.py, I suspect one of the branch of the if statement returns a wrong value for entry
```
        for key in nodeKeys:
            if key in self._videodata:
                entry = deepcopy(self._videodata[key])
            else:
                entry = node[key]
            title = entry.get('title', nodeName)
```

**Comment by xukashi** [comment]
same here

**Comment by cpassuel** [comment]
I did more tests to see what happens:
When I try to enter Rings of Power folder from my watchlist, the branch **entry = node[key]** is taken (else branch) and the key is "**trailer**" and node{"trailer"] returns a bool instead of a dict.

The value "**trailer**" for key seems weird, it should be more like "amzn1.dv.gti.78b28d61-397d-87df-03d4-9bcde012a156". I don't know if it's a bug in the plugin or incorrect data in Amazon Prime service.

I remember I had this issue too when I added the rings of power trailer in my watchlist

**Comment by jodett** [comment]
I guess it's the same problem with "Mrs Maisel Season 4", there are also all episodes missing.

**Comment by agolks** [comment]
when i try to curl the request url seen in log file, the title list in the result json is empty.
for "the boys" this list is filled.

**Comment by cpassuel** [comment]
My issue is fixed now, so it was probably an incorrect data in Prime Video.
Maybe your issue is not the same as mine, you have to check the log file for more details

**Comment by agolks** [comment]
well, watch list or search list folder is still empty at my side.

**Comment by loleq** [comment]
I was able to workaround by changing the Prime Video language to english. When language was set to polish, I got following error:

```
2022-09-12 09:36:23.038 T:1164    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/coll1_Strona+g%C5%82%C3%B3wna/Polecane/tile_2/amzn1.dv.gti.f856462e-f3f0-47d6-99a7-8e7900ffb935
2022-09-12 09:36:23.064 T:859     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/coll1_Strona+g%C5%82%C3%B3wna/Polecane/tile_2/amzn1.dv.gti.f856462e-f3f0-47d6-99a7-8e7900ffb935) failed
```

**Comment by agolks** [comment]
worked for me, too, little "simplier". just needed to activate the new web api access thingy.

**Comment by nickschurch** [comment]
I have the same problem using the standard amazonVOD interface  - no episodes being shown. enabling webAPI and trying again I just get a whirly circle with no progress. where do I find the logs?

**Comment by cpassuel** [comment]
> I have the same problem using the standard amazonVOD interface - no episodes being shown. enabling webAPI and trying again I just get a whirly circle with no progress. where do I find the logs?

It depends on the OS, on my RP4 it is in /storage/.kodi/temp/kodi.log

**Comment by lhassell** [comment]
Can confirm web API fixed the problem on 2015 Shield running Kodi 19.4

**Comment by lhassell** [comment]
I seem to have spoken too soon. Will no longer load ROP in the addon.

**Comment by Varstahl** [comment]
Closing as fixed.
