### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by thekswenson** [Sandmann79/xbmc#657]
I am using your addon in Kodi 19.4.
The addon loads but when I try to enter into some directories, or start watching a video a get an error message.  The log file says

```
Error Type: <class 'AttributeError'>
Error Contents: 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/kodi/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
    EntryPoint()
  File "/home/kodi/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 62, in EntryPoint
    g.pv.Route(verb, path)
  File "/home/kodi/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 279, in Route
    elif 'browse' == verb: g.pv.Browse(path)
  File "/home/kodi/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 594, in Browse
    title = entry.get('title', nodeName)
AttributeError: 'str' object has no attribute 'get'
```

**Comment by thekswenson** [comment]
Duplicate of #656 .

**Comment by thekswenson** [comment]
Duplicate of https://github.com/Sandmann79/xbmc/issues/656.
