### ISSUE TITLE
TypeError Exception when trying to change Profile

### ISSUE THREAD

**Issue by BrutuZ** [Sandmann79/xbmc#659]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PC
- OS version: Win 10
- Kodi version number: 18.9 Leia

**Upload Logs**

Excerpt:
```
2022-11-29 23:08:36.738 T:74724  NOTICE: [Amazon VOD] startup.py:65 Unicode filename support: True
2022-11-29 23:08:36.738 T:74724  NOTICE: [Amazon VOD] startup.py:66 Locale: en-gb / Language: en
2022-11-29 23:08:40.514 T:74724  NOTICE: [Amazon VOD] startup.py:39 Requested /pv/profiles/list
2022-11-29 23:08:40.516 T:74724  NOTICE: [Amazon VOD] network.py:162 getURL: https://www.primevideo.com/gp/video/profiles
2022-11-29 23:08:40.998 T:74724  NOTICE: [Amazon VOD] network.py:245 Download Time: 0.4816296
2022-11-29 23:08:41.004 T:74724   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: unhashable type: 'dict'
                                            Traceback (most recent call last):
                                              File "G:\Kodi\portable_data\addons\plugin.video.amazon-test\default.py", line 5, in <module>
                                                EntryPoint()
                                              File "G:\Kodi\portable_data\addons\plugin.video.amazon-test\resources\lib\startup.py", line 62, in EntryPoint
                                                g.pv.Route(verb, path)
                                              File "G:\Kodi\portable_data\addons\plugin.video.amazon-test\resources\lib\web_api.py", line 281, in Route
                                                elif 'profiles' == verb: g.pv.Profile(path)
                                              File "G:\Kodi\portable_data\addons\plugin.video.amazon-test\resources\lib\web_api.py", line 345, in Profile
                                                if 'list' == path[0]: List()
                                              File "G:\Kodi\portable_data\addons\plugin.video.amazon-test\resources\lib\web_api.py", line 319, in List
                                                home = GrabJSON(self._g.BaseUrl + '/gp/video/profiles')
                                              File "G:\Kodi\portable_data\addons\plugin.video.amazon-test\resources\lib\network.py", line 1004, in GrabJSON
                                                j = do(url, postData)
                                              File "G:\Kodi\portable_data\addons\plugin.video.amazon-test\resources\lib\network.py", line 1001, in do
                                                Merge(o, m)
                                              File "G:\Kodi\portable_data\addons\plugin.video.amazon-test\resources\lib\network.py", line 909, in Merge
                                                Merge(o[k], n[k], keys + [k])  # Recurse
                                              File "G:\Kodi\portable_data\addons\plugin.video.amazon-test\resources\lib\network.py", line 899, in Merge
                                                if item not in o:
                                            TypeError: unhashable type: 'dict'
                                            -->End of Python script error report<--
2022-11-29 23:08:41.079 T:74724 WARNING: CPythonInvoker(34, G:\Kodi\portable_data\addons\plugin.video.amazon-test\default.py): the python script "G:\Kodi\portable_data\addons\plugin.video.amazon-test\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcgui::Dialog,class PythonBindings::XBMCAddon_xbmc_Monitor_Director,class XBMCAddon::xbmcaddon::Addon
2022-11-29 23:08:41.089 T:74224   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/profiles/list
2022-11-29 23:08:41.091 T:73872   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/profiles/list) failed
```
[Full Log](https://gist.github.com/BrutuZ/577fe87b1e5948e884b4686787deb76c/raw/35aa97aadb80cb68c5555fcc464fa182fbc23278/kodi.log)

**Describe the bug**

I'm able to login, browse the catalog and play entries just fine, however only for the default profile, whenever I try to change the active profile I get the error above.

**Comment by BrutuZ** [comment]
Added a Log earlier in the loop to output the problematic values:
```diff
--- a/plugin.video.amazon-test/resources/lib/network.py
+++ b/plugin.video.amazon-test/resources/lib/network.py
@@ -897,4 +897,5 @@
        elif (type(n) in [list, set]):  # Insert into list/set
            for item in n:
+               Log('o: %s\nn: %s\nitem: %s' % (o, n, item))
                if item not in o:
                    if type(n) == list:
```

Output:
```
NOTICE: [Amazon VOD] o: {u'editProfile': u'/profiles/ref=atv_pr_ww_edt?step=editing', u'createProfileNav': u'/profiles/ref=atv_pr_cr_nv?step=associate', u'manageProfile': u'/profiles/ref=atv_pr_nv_mng?step=manage', u'createProfile': u'/profiles/ref=atv_pr_ww_add?step=associate', u'storefrontHome': u'/storefront/ref=atv_pr_ww_home', u'learnMore': u'/profilesLearnMore/ref=atv_pr_ww_lrn_mr', u'parentalControls': u'/settings/parental-controls/ref=atv_pr_ww_vr', u'preEditProfile': u'/profiles/ref=atv_pr_nv_mng?step=edit'}
                                            n: [{u'text': u'Terms and Privacy Notice', u'href': u'/ww-av-legal-home/ref=atv_ftr_ter'}, {u'text': u'Send us feedback', u'href': u'/contactus/ref=atv_ftr_cu'}, {u'text': u'Help', u'href': u'/help/ref=atv_ftr_hp'}]
                                            item: {u'text': u'Terms and Privacy Notice', u'href': u'/ww-av-legal-home/ref=atv_ftr_ter'}
```

**Comment by Varstahl** [comment]
Sorry for the delay, I've read your issue, I've just had troubles and have a backlog of urgent stuff to do before checking/addressing this. Thanks for the report, I'll get to it asap :)

**Comment by BrutuZ** [comment]
Ah don't worry about delay, the follow-up was just because I tried looking into it in the off-chance I could figure it out with minimum effort to open a PR instead 😅
Just pasted the "debug attempt" to give some more context on the data causing the issue.
