### ISSUE TITLE
Login issue with MFA/2FA : unknown error, please enable advanced debugging in settings and check avod-login.log...

### ISSUE THREAD

**Issue by chewiiie** [Sandmann79/xbmc#675]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: v0.9.6 & v0.9.7~alpha+matrix.1 (plugin.video.amazon-test-0.9.7~beta.zip)

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: PC (core i5, 8GB RAM)
- OS version: Win10 64bits 21H2
- Kodi version number: 19.5
(same issue on Pi3B with OSMC, Kodi 19.5, AmazonVOD v0.9.6)

**Upload Logs**

1st I was getting the error "Unable to find the navigation menu for primevideo.com" on both my Kodi devices.
After clearing the extension cache & login/cookie info, I try to login : it asks for my email address, password, then I get a 2FA prompt asking again for my email + password + a captcha, then I get a second captcha, and the error on the screenshot attached.
Issue is the same after upgrading to the last beta version posted on issue 674
https://github.com/Sandmann79/xbmc/issues/674

[avod-login-mfa.log](https://github.com/Sandmann79/xbmc/files/10907060/avod-login-mfa.log)
![screenshot MFA error](https://user-images.githubusercontent.com/37871226/223364242-bb48aa24-9d9f-4d29-8eca-0b15beb8649c.png)
[kodi.log](https://github.com/Sandmann79/xbmc/files/10907061/kodi.log)
[avod-login.log](https://github.com/Sandmann79/xbmc/files/10907062/avod-login.log)

**Comment by chewiiie** [comment]
> same issue
> 
> EDIT: I copied the addon_data folder from a different computer that was already logged in and it's working, so that's a temporary fix if you can do that.

Thanks! Unfortunately I cleared both caches...

**Comment by 27hectormanuel** [comment]
Same issue only solution is to disagree 2FA sign in and enable it again

**Comment by Sandmann79** [comment]
Can confirm the issue. The response from amazons server to the last captcha looks a little strange - no error or successful message, just the homepage.
I'll take a look at it....

**Comment by chewiiie** [comment]
Thank you very much

**Comment by cyr06** [comment]
I'm using beta5 on libreelec 11.0.1 rasp3
same unknown error at login. Unfortunately I don't know how to enable logs in libreelec to have the avod-login.log file. I have this on the kodi.log
```2023-04-02 15:48:06.304 T:2159     info <general>: [Amazon VOD] Login
2023-04-02 15:48:06.348 T:2159     info <general>: [Amazon VOD] Retrieve territoral config
2023-04-02 15:48:06.353 T:2159     info <general>: [Amazon VOD] getURL: https://atv-ps.amazon.com/cdp/usage/v2/GetAppStartupConfig?deviceTypeID=A22W&deviceID=dc343c9f209&firmware=1&version=1&format=json
2023-04-02 15:48:28.008 T:2159     info <general>: [Amazon VOD] Connect to SignIn Page 5 attempts left
2023-04-02 15:48:28.881 T:2159     info <general>: [Amazon VOD] Switching UserAgent
2023-04-02 15:48:28.884 T:2159     info <general>: [Amazon VOD] UA: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36 blacklisted
2023-04-02 15:48:28.885 T:2159     info <general>: [Amazon VOD] Loading list of common UserAgents
2023-04-02 15:48:28.886 T:2159     info <general>: [Amazon VOD] getURL: http://www.skydubh.com/pub/useragents.json
2023-04-02 15:48:29.037 T:2159     info <general>: [Amazon VOD] Using UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.2.14
2023-04-02 15:48:30.306 T:2159     info <general>: [Amazon VOD] Connect to SignIn Page 4 attempts left
2023-04-02 15:48:30.656 T:2159     info <general>: [Amazon VOD] Switching UserAgent
2023-04-02 15:48:30.661 T:2159     info <general>: [Amazon VOD] UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 Waterfox/56.2.14 blacklisted
2023-04-02 15:48:30.662 T:2159     info <general>: [Amazon VOD] Loading list of common UserAgents
2023-04-02 15:48:30.664 T:2159     info <general>: [Amazon VOD] getURL: http://www.skydubh.com/pub/useragents.json
2023-04-02 15:48:30.717 T:2159     info <general>: [Amazon VOD] Using UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
2023-04-02 15:48:32.077 T:2159     info <general>: [Amazon VOD] Connect to SignIn Page 3 attempts left
2023-04-02 15:48:42.267 T:2159     info <general>: [Amazon VOD] MFA, DCQ or Captcha form```

**Comment by Sandmann79** [comment]
@cyr06 your log snippet isn't from Beta5. Enable advanced logging at addon settings -> miscellaneous. There you can also create a log files archive.

**Comment by cyr06** [comment]
oups sorry :( :( :( I had a dependency error so I reinstalled the stable version instead of the beta one...
So I took an other fresh install of libreelec 11.0.1 and the issue with the dependency still happens :
`2023-04-02 19:27:56.089 T:744     error <general>: CAddonInstallJob[plugin.video.amazon-test]: The dependency on script.module.beautifulsoup4 version 4.6.3+matrix.1 could not be satisfied.`

**Comment by cyr06** [comment]
ok I installed manually :
```
script.module.beautifulsoup4-4.9.3+matrix.1.zip
script.module.mechanicalsoup-1.0.0+matrix.1.zip
script.module.pyautogui-0.9.51+matrix.1.zip
```
beta5 is now installed and I can get logged in but I can't access "my stuff" with this kind of log
```
2023-04-03 10:01:04.216 T:1744     info <general>: [Amazon VOD] Version: 0.9.7~beta5+matrix.1
2023-04-03 10:01:04.218 T:1744     info <general>: [Amazon VOD] Unicode filename support: False
2023-04-03 10:01:04.220 T:1744     info <general>: [Amazon VOD] Locale: en-us / Language: en
2023-04-03 10:01:04.247 T:1744  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-04-03 10:01:11.695 T:1744     info <general>: Skipped 33 duplicate messages..
2023-04-03 10:01:11.695 T:1744    error <general>: [Amazon VOD] Cookie invalid
2023-04-03 10:01:11.706 T:1744    error <general>: [Amazon VOD] Unable to fetch the url: /mystuff/ref=atv_hm_offers_c_9zZ8D2_1_5?episodeListSize=9999
2023-04-03 10:01:11.713 T:1744    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                       EntryPoint()
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 62, in EntryPoint
                                                       g.pv.Route(verb, path)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 282, in Route
                                                       elif 'browse' == verb: g.pv.Browse(path)
                                                                              ^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 612, in Browse
                                                       title = entry.get('title', nodeName)
                                                               ^^^^^^^^^
                                                   AttributeError: 'str' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2023-04-03 10:01:12.007 T:1750    error <general>: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/Watchlist
2023-04-03 10:01:12.013 T:680     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/Watchlist) failed
2023-04-03 10:01:13.834 T:1752     info <general>: [Amazon VOD] Version: 0.9.7~beta5+matrix.1
```

**Comment by Sandmann79** [comment]
This is bad. As I wrote above, it is possible that the cookie for primevideo.com is not valid. This is probably the case. 
There we have to go back to the previous login method for PV users for now to have a working login.

**Comment by joecandelas** [comment]
> This is bad. As I wrote above, it is possible that the cookie for primevideo.com is not valid. This is probably the case. There we have to go back to the previous login method for PV users for now to have a working login.

Hello, 
¿Which is the previous login method? I'm also having login issues. It asks me for my **_email + password + a captcha_** then I get an error. I'll try and attach and screenshot later.
Any help?
Thanks in advanced

**Comment by Sandmann79** [comment]
Here you can find the current Beta 6, which should fix these login issue:
https://github.com/Sandmann79/xbmc/issues/674#issuecomment-1505061662

**Comment by joecandelas** [comment]
> Here you can find the current Beta 6, which should fix these login issue: [#674 (comment)](https://github.com/Sandmann79/xbmc/issues/674#issuecomment-1505061662)

Yes, I already downloaded it. Thanks a lot.

**Comment by eggbeater98** [comment]
Hello,
I have installed beta6 and I get this in the kodi log when I attempt to log in:

`
2023-04-14 22:19:14.718 T:9437     INFO <general>: [Amazon VOD] getURL: https://atv-ps.amazon.com/cdp/usage/v3/GetAppStartupConfig?deviceTypeID=A28RQHJKHM2A2W&deviceID=8d7c5caf74074565bdcd6a2a3422bc48&firmware=1&version=1&format=json
2023-04-14 22:19:43.524 T:9437     INFO <general>: [Amazon VOD] Connect to SignIn Page
2023-04-14 22:19:43.925 T:9437    ERROR <general>: EXCEPTION Thrown
(PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'mechanicalsoup.utils.LinkNotFoundError'>
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                       EntryPoint()
                                                     File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 82, in EntryPoint
                                                       exec('{}()'.format(mode))
                                                     File "<string>", line 1, in <module>
                                                     File "/home/osmc/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 664, in LogIn
                                                       form = br.select_form('form[name="signIn"]')
                                                     File "/home/osmc/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/stateful_browser.py", line 220, in select_form
                                                       raise LinkNotFoundError()
                                                   mechanicalsoup.utils.LinkNotFoundError
                                                   -->End of Pythonscript error report<--

2023-04-14 22:19:44.261 T:9437     INFO <general>: Python interpreter stopped







`
I'm not sure what to do to log in.

**Comment by thomas-ernest** [comment]
Hello,

**System overview** I got the same issue yesterday on Windows 11 on AMD-powered laptop with Kodi 20.1 as well as LibreElec 11.0 on RPi4 with Kodi 20.0. I had the version 0.9.6 of the plugin while doing my tests, not the beta.

**Issue** The issue was that after entering the captcha I got an Amazon page without error, but I wasn't logged in. I could see the message to enable cookie in the amazon page. The captcha was just sequence of letters black and white without strike or graphical complexity.

**"Fix"** Once I enabled the advanced logging at addon settings in miscellaneous category, I got a different a dialog box and a different type of captcha, which enabled me to login. The captcha contained "fingerprint effect" and a kind of mirroring effect too. I had a sequence of 2 captcha on my 2 devices.

**No logs** Sorry I cannot provide logs, because they disappeared (I guess dure to restarts) since yesterday.

Thanks for the plugin,
Best regards,

**Comment by Sandmann79** [comment]
@eggbeater98 please test Beta7 from [here](https://github.com/Sandmann79/xbmc/issues/674#issuecomment-1518524373) and report back. Support for some captcha dialogs has been added there, which could fix your issue. 

@thomas-ernest if it is no longer reproducible, it may have just been a coincidence. The advanced logging option only creates additional log files and generates more log entries in the kodi.log.

**Comment by eggbeater98** [comment]
Hi @Sandmann79, I forgot to report back to say that I was able to log in after I tried again a couple of days later. I entered my credentials and a basic captcha, and then I got a sign-in confirmation on the Amazon app on my phone. I confirmed the notification on the app and the add-on finished logging in.
