### ISSUE TITLE
Connection Error/Amazon VOD error

### ISSUE THREAD

**Issue by Forlorn-Hope** [Sandmann79/xbmc#686]
**Addon used**
- [X ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: plugin.video.amazon-test-0.9.7.beta7+matrix

**Account type**
- [X ] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Intel NUC Core i5-8259U
- OS version: LibreElec 11.0.1
- Kodi version number:  20.1.0

**Upload Logs**

**Describe the bug**

I disabled the plugin before installing the new version.  After installing plugin.video.amazon-test-0.9.7.beta7+matrix.1.zip, I cleared the cache, and rebooted.  Once back up, I went into the Amazon plugin.  Selected, My Stuff, Watchlist, and received 2 errors.  The first stated that there was a Connection error /gp/video/mystuff/watchlist/ref=atv_hm_hom_c_9zZ. Then the second error states that there was an Amazon VOD error, Check the log for more information.  In looking at the Amazon Prime browser page, it appears that they have made some 'improvements', which may have broken the plug-in.  I have uploaded both the kodi.log, and the archive made by the plug-in.

Hope this helps to track down the issue.

[logfiles_20230429-224845.zip](https://github.com/Sandmann79/xbmc/files/11360567/logfiles_20230429-224845.zip)
[kodi.log](https://github.com/Sandmann79/xbmc/files/11360568/kodi.log)

**Comment by Sandmann79** [comment]
In the last few days the addon has been updated to 0.9.7 stable. Please update and delete both caches afterwards, then the errors in the watchlist should be fixed.
The bypass certificate validation setting should not be activated lightly, as it represents an increased security risk and is only intended for developer purposes.

**Comment by Forlorn-Hope** [comment]
Thank you for the response. I updated the plugin from the repository, cleared the cache, and rebooted.  I opened the plugin, went to My Stuff, Watchlist, TV Shows.  It grinds for a few seconds then returns the error same error above.  If I select Movies, it will appear to be filling the cache, say that the server did not return any content, but then will show a listing of items in my list.  Selecting All, returns a mix of the connection error, and that the servers returned no content.

I have attached the log below.
[logfiles_20230430-114431.zip](https://github.com/Sandmann79/xbmc/files/11361667/logfiles_20230430-114431.zip)

**Comment by Gemini88** [comment]
@Sandmann79 its constantly saying connection error (0.9.8) im starting to think something changed on Amazon's end again like usual amazon is always changing something on there servers

**Comment by VII86** [comment]
I am getting a similar error on my libreELEC Kodi
Hardware: raspberry Pi 4
OS: LibreELEC 11.0
Addon Version: 0.9.8+matrix.1

I try to list the contents of the Series "Good Omens Season 2", which returns the following error:

2023-08-10 21:11:13.348 T:1360  warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-08-10 21:11:14.677 T:1360     info <general>: Skipped 1 duplicate messages..
2023-08-10 21:11:14.677 T:1360    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'bool' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                       EntryPoint()
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 62, in EntryPoint
                                                       g.pv.Route(verb, path)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 284, in Route
                                                       elif 'browse' == verb: g.pv.Browse(path)
                                                                              ^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 608, in Browse
                                                       title = entry.get('title', nodeName)
                                                               ^^^^^^^^^
                                                   AttributeError: 'bool' object has no attribute 'get'
                                                   -->End of Python script error report<--

2023-08-10 21:11:14.877 T:1363    error <general>: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/search/amzn1.dv.gti.e2b25234-da5b-06af-ec69-aab86244c614/B0BYZ93YRT
2023-08-10 21:11:14.880 T:996     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/search/amzn1.dv.gti.e2b25234-da5b-06af-ec69-aab86244c614/B0BYZ93YRT) failed

Strangely the first Season of this show is not affected. I'm not sure if other series are affected as well but this is the one I encountered the error now.

**Comment by Sandmann79** [comment]
This issue has been fixed with the current betas. 
You can download it here: #700
