### ISSUE TITLE
Videoplayback starts, but the video has no picture

### ISSUE THREAD

**Issue by ChrizH84** [Sandmann79/xbmc#687]
**Addon used**
- [X ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [X ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: AMD Ryzen5600G with integrated GPU
- OS version: LibreElec 11.0.1
- Kodi version number: 20.1

**Upload Logs**

When I try to start watching a movie, it starts to play (it plays the sound). But the video itself doesn't plays. Instead, I see the movielist where I've started to play and the progress on the bottom right corner flickers.
Other Streamingservices seems to work, also live-tv.
I'm using the current LibreElec version with mainly standard settings (especially for technical things).
I could imagine that the problem is related to the AMD system, but I'm not sure if it works on Intel.

Any ideas?

**Comment by Gemini88** [comment]
@ChrizH84 yh same here and its only happening with drm protected/subscription required addons i.e. Amazon, Netflix etc. Regular real-debrid supported Add-ons no problems with playback. Im guessing a widevine error which points me to "inputstream adaptive" as the culprit but time and testing will tell

**Comment by BBJake** [comment]
I have the same problem.
It only shows "Prime video" on the background and plays the audio. But no video.
In the logs i find the following;:

```
2023-07-24 21:55:34.096 T:584      info <general>: [Amazon VOD] Service: Proxy bound to 127.0.0.1:58123
2023-07-24 21:55:34.099 T:584      info <general>: [Amazon VOD] Service: Proxy server started
2023-07-24 21:55:34.118 T:584      info <general>: [Amazon VOD] Service started
2023-07-24 21:55:35.800 T:452      info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2023-07-24 21:55:39.175 T:590      info <general>: JSONRPC Server: New connection added
2023-07-24 21:55:42.182 T:452   warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2023-07-24 21:55:42.811 T:668      info <general>: Skipped 4 duplicate messages..
2023-07-24 21:55:42.811 T:668      info <general>: [Amazon VOD] Version: 0.9.8+matrix.1
2023-07-24 21:55:42.821 T:668      info <general>: [Amazon VOD] Unicode filename support: False
2023-07-24 21:55:42.823 T:668      info <general>: [Amazon VOD] Locale: en-us / Language: de
2023-07-24 21:55:42.913 T:668   warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-07-24 21:55:45.798 T:452   warning <general>: Skipped 6 duplicate messages..
2023-07-24 21:55:45.798 T:452   warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2023-07-24 21:55:46.349 T:683      info <general>: Skipped 4 duplicate messages..
2023-07-24 21:55:46.349 T:683      info <general>: [Amazon VOD] Version: 0.9.8+matrix.1
2023-07-24 21:55:46.372 T:683      info <general>: [Amazon VOD] Unicode filename support: False
2023-07-24 21:55:46.376 T:683      info <general>: [Amazon VOD] Locale: en-us / Language: de
2023-07-24 21:55:46.480 T:683   warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-07-24 21:55:49.363 T:452   warning <general>: Skipped 6 duplicate messages..
2023-07-24 21:55:49.363 T:452   warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2023-07-24 21:55:49.522 T:700      info <general>: Skipped 5 duplicate messages..
2023-07-24 21:55:49.522 T:700      info <general>: [Amazon VOD] Version: 0.9.8+matrix.1
2023-07-24 21:55:49.522 T:700      info <general>: [Amazon VOD] Unicode filename support: False
2023-07-24 21:55:49.524 T:700      info <general>: [Amazon VOD] Locale: en-us / Language: de
2023-07-24 21:55:49.530 T:700   warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-07-24 21:55:54.596 T:452   warning <general>: Skipped 6 duplicate messages..
2023-07-24 21:55:54.596 T:452   warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2023-07-24 21:55:54.713 T:700   warning <general>: Skipped 5 duplicate messages..
2023-07-24 21:55:54.713 T:700   warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2023-07-24 21:56:06.064 T:700   warning <general>: Skipped 20 duplicate messages..
2023-07-24 21:56:06.064 T:700   warning <general>: [script.module.inputstreamhelper] Widevine update check was made on 2023-07-24 21:35
2023-07-24 21:56:06.081 T:700      info <general>: [Amazon VOD] postURL: http://127.0.0.1:58123/gpr/https%3A%2F%2Fatv-ps-eu.amazon.de%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3DB0B76P3HRY%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3Da4941eb2b9c14534be9ac51dff1047b4%26marketplaceID%3DA1PA6795UKMFR9%26format%3Djson%26version%3D2%26gascEnabled%3Dfalse%26subtitleFormat%3DTTMLv2%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%2CTransitionTimecodes%26supportedDRMKeyScheme%3DDUAL_KEY
2023-07-24 21:56:08.372 T:700      info <general>: [Amazon VOD] Using Host: Cloudfront
2023-07-24 21:56:08.373 T:700      info <general>: [Amazon VOD] checkURL: https://pop-dub-ww.cf.dash.row.aiv-cdn.net/dm/2$V1FSL0aMex9a95kMPEQ9xtqpf94~/5e61/3091/fedc/4eeb-bc9c-62d67c17ed58/2e21a97d-46e1-4889-8ff4-145fda353818_corrected.mpd
2023-07-24 21:56:08.497 T:700      info <general>: [Amazon VOD] Using inputstream.adaptive Version: 20.3.9
2023-07-24 21:56:08.624 T:452      info <general>: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B0B76P3HRY&mode=PlayVideo&name=Das+Auge&adult=0&trailer=0&selbitrate=0
2023-07-24 21:56:08.632 T:742      info <general>: Creating InputStream
2023-07-24 21:56:08.726 T:742   warning <general>: AddOnLog: inputstream.adaptive: Set headers to the manifest by using "inputstream.adaptive.stream_headers" property is a deprecated behaviour that will be removed in future.
                                                   To set headers to the manifest, use "inputstream.adaptive.manifest_headers" property.
2023-07-24 21:56:08.729 T:742      info <general>: AddOnLog: inputstream.adaptive: [Repr. chooser] Resolution set: 1920x1080, max allowed: 1920x1080, Adjust refresh rate: 1
2023-07-24 21:56:54.807 T:742      info <general>: AddOnLog: inputstream.adaptive: Successfully parsed manifest file (Periods: 1, Streams in first period: 257, Type: VOD)
2023-07-24 21:56:59.839 T:742      info <general>: Creating Demuxer
2023-07-24 21:56:59.859 T:742      info <general>: Opening stream: 1002 source: 256
2023-07-24 21:56:59.927 T:742      info <general>: Finding audio codec for: 86056
2023-07-24 21:56:59.928 T:742      info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder eac3
2023-07-24 21:56:59.928 T:742      info <general>: OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2023-07-24 21:56:59.928 T:742      info <general>: Creating audio thread
2023-07-24 21:56:59.929 T:776      info <general>: running thread: CVideoPlayerAudio::Process()
2023-07-24 21:56:59.930 T:742      info <general>: Opening stream: 0 source: 1025
2023-07-24 21:57:00.056 T:742      info <general>: CDVDSubtitlesLibass: Using libass version 1500000
2023-07-24 21:57:00.056 T:742      info <general>: CDVDSubtitlesLibass: Creating ASS library structure
2023-07-24 21:57:00.056 T:742      info <general>: CDVDSubtitlesLibass: Initializing ASS Renderer
2023-07-24 21:57:00.058 T:742      info <general>: CDVDSubtitlesLibass: Initializing ASS library font settings
2023-07-24 21:57:00.183 T:742      info <general>: CDVDSubtitlesLibass: Creating new ASS track
2023-07-24 21:57:00.271 T:776      info <general>: Creating audio stream (codec id: 86056, channels: 6, sample rate: 48000, no pass-through)
2023-07-24 21:57:00.290 T:567      info <general>: CActiveAESink::OpenSink - initialize sink
2023-07-24 21:57:00.354 T:700      info <general>: [Amazon VOD] Starting Playback: 0.0/4333.0
2023-07-24 21:57:00.490 T:567      info <general>: CAESinkALSA::Initialize - Attempting to open device "default"
2023-07-24 21:57:00.501 T:567      info <general>: CAESinkALSA::Initialize - Opened device "default"
2023-07-24 21:57:00.502 T:567      info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-07-24 21:57:00.502 T:567      info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2023-07-24 21:57:00.516 T:742   warning <general>: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
2023-07-24 21:57:00.840 T:452      info <general>: Loading skin file: MusicVisualisation.xml, load type: KEEP_IN_MEMORY
2023-07-24 21:57:01.803 T:738     error <general>: ----------------------------------------
2023-07-24 21:57:01.803 T:738     error <general>: 
                                                   
2023-07-24 21:57:01.803 T:738     error <general>: Exception occurred during processing of request from
2023-07-24 21:57:01.803 T:738     error <general>:  
2023-07-24 21:57:01.803 T:738     error <general>: ('127.0.0.1', 51594)
2023-07-24 21:57:01.803 T:738     error <general>: 
                                                   
2023-07-24 21:57:01.806 T:738     error <general>: Traceback (most recent call last):
                                                   
2023-07-24 21:57:01.806 T:738     error <general>: 
2023-07-24 21:57:01.806 T:738     error <general>:   File "/usr/lib/python3.9/socketserver.py", line 650, in process_request_thread
                                                       self.finish_request(request, client_address)
                                                   
2023-07-24 21:57:01.806 T:738     error <general>: 
2023-07-24 21:57:01.806 T:738     error <general>:   File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
                                                       self.RequestHandlerClass(request, client_address, self)
                                                   
2023-07-24 21:57:01.806 T:738     error <general>: 
2023-07-24 21:57:01.806 T:738     error <general>:   File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
                                                       self.handle()
                                                   
2023-07-24 21:57:01.806 T:738     error <general>: 
2023-07-24 21:57:01.806 T:738     error <general>:   File "/usr/lib/python3.9/http/server.py", line 429, in handle
                                                       self.handle_one_request()
                                                   
2023-07-24 21:57:01.806 T:738     error <general>: 
2023-07-24 21:57:01.806 T:738     error <general>:   File "/usr/lib/python3.9/http/server.py", line 395, in handle_one_request
                                                       self.raw_requestline = self.rfile.readline(65537)
                                                   
2023-07-24 21:57:01.806 T:738     error <general>: 
2023-07-24 21:57:01.806 T:738     error <general>:   File "/usr/lib/python3.9/socket.py", line 704, in readinto
                                                       return self._sock.recv_into(b)
                                                   
2023-07-24 21:57:01.806 T:738     error <general>: 
2023-07-24 21:57:01.806 T:738     error <general>: socket.timeout: timed out
                                                   
2023-07-24 21:57:01.806 T:738     error <general>: 
2023-07-24 21:57:01.807 T:738     error <general>: ----------------------------------------
2023-07-24 21:57:01.807 T:738     error <general>: 
             
```

**Comment by BBJake** [comment]
For me this works again with 0.9.9 Beta 4

**Comment by Sandmann79** [comment]
Has this issue been fixed for all?

**Comment by Sandmann79** [comment]
No recent activity here, closing this issue
