### ISSUE TITLE
video.amazon-test stuck on loding circle on startup / No JSON objects found in the page

### ISSUE THREAD

**Issue by stei-f** [Sandmann79/xbmc#696]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: x86_64
- OS version: Ubuntu 20.04.6 LTS
- Kodi version number:  20.1 (20.1.0) Git:20230312-289ec664e3, (6:20.1+git20230312.0705-289ec664e3-0~focal)

**Upload Logs**
Debug-Log:
```
2023-06-30 18:40:31.467 T:1590    debug <general>: ------ Window Deinit (Home.xml) ------
2023-06-30 18:40:31.467 T:1590    debug <general>: FreeVisualisation() done
2023-06-30 18:40:31.488 T:1590    debug <general>: ------ Window Init (MyVideoNav.xml) ------
2023-06-30 18:40:31.488 T:1590     info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2023-06-30 18:40:31.545 T:1590    debug <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.amazon-test/)
2023-06-30 18:40:31.545 T:1590    debug <general>:   ParentPath = [plugin://plugin.video.amazon-test/]
2023-06-30 18:40:31.545 T:2138    debug <general>: Thread waiting start, auto delete: false
2023-06-30 18:40:31.547 T:2137    debug <general>: CAddonDatabase::SetLastUsed[plugin.video.amazon-test] took 2 ms
2023-06-30 18:40:31.547 T:2138    debug <general>: CScriptRunner: running add-on script Amazon VOD('plugin://plugin.video.amazon-test/', '1', '')
2023-06-30 18:40:31.548 T:2139    debug <general>: Thread LanguageInvoker start, auto delete: false
2023-06-30 18:40:31.548 T:2139    debug <general>: initializing python engine.
2023-06-30 18:40:31.548 T:2139    debug <general>: CPythonInvoker(8, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): start processing
2023-06-30 18:40:31.585 T:2139    debug <general>: -->Python Interpreter Initialized<--
2023-06-30 18:40:31.585 T:2139    debug <general>:

2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): the source file to load is "/home/kodi/.kodi/addons/plugin.video.amazon-test/default.py"
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8): default python path:
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):   /usr/lib/python38.zip
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):   /usr/lib/python3.8
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):   /usr/lib/python3.8/lib-dynload
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):   /usr/local/lib/python3.8/dist-packages
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):   /usr/lib/python3/dist-packages
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8): adding path:
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/plugin.video.amazon-test
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.beautifulsoup4/lib
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.certifi/lib
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.chardet/lib
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.idna/lib
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.inputstreamhelper/lib
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.kodi-six/libs
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.mechanicalsoup/lib
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.pyautogui/lib
2023-06-30 18:40:31.585 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.pyxbmct/lib
2023-06-30 18:40:31.586 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.requests/lib
2023-06-30 18:40:31.586 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.six/lib
2023-06-30 18:40:31.586 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.soupsieve/lib
2023-06-30 18:40:31.586 T:2139    debug <general>: CPythonInvoker(8):  /home/kodi/.kodi/addons/script.module.urllib3/lib
2023-06-30 18:40:31.586 T:2139    debug <general>: CPythonInvoker(8): adding args:
2023-06-30 18:40:31.586 T:2139    debug <general>: CPythonInvoker(8):  plugin://plugin.video.amazon-test/
2023-06-30 18:40:31.586 T:2139    debug <general>: CPythonInvoker(8):  1
2023-06-30 18:40:31.586 T:2139    debug <general>: CPythonInvoker(8):
2023-06-30 18:40:31.586 T:2139    debug <general>: CPythonInvoker(8):  resume:false
2023-06-30 18:40:31.586 T:2139    debug <general>: CPythonInvoker(8, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): entering source directory /home/kodi/.kodi/addons/plugin.video.amazon-test
2023-06-30 18:40:31.586 T:2139    debug <general>: CPythonInvoker(8, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): instantiating addon using automatically obtained id of "plugin.video.amazon-test" dependent on version 3.0.0 of the xbmc.python api
2023-06-30 18:40:31.646 T:1590    debug <general>: ------ Window Init (DialogBusy.xml) ------
2023-06-30 18:40:32.354 T:2139    debug <CAddonSettings[0@plugin.video.amazon-test]>: trying to load setting definitions from old format...
2023-06-30 18:40:32.357 T:2139    debug <CSettingsManager>: requested setting (at_check) was not found.
2023-06-30 18:40:32.357 T:2139    debug <CSettingsManager>: requested setting (at_lang) was not found.
2023-06-30 18:40:32.357 T:2139    debug <CSettingsManager>: requested setting (country) was not found.
2023-06-30 18:40:32.357 T:2139    debug <CSettingsManager>: requested setting (drm_check) was not found.
2023-06-30 18:40:32.357 T:2139    debug <CSettingsManager>: requested setting (fallback_method) was not found.
2023-06-30 18:40:32.357 T:2139    debug <CSettingsManager>: requested setting (primevideo_area) was not found.
2023-06-30 18:40:32.357 T:2139    debug <CSettingsManager>: requested setting (save_login) was not found.
2023-06-30 18:40:32.358 T:2139    debug <CSettingsManager>: requested setting (set_login) was not found.
2023-06-30 18:40:32.358 T:2139    debug <CSettingsManager>: requested setting (sub_lang) was not found.
2023-06-30 18:40:32.358 T:2139    debug <CSettingsManager>: requested setting (subtitles) was not found.
2023-06-30 18:40:32.358 T:2139    debug <CSettingsManager>: requested setting (uhd_android) was not found.
2023-06-30 18:40:32.358 T:2139    debug <CSettingsManager>: requested setting (use_mfa) was not found.
2023-06-30 18:40:32.358 T:2139    debug <CSettingsManager>: requested setting (use_webapi) was not found.
2023-06-30 18:40:32.395 T:2139    debug <general>: [Amazon VOD] Requested {}
2023-06-30 18:40:32.399 T:1590    debug <general>: CGUIMediaWindow::GetDirectory (plugin://plugin.video.amazon-test/)
2023-06-30 18:40:32.399 T:1590    debug <general>:   ParentPath = [plugin://plugin.video.amazon-test/]
2023-06-30 18:40:32.400 T:1590  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2023-06-30 18:40:32.403 T:2137    debug <general>: Skipped 4 duplicate messages..
2023-06-30 18:40:32.403 T:2137    debug <general>: CAddonDatabase::SetLastUsed[plugin.video.amazon-test] took 3 ms
2023-06-30 18:40:32.403 T:2130    debug <general>: CScriptRunner: running add-on script Amazon VOD('plugin://plugin.video.amazon-test/', '2', '')
2023-06-30 18:40:32.403 T:2140    debug <general>: Thread LanguageInvoker start, auto delete: false
2023-06-30 18:40:32.403 T:2140    debug <general>: initializing python engine.
2023-06-30 18:40:32.403 T:2140    debug <general>: CPythonInvoker(9, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): start processing
2023-06-30 18:40:32.429 T:2139     info <general>: [Amazon VOD] Version: 0.9.9~beta
2023-06-30 18:40:32.429 T:2139     info <general>: [Amazon VOD] Unicode filename support: False
2023-06-30 18:40:32.429 T:2139     info <general>: [Amazon VOD] Locale: de-de / Language: de
2023-06-30 18:40:32.465 T:1590  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2023-06-30 18:40:32.481 T:2140    debug <general>: -->Python Interpreter Initialized<--
2023-06-30 18:40:32.481 T:2140    debug <general>:

2023-06-30 18:40:32.481 T:2140    debug <general>: CPythonInvoker(9, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): the source file to load is "/home/kodi/.kodi/addons/plugin.video.amazon-test/default.py"
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9): default python path:
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):   /usr/lib/python38.zip
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):   /usr/lib/python3.8
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):   /usr/lib/python3.8/lib-dynload
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):   /usr/local/lib/python3.8/dist-packages
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):   /usr/lib/python3/dist-packages
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9): adding path:
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/plugin.video.amazon-test
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.beautifulsoup4/lib
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.certifi/lib
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.chardet/lib
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.idna/lib
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.inputstreamhelper/lib
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.kodi-six/libs
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.mechanicalsoup/lib
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.pyautogui/lib
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.pyxbmct/lib
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.requests/lib
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.six/lib
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.soupsieve/lib
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  /home/kodi/.kodi/addons/script.module.urllib3/lib
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9): adding args:
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  plugin://plugin.video.amazon-test/
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  2
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9):  resume:false
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): entering source directory /home/kodi/.kodi/addons/plugin.video.amazon-test
2023-06-30 18:40:32.482 T:2140    debug <general>: CPythonInvoker(9, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): instantiating addon using automatically obtained id of "plugin.video.amazon-test" dependent on version 3.0.0 of the xbmc.python api
2023-06-30 18:40:32.814 T:2139    debug <general>: [Amazon VOD] Download Time: 0.3567756929999746
2023-06-30 18:40:32.817 T:2139    error <general>: [Amazon VOD] No JSON objects found in the page
2023-06-30 18:40:32.817 T:2139    debug <general>: CPythonInvoker(8, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): script successfully run
2023-06-30 18:40:32.817 T:2139    debug <general>: onExecutionDone(8, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py)
2023-06-30 18:40:32.853 T:2139    debug <general>: .
2023-06-30 18:40:32.946 T:2139    debug <general>: Python interpreter stopped
2023-06-30 18:40:32.946 T:2139    debug <general>: Thread LanguageInvoker 140307169531648 terminating
2023-06-30 18:40:32.954 T:2138    error <general>: GetDirectory - Error getting plugin://plugin.video.amazon-test/
2023-06-30 18:40:32.954 T:2138    debug <general>: Thread waiting 140305927194368 terminating
2023-06-30 18:40:33.406 T:2140    debug <CAddonSettings[0@plugin.video.amazon-test]>: trying to load setting definitions from old format...
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (at_check) was not found.
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (at_lang) was not found.
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (country) was not found.
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (drm_check) was not found.
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (fallback_method) was not found.
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (primevideo_area) was not found.
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (save_login) was not found.
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (set_login) was not found.
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (sub_lang) was not found.
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (subtitles) was not found.
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (uhd_android) was not found.
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (use_mfa) was not found.
2023-06-30 18:40:33.409 T:2140    debug <CSettingsManager>: requested setting (use_webapi) was not found.
2023-06-30 18:40:33.447 T:2140    debug <general>: [Amazon VOD] Requested {}
2023-06-30 18:40:33.466 T:1590  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2023-06-30 18:40:33.564 T:2140     info <general>: Skipped 5 duplicate messages..
2023-06-30 18:40:33.564 T:2140     info <general>: [Amazon VOD] Version: 0.9.9~beta
2023-06-30 18:40:33.564 T:2140     info <general>: [Amazon VOD] Unicode filename support: False
2023-06-30 18:40:33.564 T:2140     info <general>: [Amazon VOD] Locale: de-de / Language: de
2023-06-30 18:40:33.582 T:1590  warning <general>: CGUIMediaWindow::OnMessage - updating in progress
2023-06-30 18:40:33.775 T:2140    debug <general>: [Amazon VOD] Download Time: 0.20696601600002396
2023-06-30 18:40:33.781 T:2140    error <general>: [Amazon VOD] No JSON objects found in the page
2023-06-30 18:40:33.781 T:2140    debug <general>: CPythonInvoker(9, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): script successfully run
```

**Describe the bug**
After opening the Amazon Video Addon Kodi get stuck on the loading circle forever. You cannon exit with any input.

**Comment by stei-f** [comment]
See also #695, I think this is the same. I didn't want to hijack his bug with my debug logs.

It seems like it retries multiple times and eventually end up stuck.

**Comment by tux4you** [comment]
same here
xbian nexus
amazon vod 0.9.8+matrix.1

same error:
error <general>: [Amazon VOD] No JSON objects found in the page

looks like it stuck ... in tcpdump i do not see any connection retries

**Comment by Sandmann79** [comment]
Amazon now interposes an anti-robot captcha for normal page requests, which the addon does not currently support.
Now it would be easy to integrate the captcha query into the addon, but since this would complicate the handling of the addon, it would be better to know why the captcha appears in the addon and not when using a web browser.

**Comment by tux4you** [comment]
puh, ok ... sounds not so easy ... do you need help or have any ideas, how to integrate the captcha query into the addon?

**Comment by tux4you** [comment]
**blind chicken ... please reproduce this:**
i started a browser on my pc, logged in amazon and started an video/movie via prime
after that, i started your app and voila ... it works :/

**Comment by Kampfader** [comment]
"pc" is the same hardware that ubuntu runs on?

**Comment by tux4you** [comment]
> "pc" is the same hardware that ubuntu runs on?

no, sorry, its a normal workstation and has nothing to do with kodi
maybe there is some ip whitelisting on the amazon server, so if you logged in an opened something, you are trusted ... dont know
i tested this 2 times now

**Comment by stei-f** [comment]
> Amazon now interposes an anti-robot captcha for normal page requests, which the addon does not currently support. Now it would be easy to integrate the captcha query into the addon, but since this would complicate the handling of the addon, it would be better to know why the captcha appears in the addon and not when using a web browser.

What client_string/user_agent uses the addon? Empty http clients are almost every time to the robot detection.

**Comment by stei-f** [comment]
> > "pc" is the same hardware that ubuntu runs on?
> 
> no, sorry, its a normal workstation and has nothing to do with kodi maybe there is some ip whitelisting on the amazon server, so if you logged in an opened something, you are trusted ... dont know i tested this 2 times now

When I do this (on the same client kodi is running), I can get one step further. The addon loads and presents the first selection screen. Upon selecting a "section" it start hanging in the load circle. I will try reverting to the last stable addon version.

**Comment by tux4you** [comment]
yesterday was working ... today out ...

you need some help?

**Comment by Ronny-nerd** [comment]
Have you ever tried it with it...on Windows it works with it too...if you then under data source:
instead of Web = Android and delete the cache.

https://github.com/Sandmann79/xbmc/issues/674#issuecomment-1455485306

![screenshot3](https://github.com/Sandmann79/xbmc/assets/65504837/13492c87-1c86-4294-9309-2a1d7cde9f61)
![screenshot4](https://github.com/Sandmann79/xbmc/assets/65504837/634b139d-fb8c-4854-97f6-96cd8675be6f)

**Comment by tux4you** [comment]
this is not working on debian linux/ xbian :(
actually its not working anymore ... up to yesterday, it was working after 5-6 times trying ...

something to do? something, we can help you?

thanks

**Comment by tux4you** [comment]
to not push you to much ... but @Sandmann79 , do you think its possible to solve that problem?

**Comment by fkoss** [comment]
Same problem here!
If I start a video on another machine, kodi will NOT stuck on loading and shows the prime menu.

**Comment by tux4you** [comment]
> Same problem here! If I start a video on another machine, kodi will NOT stuck on loading and shows the prime menu.

not working anymore here ... anybody out there, who got it working?

**Comment by cow-crash** [comment]
Same problem since few weeks. Is anybody working on this?

**Comment by nocreativi** [comment]
> Have you ever tried it with it...on Windows it works with it too...if you then under data source: instead of Web = Android and delete the cache.

Changing the data source to "Android" and then back to "web" + deleting the cache works for me (kodi 20.2 Raspi4).

**Comment by tux4you** [comment]
one other question ... somebody tried browser launcher and firefox or chomium?
is that usable/working?

@Sandmann79 
i tried a little bit with http proxy, but did not see anything, expect this url ... maybe you see there something .... dont know
`TCP_MISS/503 7834 POST http://127.0.0.1:41921/gpr/https%3A%2F%2Fatv-ps-eu.amazon.de%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3DB00V412SFY%26deviceTypeID%3DAOAGZA014O5RE%26firmware%3D1%26deviceID%3Dcdc6dbc7477c496cad11164dd59cc72b%26marketplaceID%3DA1PA6795UKMFR9%26format%3Djson%26version%3D2%26gascEnabled%3Dfalse%26subtitleFormat%3DTTMLv2%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%2CTransitionTimecodes%26supportedDRMKeyScheme%3DDUAL_KEY`

**Comment by cow-crash** [comment]
On my system kodi 18.9 raspi3 the data source can't change. It's grayed. Clean cache has no effect.

**Comment by behemoth38** [comment]
@cowcrash, gleiches bei mir

**Comment by Sandmann79** [comment]
Captcha support is already built in. But it comes every two hours, which of course is not very user-friendly.
Next, I don't understand why the captcha appears in the addon - if the same http request is executed only with the same user-agent and cookie in curl, a response comes without captcha. Even a minimal code rebuild in python worked without problems.
Maybe @Varstahl has an idea what the problem could be? He definitely has more experience in this field :wink:

But since I'm not getting anywhere at this point, I've decided to continue working on the Android Api for now.
There will be a beta to test in the next few days.

**Comment by Sandmann79** [comment]
@tux4you sorry for the confusion, i meant in my not yet published builds

**Comment by tux4you** [comment]
hehe ... no problem :)
waiting for public builds ... everything is better than nothing

thank you for the great work

**Comment by tux4you** [comment]
@Sandmann79 will test tomorrow ... 
are you german? gute arbeit, vielen dank und einen schönen abend
[https://www.kodinerds.net/thread/44211-release-amazon-prime-instant-video/?postID=725403#post725403](url)

**Comment by Sandmann79** [comment]
@tux4you Yes I am. 
Since a little more info is needed here comes the announcement about the beta only now.

Included in the beta is a solver for the simple Amazon Captchas. This should make the Web-API usable again. This is realized by a separate module, which is only executable from Kodi 19 and higher. It is mandatory to install the module **before installing the beta**, otherwise an error will occur. With Kodi 18 or if the captcha is not recognized, it can be solved manually. 

In the beta, the Android api is also unlocked. 
Feedback from PrimeVideo users would be important here, as I could not test this properly due to a limited account and thus my watchlist is not displayed. Please be sure to test this. 
The Android Api can be activated at Settings > Data Source. There you can also activate the coloring of the content, but this does not work one hundred percent for Freevee and Live content. 

Important notes about the Android API:
- Unless already enabled in Settings > Connection > Register Device for 4K, it must be enabled and logged into the addon again to get the token needed to use the Api.
- The current profile is displayed but cannot be changed.

Downloads:
Captcha Solver Module: [script.module.amazoncaptcha-0.5.11+matrix.1.zip](https://github.com/Sandmann79/xbmc/files/12182253/script.module.amazoncaptcha-0.5.11%2Bmatrix.1.zip)
Beta 2 for Kodi 19 and higher: [plugin.video.amazon-test-0.9.9~beta2+matrix.1.zip](https://github.com/Sandmann79/xbmc/files/12182257/plugin.video.amazon-test-0.9.9.beta2%2Bmatrix.1.zip)
Beta 2 for Kodi 18: plugin.video.amazon-test-0.9.9~beta2+leia.zip - have to fix first

**Comment by cow-crash** [comment]
@ Sandmann79
thanks for your work.
i've tested 'plugin.video.amazon-test-0.9.9~beta2+leia.zip'
do i have to install the captcha plugin 'script.module.amazoncaptcha-0.5.11+matrix.1.zip' or is there a separate zip for leia?
I got following error on starting:
2023-07-27 16:21:10.569 T:1404040064  NOTICE: [Amazon VOD] MFA, DCQ or Captcha form
2023-07-27 16:21:10.861 T:1416590208   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'ModuleNotFoundError' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                EntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 67, in EntryPoint
                                                g.pv.BrowseRoot()
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 373, in BrowseRoot
                                                if not self.BuildRoot():
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 382, in BuildRoot
                                                home = GrabJSON(self._g.BaseUrl + ('' if self._g.UsePrimeVideo else '/gp/video/storefront'))
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 1122, in GrabJSON
                                                j = do(url, postData)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 1062, in do
                                                matches = Captcha(r)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 1104, in Captcha
                                                br = MFACheck(br, '', soup)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 531, in MFACheck
                                                if not wnd.solve_captcha():
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 1322, in solve_captcha
                                                except ModuleNotFoundError:
                                            NameError: global name 'ModuleNotFoundError' is not defined
                                            -->End of Python script error report<--

**Comment by Sandmann79** [comment]
@cow-crash as already written, the Captcha module only runs from Kodi 19 onwards. A fix for the bug in Kodi 18 is on the way…

**Comment by fkoss** [comment]
Dear Mr. @Sandmann79 

I'd like to confirm that your addons
script.module.amazoncaptcha-0.5.11+matrix.1.zip
and plugin.video.amazon-test-0.9.9~beta2+matrix.1.zip
are doing well on my Kodi 19.

I'm using PrimeVideo in a German region.
Since Kodi is running on a RaspberryPi, I'm using Input Stream. So if I temporarily set the app to Android, launching the PrimeVideo addon and switching back to Input Stream, it works. After a while (I recognized it on the next day) I will have to do the same thing to get the menu an videos back.

**Comment by Sandmann79** [comment]
@fkoss
Maybe I don't quite understand the question or you are confusing things.
The setting where Inputstream / Browser / Script / Android can be selected is for the playback method of the videos and not for the menu content. To my knowledge, only Inputstream works on the RasPi (unless you have Android installed).
The source for the menu content can be changed in the settings under data source.

**Comment by fkoss** [comment]
@Sandmann79 
Oh boy! All I wanted was to give you the requestet feedback as a Amazon Prime user...

I did never touch the data source settings the last 2 years, since I'm using Kodi.
I only knew the Android setting in the playback section, so I thought I have to change the settings there to enable your workaround.

Now, I've changed the data source to Android and **got a completely new user experience**!
It seems your 0.9.9b2 Version is working. Let me knew if I can do some tests (especially Amazon Prime).

Thank you for opening up new horizons and of course for your great work! :-)

**Comment by rocktobe** [comment]
Hi guys, 
I read you posts carrefull but I cant make amazon prime work sinds january..
I installed the latest addon Fixed Beta 2 for Kodi 18.
I tried input source Android or input stream, enabled register device for 4k playback ...
But it still doesnt work !
Error : "amazon vod error, check the log for mote information"
My configuration  : rpi3, librelec, kodi 18 (leia).

How and where do I read the logs??
I checked miscellanous create logfiles archive or upload kodi log via ares project but I cannot make it...
Can you help me tot find the log and to make it works? Thanks in advance

**Comment by DDuck007** [comment]
… works on Kodi Omega Libreelec 12 (nightly 20230727) with inputstream.adaptive 21.1.2 but crashes Kodi when using actual 21.1.3 version …

**Comment by Atomisirsi** [comment]
Thanks for your great work!

I tested the new Android API the last few days and recognized two things:
- The categories are sometimes duplicated (especially in main view).
- Seasons do not show thumbnails / any preview art anymore. When added to the favorites only a star symbol is shown.

**Comment by Atomisirsi** [comment]
Little update, maybe also related to

> currently the program mostly starts some tries and then it works correctly. But i have to do multiple restarts and ignore the failures.

During startup of Amazon VOD I get an exception, though everything seems to work normal afterwards:
```
...
2023-08-02 20:28:26.887 T:3727     INFO <general>: CAddonMgr::FindAddons: plugin.video.amazon-test v0.9.9~beta2+matrix.1 installed
...
023-08-02 20:28:26.890 T:3727     INFO <general>: CAddonMgr::FindAddons: script.module.amazoncaptcha v0.5.11+matrix.1 installed
...
2023-08-02 20:28:35.754 T:3963     INFO <general>: [Amazon VOD] Service: Proxy bound to 127.0.0.1:40751
2023-08-02 20:28:35.758 T:3963     INFO <general>: [Amazon VOD] Service: Proxy server started
2023-08-02 20:28:35.758 T:3963     INFO <general>: [Amazon VOD] Service started
2023-08-02 20:28:35.765 T:3963     INFO <general>: [Amazon VOD] Service: Exporting the Watchlist
...
2023-08-02 20:28:41.019 T:4088    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'PrimeVideo' object has no attribute 'Browse'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module>
                                                       EntryPoint()
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 80, in EntryPoint
                                                       g.pv.Browse('root/Watchlist/watchlist', export=5)
                                                   AttributeError: 'PrimeVideo' object has no attribute 'Browse'
                                                   -->End of Python script error report<--                                                                                                                                                     
```

**Comment by Sandmann79** [comment]
Future beta versions will now be made available at #700. 
Please post bugs and questions about the beta versions there.

**Comment by rocktobe** [comment]
Hi guys,
I finally decided to upgrade my kodi (leia 18) to kodi 19 because no captcha patch was available...
I succeeded with a lot o struggle to make amazon prime work again.
For that I needed to upgrade Libreelec 10 to 11 and thus to Kodi 19.5.
I had also to reinstall the inputstream adaptive.

unfortunately, now I am facing a new problem !

With LE11 installed, I cannot make my spdif soundcard work !
It is supposed to be selected in kodi sound settings but only the PCM 2.0 or HDMI work.
As i have an old DENON amplifier without HDMI I still need to use the spdif output to get dolby digital from amazon prime !
I found that threat on libreelec forum : 
No more audio after upgrading from LE9 to LE10 (generic x64 build).
"Audio device in LE9 was ALSA/SPDIF device with SPDIF passthrough enabled. Can no longer be selected in LE10, only PulseAudio/BlueTooth device listed (greyed out). I don't remember seeing PulseAudio/BlueTooth device there in LE9 (but I might be wrong; was definitely never used)."
https://forum.libreelec.tv/thread/24602-no-audio-or-no-remote-since-le10/

Unfortunately The procedure described doesnt work for me.
I'm not a computer geek specialist and I do not know how to edit the /storage/.config/system.d/kodi.service file.
I opened a session in raspbian and I cannot edit or create the file (I dont find it either).
Can you please provide me any help to make the spdif work again on LE11 (kodi 19).

Thanks in advance

**Comment by cow-crash** [comment]
I've update the old version (leia beta 3). After start i have to process the captcha. After that all seem to be okay.
@Sandmann79 thanx for your work
