### ISSUE TITLE
Unable to start stream - HTTP error

### ISSUE THREAD

**Issue by Dapsy2000** [Sandmann79/xbmc#708]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 0.98+matrix.1

**Account type**
- [ ] primevideo.com
- [x] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: RPi 3 B+
- OS version: LibreELEC 11.0.3
- Kodi version number: v20.2 (Nexus)

**Upload Logs**

Start Playback:

2023-10-13 15:25:44.389 T:1073 critical : [script.module.inputstreamhelper] ['ldd', '/storage/.kodi/cdm/libwidevinecdm.so'] cmd failed.
2023-10-13 15:25:44.389 T:1073 critical : [script.module.inputstreamhelper] Failed to check for missing Widevine libraries.
2023-10-13 15:25:44.389 T:1073 warning : [script.module.inputstreamhelper] User had declined an update on 2023-10-11 16:56
2023-10-13 15:25:44.412 T:1073 info : [Prime Video] postURL: http://127.0.0.1:58309/gpr/https%3A%2F%2Fatv-ps-eu.amazon.de%2Fcdp%2Fcatalog%2FGetPlaybackResources%3Fasin%3A6C7VWM8GH%26deviceTypeID%5HUAMHZB917O5BW%26firmware%3D1%26deviceID%5Bq816732561a294175bdc52c132a4fb5fc%26marketplaceID%6HQ5PA6795KJQAB6%26format%3Djson%26version%3D2%26gascEnabled%3Dfalse%26subtitleFormat%3DTTMLv2%26resourceUsage%3DImmediateConsumption%26consumptionType%3DStreaming%26deviceDrmOverride%3DCENC%26deviceStreamingTechnologyOverride%3DDASH%26deviceProtocolOverride%3DHttps%26deviceBitrateAdaptationsOverride%3DCVBR%252CCBR%26audioTrackId%3Dall%26languageFeature%3DMLFv2%26videoMaterialType%3DFeature%26desiredResources%3DPlaybackUrls%2CSubtitleUrls%2CForcedNarratives%2CTransitionTimecodes%26supportedDRMKeyScheme%3DDUAL_KEY
2023-10-13 15:25:44.567 T:1081 error : ----------------------------------------
2023-10-13 15:25:44.567 T:1081 error :

2023-10-13 15:25:44.567 T:1081 error : Exception occurred during processing of request from
2023-10-13 15:25:44.567 T:1081 error :
2023-10-13 15:25:44.567 T:1081 error : ('127.0.0.1', 59220)
2023-10-13 15:25:44.567 T:1081 error :

2023-10-13 15:25:44.570 T:1081 error : Traceback (most recent call last):

2023-10-13 15:25:44.571 T:1081 error :
2023-10-13 15:25:44.572 T:1081 error : File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread

2023-10-13 15:25:44.572 T:1081 error :
2023-10-13 15:25:44.572 T:1081 error : File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request

2023-10-13 15:25:44.572 T:1081 error :
2023-10-13 15:25:44.572 T:1081 error : File "/usr/lib/python3.11/socketserver.py", line 755, in init

2023-10-13 15:25:44.572 T:1081 error :
2023-10-13 15:25:44.572 T:1081 error : File "/usr/lib/python3.11/http/server.py", line 432, in handle

2023-10-13 15:25:44.573 T:1081 error :
2023-10-13 15:25:44.573 T:1081 error : File "/usr/lib/python3.11/http/server.py", line 420, in handle_one_request

2023-10-13 15:25:44.573 T:1081 error :
2023-10-13 15:25:44.573 T:1081 error : File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 208, in do_POST
self._AlterGPR(unquote(path[1]), headers, data)

2023-10-13 15:25:44.573 T:1081 error :
2023-10-13 15:25:44.573 T:1081 error : File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 246, in _AlterGPR
content = json.loads(content)
^^^^^^^^^^^^^^^^^^^

2023-10-13 15:25:44.573 T:1081 error :
2023-10-13 15:25:44.573 T:1081 error : File "/usr/lib/python3.11/json/init.py", line 346, in loads

2023-10-13 15:25:44.573 T:1081 error :
2023-10-13 15:25:44.573 T:1081 error : File "/usr/lib/python3.11/json/decoder.py", line 337, in decode

2023-10-13 15:25:44.573 T:1081 error :
2023-10-13 15:25:44.573 T:1081 error : File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode

2023-10-13 15:25:44.573 T:1081 error :
2023-10-13 15:25:44.573 T:1081 error : json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2023-10-13 15:25:44.573 T:1081 error :
2023-10-13 15:25:44.573 T:1081 error : ----------------------------------------
2023-10-13 15:25:44.574 T:1081 error :

2023-10-13 15:25:44.578 T:1073 error : [Prime Video] Error reason: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) (ConnectionError)
2023-10-13 15:25:44.633 T:874 info : VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=A6C7VWM8GH&mode=PlayVideo&name=Krieg+der+Bestatter&adult=0&trailer=0&selbitrate=0
2023-10-13 15:25:44.732 T:1082 info : Creating InputStream
2023-10-13 15:25:44.733 T:1082 info : Creating Demuxer
2023-10-13 15:25:44.735 T:1082 info : Opening stream: 0 source: 256
2023-10-13 15:25:44.735 T:1082 info : Finding audio codec for: 65536
2023-10-13 15:25:44.735 T:1082 info : CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder pcm_s16le
2023-10-13 15:25:44.736 T:1082 info : OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2023-10-13 15:25:44.736 T:1082 info : Creating audio thread
2023-10-13 15:25:44.736 T:1084 info : running thread: CVideoPlayerAudio::Process()
2023-10-13 15:25:44.737 T:1082 info : CVideoPlayer::OnExit()
2023-10-13 15:25:44.737 T:1082 info : VideoPlayer: eof, waiting for queues to empty
2023-10-13 15:25:44.737 T:1082 info : Closing stream player 1
2023-10-13 15:25:44.737 T:1082 info : Waiting for audio thread to exit
2023-10-13 15:25:44.752 T:1084 info : thread end: CVideoPlayerAudio::OnExit()
2023-10-13 15:25:44.752 T:1082 info : Closing audio device
2023-10-13 15:25:44.752 T:1082 info : Deleting audio codec
2023-10-13 15:25:44.763 T:1045 info : Deleting settings information for files plugin://plugin.video.amazon-test/?asin=A6C7VWM8GH&mode=PlayVideo&name=Krieg+der+Bestatter&adult=0&trailer=0&selbitrate=0
2023-10-13 15:25:44.782 T:901 error : EXCEPTION: Kodi is not playing any file
2023-10-13 15:25:44.785 T:874 info : CVideoPlayer::CloseFile()
2023-10-13 15:25:44.785 T:874 info : VideoPlayer: waiting for threads to exit
2023-10-13 15:25:44.785 T:874 info : VideoPlayer: finished waiting
2023-10-13 15:25:44.786 T:874 info : CVideoPlayer::CloseFile()
2023-10-13 15:25:44.786 T:874 info : VideoPlayer: waiting for threads to exit
2023-10-13 15:25:44.786 T:874 info : VideoPlayer: finished waiting

**Describe the bug**

RTL+ and Prime Video stopped playing video a few days ago.

For this reason I did an update for all installed addons including InputStream Adaptive.

-----------------------------------------------------------------------------------------------------------------------------------
2023-10-13 15:27:25.809 T:1100  warning <general>: [script.module.inputstreamhelper]
                                                   Kodi version 20.2 is running on a Linux system with arm architecture.

                                                   InputStream Helper is at version 0.6.1+matrix.1
                                                   InputStream Adaptive is at version 20.3.13.1

                                                   Widevine CDM is at version 4.10.2662.3 and was installed on 2023-07-29 17:41
                                                   It was extracted from Chrome OS image ELM with version 15572.57.0
                                                   It was last checked for updates on 2023-07-29 17:42
                                                   It is installed at /storage/.kodi/cdm/

                                                   Please report issues to: https://git.io/JfKJb
-----------------------------------------------------------------------------------------------------------------------------------

Maybe anyone can provide a solution.

**Comment by henk31** [comment]
Same problem here

**Comment by Dapsy2000** [comment]
> Same problem here
Schau mal im kodinerds Forum https://www.kodinerds.net/thread/44211-release-amazon-prime-instant-video/?pageNo=445 vorbei, damit ich es hinbekommen.

1. Captcha Modul installieren
2. Amazon Add-On 0.9.9 Beta 6 installieren
3. Addon Einstellungen -> Datenquelle unter WEB den Cache löschen und dann statt WEB,  Android API aktivieren
4. Restart 

Quellen für die Module und Add-On Beta findest du in den Posts im Forum.
