### ISSUE TITLE
When trying to play a movie "http error" message appears

### ISSUE THREAD

**Issue by gretakbt** [Sandmann79/xbmc#731]
**Addon used**
- [x ] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [x ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: raspberry pi 4 4GB
- OS version: Libreelec 10.0.3
- Kodi version number: 19.4 (matrix)

**Upload Logs**

 
ERROR <general>: /storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'atv-ps-eu.amazon.de'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
                                                     warnings.warn(
                                                   
2024-03-15 22:45:37.671 T:948     ERROR <general>: ----------------------------------------
2024-03-15 22:45:37.671 T:948     ERROR <general>: 
                                                   
2024-03-15 22:45:37.671 T:948     ERROR <general>: Exception happened during processing of request from
2024-03-15 22:45:37.671 T:948     ERROR <general>:  
2024-03-15 22:45:37.671 T:948     ERROR <general>: ('127.0.0.1', 42770)
2024-03-15 22:45:37.671 T:948     ERROR <general>: 
                                                   
2024-03-15 22:45:37.673 T:948     ERROR <general>: Traceback (most recent call last):
                                                   
2024-03-15 22:45:37.673 T:948     ERROR <general>: 
2024-03-15 22:45:37.673 T:948     ERROR <general>:   File "/usr/lib/python3.8/socketserver.py", line 683, in process_request_thread
                                                   
2024-03-15 22:45:37.673 T:948     ERROR <general>: 
2024-03-15 22:45:37.673 T:948     ERROR <general>:   File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
                                                   
2024-03-15 22:45:37.673 T:948     ERROR <general>: 
2024-03-15 22:45:37.673 T:948     ERROR <general>:   File "/usr/lib/python3.8/socketserver.py", line 747, in __init__
                                                   
2024-03-15 22:45:37.673 T:948     ERROR <general>: 
2024-03-15 22:45:37.673 T:948     ERROR <general>:   File "/usr/lib/python3.8/http/server.py", line 427, in handle
                                                   
2024-03-15 22:45:37.673 T:948     ERROR <general>: 
2024-03-15 22:45:37.673 T:948     ERROR <general>:   File "/usr/lib/python3.8/http/server.py", line 415, in handle_one_request
                                                   
2024-03-15 22:45:37.673 T:948     ERROR <general>: 
2024-03-15 22:45:37.673 T:948     ERROR <general>:   File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 210, in do_POST
                                                       self._AlterGPR(unquote(path[1]), headers, data)
                                                   
2024-03-15 22:45:37.673 T:948     ERROR <general>: 
2024-03-15 22:45:37.673 T:948     ERROR <general>:   File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 252, in _AlterGPR
                                                       content = json.loads(content)
                                                   
2024-03-15 22:45:37.673 T:948     ERROR <general>: 
2024-03-15 22:45:37.673 T:948     ERROR <general>:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
                                                   
2024-03-15 22:45:37.673 T:948     ERROR <general>: 
2024-03-15 22:45:37.673 T:948     ERROR <general>:   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
                                                   
2024-03-15 22:45:37.673 T:948     ERROR <general>: 
2024-03-15 22:45:37.674 T:948     ERROR <general>:   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
                                                   
2024-03-15 22:45:37.674 T:948     ERROR <general>: 
2024-03-15 22:45:37.674 T:948     ERROR <general>: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   
2024-03-15 22:45:37.674 T:948     ERROR <general>: 
2024-03-15 22:45:37.674 T:948     ERROR <general>: ----------------------------------------
2024-03-15 22:45:37.674 T:948     ERROR <general>: 
                                                   
2024-03-15 22:45:37.676 T:934     ERROR <general>: [Amazon VOD] Error reason: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')) (ConnectionError)
2024-03-15 22:45:37.694 T:934      INFO <general>: CPythonInvoker(9, /storage/.kodi/addons/plugin.video.amazon-test/default.py): script successfully run
2024-03-15 22:45:37.713 T:807      INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.amazon-test/?asin=B0CM6YP9SZ&mode=PlayVideo&name=Poor+Things&adult=0&trailer=0&selbitrate=0
2024-03-15 22:45:37.714 T:950      INFO <general>: Creating InputStream

**Describe the bug**

when I try to run a movie error messages appears: "Playback not possible - http error"

**Comment by Sandmann79** [comment]
It appears that Dissable SSL Certificate Verification is activated in the settings under Connections. This setting is only intended for developers and should never be activated lightly, as it represents an increased security risk.

**Comment by perlego-maares** [comment]
HI @Sandmann79 first, thanks for this absolutely awesome add on! 

I having the exact same problem, non the less, toggling SSL Certificate Verification does not work for me. Tried to update the package but does not seem to do the trick.
