### ISSUE TITLE
error in fetching 'Watchlist'

### ISSUE THREAD

**Issue by cow-crash** [Sandmann79/xbmc#736]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [ ] primevideo.com
- [x) amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: raspberry pi 3
- OS version: libreelec 9.2.8
- Kodi version number: 18.9

**Upload Logs**

**Describe the bug**

Hi,
since few day there's an error in fetching 'Watchlist/All'.
fetching 'Watchlist/Films' is okay.
fetching 'Watchlist/Series' has error.
in log there this entries:

2024-04-22 03:00:00.915 T:1423176576   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/watchlist/all
2024-04-22 03:00:00.917 T:1937312192   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/watchlist/all) failed

it seems that amazon has changed the structure :(

**Comment by DanielSiepmann** [comment]
My log has some more info on that:
```
2024-04-23 17:27:04.452 T:902     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'titleIds'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 9, in <module>
                                                       EntryPoint(argv)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 67, in EntryPoint
                                                       _g.pv.Route(verb, path)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 184, in Route
                                                       elif 'browse' == verb: self._g.pv.Browse(path)
                                                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 458, in Browse
                                                       node, breadcrumb = self._TraverseCatalog(path)
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 154, in _TraverseCatalog
                                                       self._LazyLoad(node[nodeName], pathList[0:1 + i])
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 1383, in _LazyLoad
                                                       bUpdatedVideoData |= AddSeason(breadcrumb[-1], o, bCacheRefresh, iu)
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 839, in AddSeason
                                                       bUpdatedVideoData |= ParseSinglePage(oid, season, bCacheRefresh, url=url)
                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 1016, in ParseSinglePage
                                                       for e in le['titleIds']:
                                                                ~~^^^^^^^^^^^^
                                                   KeyError: 'titleIds'
                                                   -->End of Python script error report<--

2024-04-23 17:27:04.908 T:901     error <general>: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/watchlist/tv/nextPage/amzn1.dv.gti.40a9f6d2-bef1-501c-2313-5acbaf00ea0d/B00ERNJYNA
2024-04-23 17:27:04.926 T:706     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/watchlist/tv/nextPage/amzn1.dv.gti.40a9f6d2-bef1-501c-2313-5acbaf00ea0d/B00ERNJYNA) failed
```

Thanks for opening the issue, I thought I broke something :D

**Comment by FestivaL5** [comment]
Hello,
I'm just install new fresh buil o f kodi for test and I have same issues.
I can load and watch movies but if the list countains series, I have an error.

Thank for your great work !
Clément

**Comment by mfp85** [comment]
Hi, I had the same issue fetching both the watchlist/series but also using the search.
Your [latest commit](https://github.com/Sandmann79/xbmc/commit/72f61501a16f7e4b4f0eefec5fb0bc46907963c3) fixed this issue for me. 
Thanks for the update!

**Comment by kl8ter** [comment]
Hello,
I have the same issue. I have installed the version 1.0.5
on Raspberry 4 on libreelec.
I have seen that something has changed in code. But not a new release exists. 
How can I install the "test" release version?

**Comment by Soybean44** [comment]
Hey,
I have the same issue, I installed the latest version straight from GitHub by cloning the repo and copying the plugin folder to my .kodi directory, however nothing works. watchlist doesn't work as well as searching. I'm on a Raspberry Pi 4 with a fresh install of libreelec. everything is as fresh as fresh can be so I don't know if there is anything else worth mentioning but feel free to ask me if you want any debug info

**Comment by cow-crash** [comment]
menu items like 'search' also disfunctional. @Sandmann79 do you regard this failure?

**Comment by DanielSiepmann** [comment]
> Hi, I had the same issue fetching both the watchlist/series but also using the search. Your [latest commit](https://github.com/Sandmann79/xbmc/commit/72f61501a16f7e4b4f0eefec5fb0bc46907963c3) fixed this issue for me. Thanks for the update!

Thanks for mentioning. The commit also fixed the issue for me.

For those interested. The file to adjust was located at `.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py`, at least for me. I modified the file in the same way as done in the mentioned commit. Maybe this helps some more people until a new version is released.

Also downloading and unpacking the current "master" branch should work as well. One should be able to install the add-on from the zip.

**Comment by cow-crash** [comment]
> > Hi, I had the same issue fetching both the watchlist/series but also using the search. Your [latest commit](https://github.com/Sandmann79/xbmc/commit/72f61501a16f7e4b4f0eefec5fb0bc46907963c3) fixed this issue for me. Thanks for the update!
> 
> Thanks for mentioning. The commit also fixed the issue for me.
> 
> For those interested. The file to adjust was located at `.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py`, at least for me. I modified the file in the same way as done in the mentioned commit. Maybe this helps some more people until a new version is released.
> 
> Also downloading and unpacking the current "master" branch should work as well. One should be able to install the add-on from the zip.

for me, this commit also fix the error. thanx, great work.

**Comment by kl8ter** [comment]
> Hi, I had the same issue fetching both the watchlist/series but also using the search. Your [latest commit](https://github.com/Sandmann79/xbmc/commit/72f61501a16f7e4b4f0eefec5fb0bc46907963c3) fixed this issue for me. Thanks for the update!

I checked the code - it's fine - but or me it doesn't work.

**Comment by cow-crash** [comment]
> Hello, I have the same issue. I have installed the version 1.0.5 on Raspberry 4 on libreelec. I have seen that something has changed in code. But not a new release exists. How can I install the "test" release version?

i think, you've to install version 1.0.6,. then do the change of commit
