### ISSUE TITLE
Cannot access to tv shows watchlist

### ISSUE THREAD

**Issue by cpassuel** [Sandmann79/xbmc#737]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.05

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Raspberry Pi 4
- OS version: LibreElec 9.2.8
- Kodi version number: v18

**Upload Logs**

**Describe the bug**

I have an error when I click on the tv shows watch list. The films watchlist is fine. I don't know if it's related to a specific entry on my watchlist or if it's a tv shows watchlist issue

2024-04-29 19:04:00.044 T:2530284352  NOTICE: [Amazon VOD] Version: 1.0.5
2024-04-29 19:04:00.045 T:2530284352  NOTICE: [Amazon VOD] Unicode filename support: False
2024-04-29 19:04:00.047 T:2530284352  NOTICE: [Amazon VOD] Locale: en-us / Language: fr
2024-04-29 19:04:00.085 T:2518676288  NOTICE: [Amazon VOD] Version: 1.0.5
2024-04-29 19:04:00.085 T:2518676288  NOTICE: [Amazon VOD] Unicode filename support: False
2024-04-29 19:04:00.087 T:2518676288  NOTICE: [Amazon VOD] Locale: en-us / Language: fr
2024-04-29 19:04:00.232 T:2518676288 WARNING: Attempt to use invalid handle 2
2024-04-29 19:04:00.232 T:2530284352 WARNING: Attempt to use invalid handle 1
2024-04-29 19:04:04.963 T:3011190848 WARNING: Previous line repeats 3 times.
2024-04-29 19:04:04.963 T:3011190848 WARNING: CGUIMediaWindow::OnMessage - updating in progress
2024-04-29 19:04:07.297 T:2470810432 WARNING: Previous line repeats 5 times.
2024-04-29 19:04:07.297 T:2470810432 WARNING: Attempt to use invalid handle 3
2024-04-29 19:04:22.735 T:2470810432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'titleIds'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 9, in <module>
                                                EntryPoint(argv)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 67, in EntryPoint
                                                _g.pv.Route(verb, path)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 184, in Route
                                                elif 'browse' == verb: self._g.pv.Browse(path)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 458, in Browse
                                                node, breadcrumb = self._TraverseCatalog(path)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 154, in _TraverseCatalog
                                                self._LazyLoad(node[nodeName], pathList[0:1 + i])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 1383, in _LazyLoad
                                                bUpdatedVideoData |= AddSeason(breadcrumb[-1], o, bCacheRefresh, iu)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 839, in AddSeason
                                                bUpdatedVideoData |= ParseSinglePage(oid, season, bCacheRefresh, url=url)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 1016, in ParseSinglePage
                                                for e in le['titleIds']:
                                            KeyError: u'titleIds'
                                            -->End of Python script error report<--
2024-04-29 19:04:22.904 T:2470810432 WARNING: CPythonInvoker(5, /storage/.kodi/addons/plugin.video.amazon-test/default.py): the python script "/storage/.kodi/addons/plugin.video.amazon-test/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon7xbmcgui6DialogE,N9XBMCAddon9xbmcaddon5AddonE,N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE
2024-04-29 19:04:22.905 T:2447110976   ERROR: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/watchlist/tv
2024-04-29 19:04:22.929 T:3011190848   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/watchlist/tv) failed
2024-04-29 19:04:24.647 T:2470810432 WARNING: Attempt to use invalid handle 4

**Comment by cpassuel** [comment]
By looking a the file on my system, it's not the same as master version on github.
My version below
```
            # Episodes lists
            if 'collections' in state:
                # "collections": {"amzn1.dv.gti.[▒^`▒]": [{"titleIds": ["amzn1.>
                for gti, lc in state['collections'].items():
                    for le in lc:
                        for e in le['titleIds']:
                            GTIs.append(e)

```

**Comment by cpassuel** [comment]
I updated to v1.0.6 manually (from the source code) and it's working. I don't know why the plugin it's not updating through kodi itself

**Comment by Sandmann79** [comment]
Sometimes it takes some time for the update to arrive everywhere. In the meantime, you can initiate a repo refresh within the add-on browser via the context menu. Afterwards, the new version should be found.
This issue has been fixed with the latest release.
