### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'get'

### ISSUE THREAD

**Issue by Khomotica** [Sandmann79/xbmc#738]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.0.6+matrix.1

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Rasp pi 4
- OS version: LibreElec 11.0.6
- Kodi version number: 20.3

**Upload Logs**

**Describe the bug**

New issue appears when trying to fetch episodes from one TV Serie : 

2024-05-16 21:34:13.581 T:29653   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'bool' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 9, in <module>
                                                       EntryPoint(argv)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 67, in EntryPoint
                                                       _g.pv.Route(verb, path)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 184, in Route
                                                       elif 'browse' == verb: self._g.pv.Browse(path)
                                                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 490, in Browse
                                                       title = entry.get('title', nodeName)
                                                               ^^^^^^^^^
                                                   AttributeError: 'bool' object has no attribute 'get'
                                                   -->End of Python script error report<--

2024-05-16 21:34:13.859 T:29888   error <general>: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/watchlist/tv/amzn1.dv.gti.a89077d1-60d3-4d8f-9df3-79c132d764b2/amzn
1.dv.gti.8f7b12dc-fea8-4499-b6bd-73a3735b7253
2024-05-16 21:34:13.889 T:875     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/watchlist/tv/amzn1.dv.gti.a89077d1-60d3-4d8f-9df3-79c132d764b2/amz
n1.dv.gti.8f7b12dc-fea8-4499-b6bd-73a3735b7253) failed

**Comment by Sandmann79** [comment]
The entry for the season in the cache is probably defective. 
However, this can be easily repaired by refreshing the season. To do this, select the relevant season in the season overview and select Refresh in the context menu.

**Comment by Khomotica** [comment]
> The entry for the season in the cache is probably defective. However, this can be easily repaired by refreshing the season. To do this, select the relevant season in the season overview and select Refresh in the context menu.

Nice one .. it works
@Sandmann79 : Thanks man great job
