### ISSUE TITLE
Amazon - unable to get content

### ISSUE THREAD

**Issue by notoco** [Sandmann79/xbmc#742]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: GT King s922x
- OS version: Coreelec 21 Omega
- Kodi version number: 21

**Upload Logs**

```2024-06-01 07:50:15.380 T:26716    info <general>: [Amazon VOD] Version: 1.0.6+matrix.1
2024-06-01 07:50:15.380 T:26716    info <general>: [Amazon VOD] Unicode filename support: False
2024-06-01 07:50:15.382 T:26716    info <general>: [Amazon VOD] Locale: en-us / Language: pl
2024-06-01 07:50:15.572 T:26684    info <general>: [Amazon VOD] Version: 1.0.6+matrix.1
2024-06-01 07:50:15.573 T:26684    info <general>: [Amazon VOD] Unicode filename support: False
2024-06-01 07:50:15.574 T:26684    info <general>: [Amazon VOD] Locale: en-us / Language: pl
2024-06-01 07:50:26.306 T:26773   error <general>: GetDirectory - Error getting plugin://plugin.video.amazon-test/
2024-06-01 07:50:28.574 T:4018    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed
2024-06-01 07:50:34.395 T:26813   error <general>: GetDirectory - Error getting plugin://plugin.video.amazon-test/
2024-06-01 07:50:44.832 T:4018     info <general>: NFS is idle. Closing the remaining connections.
2024-06-01 07:50:47.157 T:4018    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed
2024-06-01 07:50:47.833 T:26887    info <general>: [Amazon VOD] Login
2024-06-01 07:50:47.840 T:26887    info <general>: [Amazon VOD] Retrieve territoral config
2024-06-01 07:50:47.842 T:26887    info <general>: [Amazon VOD] getURL: https://atv-ps.amazon.com/cdp/usage/v3/GetAppStartupConfig?deviceTypeID=A28RQHJKHM2A2W&deviceID=8525437f1b364bcd9f38e4342a36b68d&firmware=1&version=1&supportedLocales=da_DK,de_DE,en_US,es_ES,fi_FI,fr_FR,hi_IN,id_ID,it_IT,ko_KR,nb_NO,nl_NL,pl_PL,pt_BR,pt_PT,ru_RU,sv_SE,ta_IN,te_IN,th_TH,tr_TR,zh_CN,zh_TW,ms_MY,hu_HU,ro_RO,fil_PH,cs_CZ,el_GR,he_IL,ar_AE,ja_JP&format=json
2024-06-01 07:50:48.755 T:4018     info <general>: Loading skin file: DialogKeyboard.xml, load type: KEEP_IN_MEMORY
2024-06-01 07:51:52.051 T:26887    info <general>: [Amazon VOD] Connect to SignIn Page
2024-06-01 07:52:00.083 T:4018     info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2024-06-01 07:52:01.194 T:26970   error <general>: GetDirectory - Error getting plugin://plugin.video.amazon-test/
2024-06-01 07:52:15.408 T:4018    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/) failed
2024-06-01 07:52:17.751 T:27030    info <general>: [Amazon VOD] Version: 1.0.6+matrix.1
2024-06-01 07:52:17.752 T:27030    info <general>: [Amazon VOD] Unicode filename support: False
2024-06-01 07:52:17.753 T:27030    info <general>: [Amazon VOD] Locale: en-us / Language: pl
2024-06-01 07:52:17.935 T:26896   error <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/e/e78281d5.png
2024-06-01 07:52:21.919 T:27047   error <general>: [Amazon VOD] Error reason: 400 error (NoRetries)
2024-06-01 07:52:21.925 T:27047   error <general>: [Amazon VOD] Unable to fetch the url: /gp/video/api/paginateCollection?journeyIngressContext=8%7CEgRzdm9k&serviceToken=eyJ0eXBlIjoiaHBhZ2UiLCJuYXYiOmZhbHNlLCJzZWMiOiJjZW50ZXIiLCJwcmlkIjoiNmI2NTA1ODgtYThiNC00MTVmLThiZmYtMGUwMjgxNDY0YzExIiwiZmlsdGVyIjp7fSwib2Zmc2V0IjoyLCJucHNpIjoyMCwib3JlcSI6IjM2MDc4YTljLWNhZDYtNDMzNC1hNTJhLWYwY2YxZGVjM2JiNjoxNzE3MjIwNDU4MDAwIiwiYXBNYXgiOjM2LCJzdHJpZCI6IjE6MTJPUEQ5OU9LNkRLS0IjI01aUVdHWkxVTVZTRUdZTFNONTJYR1pMTSIsInN0S2V5Ijoie1wic2JzaW5cIjowLFwiY3Vyc2l6ZVwiOjM2LFwicHJlc2l6ZVwiOjB9Iiwib3JlcWsiOiIxMnk4eFR6UWpqUHBkTGFjNW91Tk9VT2MrMXNwSUpJVXpObUZodXBQREhVPSIsIm9yZXFrdiI6MX0%3D&paginationTargetId=V2%3D4AEA6u69gYPeuYe-toZwYWdlSWSIcGFnZVR5cGWMY29sbGVjdGlvbklkiHdpZGdldElkjo5zd2lmdElkVmVyc2lvbt7AioRraWRzi4VtZXJjaIyOqjE6MTJPUEQ5OU9LNkRLS0IjI01aUVdHWkxVTVZTRUdZTFNONTJYR1pMTY0PjoJWMg%3D%3D&pageId=home&startIndex=0&pageSize=20&pageType=home&isCleanSlateActive=1&isDiscoverActive=1&isLivePageActive=1&variant=desktopWindows&payloadScheme=default&actionScheme=default&collectionType=Container
2024-06-01 07:52:21.929 T:27047   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 9, in <module>
                                                       EntryPoint(argv)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 67, in EntryPoint
                                                       _g.pv.Route(verb, path)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 184, in Route
                                                       elif 'browse' == verb: self._g.pv.Browse(path)
                                                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 490, in Browse
                                                       title = entry.get('title', nodeName)
                                                               ^^^^^^^^^
                                                   AttributeError: 'str' object has no attribute 'get'
                                                   -->End of Python script error report<--
                                                   
2024-06-01 07:52:22.235 T:27046   error <general>: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/coll1_Strona+g%C5%82%C3%B3wna/%5BCOLOR+FF00A8E0%5DPrime%5B%2FCOLOR%5D+Akcja+i+przygoda
2024-06-01 07:52:22.260 T:4018    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/coll1_Strona+g%C5%82%C3%B3wna/%5BCOLOR+FF00A8E0%5DPrime%5B%2FCOLOR%5D+Akcja+i+przygoda) failed```


**Describe the bug**
<!-- ⚠️ A clear and concise description of what the bug is. -->

After logging in, when entering any category, a connection error appears

**Comment by notoco** [comment]
Changing the settings from webpage to android solved the problem.
