### ISSUE TITLE
Watchlist (My Stuff) is empty

### ISSUE THREAD

**Issue by GG-76** [Sandmann79/xbmc#759]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Sony Bravia TV (Google TV)
- OS version: Android TV 10
- Kodi version number: Kodi 21.1

**Describe the bug**

Hi, since the latest version of the addon, the My Stuff (Prime Video Watchlist) folder is empty and it is not possible to get the series list from the Prime Video watchlist.

**Comment by Sandmann79** [comment]
Are you using the latest Addon version 1.1.2?
If yes, please upload a log, cannot reproduce the error. 
Possibly another upcoming change to Amazon's website.
But you are the only one currently reporting this error.

**Comment by GG-76** [comment]
@Sandmann79 It took a while. I am attaching the log, hopefully it will be of some use

https://paste.kodi.tv/etifehoxuy.kodi

**Comment by mlc42** [comment]
Same here Watchlist Series ist empty (watchlist films is okay)
After refereshing the list i get this error

2024-11-01 11:13:16.345 T:1304     info <general>: [Amazon VOD] Refresh params: ({'lazyLoadURL': '/gp/video/mystuff/watchlist/tv/ref=atv_mys_wl_tab', 'title': 'Serien'}, ['root', 'Watchlist', 'watchlist', 'tv'], True)
2024-11-01 11:15:14.907 T:1045     info <general>: CActiveAESink::OpenSink - initialize sink
2024-11-01 11:15:14.907 T:1045     info <general>: CAESinkALSA::Initialize - Attempting to open device "sysdefault:CARD=sndrpihifiberry"
2024-11-01 11:15:14.916 T:1045     info <general>: CAESinkALSA::Initialize - Opened device "sysdefault:CARD=sndrpihifiberry"
2024-11-01 11:15:14.917 T:1045     info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2024-11-01 11:15:14.917 T:1045     info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE4
2024-11-01 11:15:21.019 T:1304    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 9, in <module>
                                                       EntryPoint(argv)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 67, in EntryPoint
                                                       _g.pv.Route(verb, path)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 184, in Route
                                                       elif 'browse' == verb: self._g.pv.Browse(path)
                                                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 617, in Browse
                                                       sorted([(folderTypeList.count(x), x) for x in set(folderTypeList) if x not in [3, 4]], reverse=True)[0][1]
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2024-11-01 11:15:21.402 T:1365    error <general>: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/watchlist/tv
2024-11-01 11:15:21.432 T:1037    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/watchlist/tv) failed

**Comment by mlc42** [comment]
@Sandmann79 with the latest WebAPI all is okay again. Kodi Nexus Raspi 4
Thank you.

**Comment by microlity** [comment]
Same here getting the index out of range error when trying to refresh the list after clearing the data source cache:

2024-11-02 22:59:12.071 T:12988   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/default.py", line 9, in <module>
                                                       EntryPoint(argv)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 67, in EntryPoint
                                                       _g.pv.Route(verb, path)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 184, in Route
                                                       elif 'browse' == verb: self._g.pv.Browse(path)
                                                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 617, in Browse
                                                       sorted([(folderTypeList.count(x), x) for x in set(folderTypeList) if x not in [3, 4]], reverse=True)[0][1]
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--

Also tried complete new user login and reinstalling Amazon VOD app but nothing helped.

**Comment by mlc42** [comment]
i use the the 1.1.2 and only download the web_api.py and replace it in the addon folder.
Then i restart the raspi and refresh the series folder. It took a while but after that all is ok.

**Comment by microlity** [comment]
Thanks @mcl42 for confirming that latest modifications in the repo fixed this issue. Was also one steps away from applying mentioned modifications after I saw your comment from yesterday. Rather than that I would prefer to recognize a new version being released, as it is likely to affect more users soon.

@Sandmann79 Is a new release planned in the near future?

**Comment by Sandmann79** [comment]
@mlc42, thank you for testing. Are you a PrimeVideo.com or Amazon.tld user?

@microlity it will be released within the next 2 days. Still need to do some testing.

**Comment by mlc42** [comment]
@Sandmann79  I use Amazon.de

**Comment by GG-76** [comment]
Hello, I updated to version 1.1.3 but the problem still occurs, so I don't know what's wrong. I can still try to reinstall the addon completely.

**Comment by GG-76** [comment]
@Sandmann79  I've done that twice already and my watchlist is still empty anyway :(

**Comment by Sandmann79** [comment]
@GG-76 Sorry, I misread that.
Please activate the settings Dump json replies and Log HTTP response content in Settings / Miscellaneous, delete both caches and then only navigate to the series watchlist in the addon. 
After that go to Settings / Miscellaneous / Create Log files archive and upload it here together with the kodi.log.

**Comment by GG-76** [comment]
@Sandmann79 here it is.
[kodi.log](https://github.com/user-attachments/files/17692066/kodi.log)
[logfiles_20241110-165422.zip](https://github.com/user-attachments/files/17692067/logfiles_20241110-165422.zip)

**Comment by Forlorn-Hope** [comment]
Just adding to the initial users ticket.  I am also having the same issue.  Initially my Watchlist was empty.  I cleared the cache, and rebooted, still empty.  I came back a few hours later, and my folder is now populated, but all the series folders are empty.  The last time this happened, as we all tend to know, is that Amazon made a change to their web interface.  I have attached my log files to confirm and assist the original poster: 

[kodi.log](https://github.com/user-attachments/files/17692924/kodi.log)
[logfiles_20241110-150500.zip](https://github.com/user-attachments/files/17692925/logfiles_20241110-150500.zip)

**Comment by GG-76** [comment]
i tried version 1.1.4. and still unchanged.

**Comment by GG-76** [comment]
@Sandmann79 Hi, can you fix this bug please?

**Comment by GG-76** [comment]
It looks like I'm not going to be able to fix it. Has anyone else had this problem please?

**Comment by Sandmann79** [comment]
@GG-76 please upload new logs, the old ones did not contain any useful information (only the Addon was started and the main menu was loaded). 
Empty both caches beforehand.

**Comment by GG-76** [comment]
@Sandmann79 ok i try it, and log from @Forlorn-Hope , who have same problem is useful too?

**Comment by GG-76** [comment]
@Sandmann79  So, Here it is, perhaps this time it will be more useful. I noticed now that I even show all folders twice. My Stuff folder i can open, but the spikes will be shown and does not get off any content

[logfiles_20250315-115627.zip](https://github.com/user-attachments/files/19261058/logfiles_20250315-115627.zip)
[kodi.log](https://github.com/user-attachments/files/19261057/kodi.log)
