### ISSUE TITLE
'>' not supported between instances of 'LooseVersion' and 'Version'

### ISSUE THREAD

**Issue by lagweasel** [Sandmann79/xbmc#761]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: Sandmann79,Varstahl-1.1.2+matrix.1

**Account type**
- [X] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Intel NUC 11th gen
- OS version: Ubuntu 24.04.1 LTS (noble)
- Kodi version number: 21.1-Omega (via flatpak)

**Upload Logs**

[Log link](https://gist.github.com/lagweasel/27fba0c5bed877ec635fca7151bddb3d)

**Describe the bug**

Trying to play any video from Amazon Prime VOD:
"Amazon VOD error / Check the log for more information"
"One or more items failed to play. Check the log for more information about this message"
(see log link above)

**Comment by AdamNo2** [comment]
i have the exact same problem with Ubuntu 24 & Kodi 21 flatpak. 
playing an amazon item results in:

> 2024-09-20 14:05:39.690 T:19376   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>' not supported between instances of 'LooseVersion' and 'Version'
                                                   Traceback (most recent call last):
                                                     File "/home/ak/.var/app/tv.kodi.Kodi/data/addons/plugin.video.amazon-test/default.py", line 9, in <module>
                                                       EntryPoint(argv)
                                                     File "/home/ak/.var/app/tv.kodi.Kodi/data/addons/plugin.video.amazon-test/resources/lib/startup.py", line 75, in EntryPoint
                                                       PlayVideo(args.get('name', ''), args.get('asin'), args.get('adult', '0'), int(args.get('trailer', '0')), int(args.get('selbitrate', '0'
)))
                                                     File "/home/ak/.var/app/tv.kodi.Kodi/data/addons/plugin.video.amazon-test/resources/lib/playback.py", line 472, in PlayVideo
                                                       suc = _IStreamPlayback(asin, name, streamtype, isAdult, extern)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/ak/.var/app/tv.kodi.Kodi/data/addons/plugin.video.amazon-test/resources/lib/playback.py", line 343, in _IStreamPlayback
                                                       if not inputstream_helper.check_inputstream():
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/ak/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 411, in check_i
nputstream
                                                       if self.drm == 'widevine' and not self._supports_widevine():
                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/ak/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 158, in _suppor
ts_widevine
                                                       if parse_version(config.WIDEVINE_MINIMUM_KODI_VERSION[system_os()]) > parse_version(kodi_version()):
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: '>' not supported between instances of 'LooseVersion' and 'Version'
                                                   -->End of Python script error report<--
2024-09-20 14:05:39.958 T:7       error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.amazon-test/?asin=B0D6JWPD1M&mode=PlayVideo&name=Ich+%E2%80%93+Ei
nfach+Unverbesserlich+4&adult=0&trailer=0&selbitrate=0]


i tried to re-install widevine cdm with the imputstream helper addon but it fails in a similiar way:

> 2024-09-20 14:06:33.008 T:19577 warning <general>: [script.module.inputstreamhelper] Recursively create directory '/home/ak/.var/app/tv.kodi.Kodi/data/userdata/addon_data/script.module.inputstreamhelper/temp/'.
2024-09-20 14:06:33.122 T:19577   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: '>' not supported between instances of 'LooseVersion' and 'Version'
                                                   Traceback (most recent call last):
                                                     File "/home/ak/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/default.py", line 8, in <module>
                                                       run(sys.argv)
                                                     File "/home/ak/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 15, in run
                                                       widevine_install(choose_version=params[2])
                                                     File "/home/ak/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/api.py", line 48, in widevine_install
                                                       Helper('mpd', drm='widevine').install_widevine(choose_version=choose_version)
                                                     File "/home/ak/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 34, in clean_before_after
                                                       result = func(self, *args, **kwargs)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/ak/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 219, in install_widevine
                                                       if not self._supports_widevine():
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/ak/.var/app/tv.kodi.Kodi/data/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 163, in _supports_widevine
                                                       if parse_version(config.WIDEVINE_MINIMUM_KODI_VERSION[system_os()]) > parse_version(kodi_version()):
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: '>' not supported between instances of 'LooseVersion' and 'Version'
                                                   -->End of Python script error report<--

Anybody an idea how to fix?
is it maybe a flatpak issue?

**Comment by Sandmann79** [comment]
This is not an error of the addon, but of the Input Stream Helper Addon.
Please create an error report there.

**Comment by lagweasel** [comment]
For the record, looks like someone else already raised this with InputStreamHelper here: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/570
