### ISSUE TITLE
Videos can't be played if the manifest doesn't have the audioTrackId tag

### ISSUE THREAD

**Issue by Uukrull** [Sandmann79/xbmc#765]
**Addon used**
- [x] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware: Shield TV
- OS version: Latest beta
- Kodi version number: Kodi 22.0-ALPHA1 (21.90.700) Git:20241106-f9ea21c1a1

**Upload Logs**
[kodi.log](https://github.com/user-attachments/files/17678638/kodi.log)

**Describe the bug**

The videos can't be played if the manifest doesn't have the audioTrackId tag. Here are the unmodified manifests for 5 movies:
[manifests.zip](https://github.com/user-attachments/files/17678688/manifests.zip)

The only one I know for sure is in the German Amazon is [The Betrayed](https://www.amazon.de/-/en/Zulumoke-Oyibo/dp/B0DJR3KLBX)

The others are from the Spanish Primevideo:

[Pedro Ruminot: Come One at a Time](https://www.primevideo.com/detail/0OAPTYYZ183EO70A5NFYIAF86U)
[Nokturno](https://www.primevideo.com/detail/0H8UPP2HGPIVM1JFXNTE4Z61HP)
[Itzia, Tango & Cacao](https://www.primevideo.com/detail/0LC81B6XGDMIEGX98QFF69FP3F)
[Santos](https://www.primevideo.com/detail/0FBDIQM7BA1C38YFMV1XJF3KCF)

They have in common that only one language is available for the audio tracks. With the latest master, this is the error I get:

```
2024-11-08 13:29:21.838 T:12197   error <general>: Exception occurred during processing of request from
2024-11-08 13:29:21.838 T:12197   error <general>:  
2024-11-08 13:29:21.838 T:12197   error <general>: ('127.0.0.1', 48464)
2024-11-08 13:29:21.838 T:12197   error <general>: 
                                                   
2024-11-08 13:29:21.842 T:12197   error <general>: Traceback (most recent call last):
                                                   
2024-11-08 13:29:21.843 T:12197   error <general>: 
2024-11-08 13:29:21.844 T:12197   error <general>:   File "/data/user/0/org.xbmc.kodi22/cache/apk/assets/python3.12/lib/python3.12/socketserver.py", line 692, in process_request_thread
                                                       self.finish_request(request, client_address)
                                                   
2024-11-08 13:29:21.845 T:12197   error <general>: 
2024-11-08 13:29:21.845 T:12197   error <general>:   File "/data/user/0/org.xbmc.kodi22/cache/apk/assets/python3.12/lib/python3.12/socketserver.py", line 362, in finish_request
                                                       self.RequestHandlerClass(request, client_address, self)
                                                   
2024-11-08 13:29:21.845 T:12197   error <general>: 
2024-11-08 13:29:21.845 T:12197   error <general>:   File "/data/user/0/org.xbmc.kodi22/cache/apk/assets/python3.12/lib/python3.12/socketserver.py", line 761, in __init__
                                                       self.handle()
                                                   
2024-11-08 13:29:21.845 T:12197   error <general>: 
2024-11-08 13:29:21.846 T:12197   error <general>:   File "/data/user/0/org.xbmc.kodi22/cache/apk/assets/python3.12/lib/python3.12/http/server.py", line 436, in handle
                                                       self.handle_one_request()
                                                   
2024-11-08 13:29:21.846 T:12197   error <general>: 
2024-11-08 13:29:21.846 T:12197   error <general>:   File "/data/user/0/org.xbmc.kodi22/cache/apk/assets/python3.12/lib/python3.12/http/server.py", line 424, in handle_one_request
                                                       method()
                                                   
2024-11-08 13:29:21.846 T:12197   error <general>: 
2024-11-08 13:29:21.846 T:12197   error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi22/files/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 228, in do_GET
                                                       self._AlterMPD(unquote(path[1]), headers, data)
                                                   
2024-11-08 13:29:21.846 T:12197   error <general>: 
2024-11-08 13:29:21.846 T:12197   error <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi22/files/.kodi/addons/plugin.video.amazon-test/resources/lib/proxy.py", line 382, in _AlterMPD
                                                       newLocale = self._AdjustLocale(trackId[0], langCount[self.split_lang(trackId[0])])
                                                                                                  ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   
2024-11-08 13:29:21.846 T:12197   error <general>: 
2024-11-08 13:29:21.846 T:12197   error <general>: KeyError: 'en'
```

**Comment by Sandmann79** [comment]
With https://github.com/Sandmann79/xbmc/commit/8af7185279b5dc8c465f878f89d84eca644eae39 it should work as expected. Thanks for looking for a German movie to test.

**Comment by Uukrull** [comment]
Yes, it does. Many thanks!
