### ISSUE TITLE
TV Show Folders empty

### ISSUE THREAD

**Issue by Forlorn-Hope** [Sandmann79/xbmc#767]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 1.1.4

**Account type**
- [ ] primevideo.com
- [X] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:Intel NUC i5
- OS version: Librelec 12.0.1
- Kodi version number: Kodi (Omega) v21.1

**Upload Logs**

**Describe the bug**

All TV show folders are empty.  When I go to the following   My Stuff -> Watchlist -> TV shows or All, any TV show folder after, it is empty.  If it has more than 1 season, then the season folders are listed, but are empty within.  Here are some examples:

My Stuff -> Watchlist -> TV shows -> The Source -> empty
My Stuff -> Watchlist -> TV shows -> Murdoch Mysteries -> Season X -> empty
My Stuff -> Watchlist -> All -> Cross -> empty

This began after Amazons most recent Prime Video interface "upgrade".

[logfiles_20241117-091413.zip](https://github.com/user-attachments/files/17791570/logfiles_20241117-091413.zip)
[20241117_091339910951_29.json](https://github.com/user-attachments/files/17791571/20241117_091339910951_29.json)
[kodi.log](https://github.com/user-attachments/files/17791572/kodi.log)
[html.log](https://github.com/user-attachments/files/17791573/html.log)

**Comment by Vichman67** [comment]
Similar issue applies to me, but with these differences:

- Account type: primevideo.com
- Hardware: Raspberry PI 5 with LibreELEC 11 and also notebook x64 i7 with Ubuntu 22.04
- Kodi version number: Kodi (Nexus) v20.3 & 20.5

But what I can not list is My Stuff -> Watchlist -> Movies or All.
I can list and wath my TV shows.

From Kodi log I see there is a problem with character enconding - or so it seems to me:

```
2025-03-08 18:47:42.946 T:1553     info <general>: [Amazon VOD] Version: 1.1.4+matrix.1
2025-03-08 18:47:42.946 T:1553     info <general>: [Amazon VOD] Unicode filename support: False
2025-03-08 18:47:42.947 T:1553     info <general>: [Amazon VOD] Locale: en-us / Language: es
2025-03-08 18:48:11.831 T:1556    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnicodeDecodeError'>
                                                   Error Contents: 'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 1438, in _LazyLoad
                                                       seeMore = cnt['viewOutput']['features'][wl_lib]['content']
                                                                 ~~~^^^^^^^^^^^^^^
                                                   KeyError: 'viewOutput'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 9, in <module>
                                                       EntryPoint(argv)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 67, in EntryPoint
                                                       _g.pv.Route(verb, path)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 184, in Route
                                                       elif 'browse' == verb: self._g.pv.Browse(path)
                                                                              ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 458, in Browse
                                                       node, breadcrumb = self._TraverseCatalog(path)
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 154, in _TraverseCatalog
                                                       self._LazyLoad(node[nodeName], pathList[0:1 + i])
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/web_api.py", line 1453, in _LazyLoad
                                                       t = json.loads(base64.b64decode(q['serviceToken']))
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/usr/lib/python3.11/json/__init__.py", line 341, in loads
                                                   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte
                                                   -->End of Python script error report<--
                                                   
2025-03-08 18:48:11.938 T:1560    error <general>: GetDirectory - Error getting plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/watchlist/movie
2025-03-08 18:48:11.939 T:990     error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.amazon-test/pv/browse/root/Watchlist/watchlist/movie) failed
```

I'm using an account for Amazon Prime Video from Spain.

Any idea?

Thanks!

**Comment by Sandmann79** [comment]
@Vichman67 Your issue is related to #775. An update is coming soon.

**Comment by Vichman67** [comment]
> [@Vichman67](https://github.com/Vichman67) Your issue is related to [#775](https://github.com/Sandmann79/xbmc/issues/775). An update is coming soon.

Thanks a lot. I'll keep an eye on #775...

**Comment by Forlorn-Hope** [comment]
Wanted to give an update.  I installed the latest version, 1.1.5, and my issue has changed a bit.  I cleared both caches, and restarted.  When I go into My Stuff -> Watchlist -> TV shows or All, any TV show folder after, it appears to be loading, but then I receive an corrupted cache error, and the folders are blank.  If I back all the way out, and then refresh , some of the folder posters will appear, the rest will just show the names.  If I go into a show with multiple seasons, it will only show the season folders as like amzn1.dv.gti.hnw947-tbilyhtoy-hjs53rgkbei74.  When opening that folder, it is empty.  Just another datapoint.  Please find the logfiles attached.

Thank you for your labors.

[logfiles_20250323-114219.zip](https://github.com/user-attachments/files/19410100/logfiles_20250323-114219.zip)

**Comment by macin2442** [comment]
I seem to observe similar issues on LibreElec 12.0.2 with Kodi 21.2.0 and Amazon VOD 1.1.6+matrix.1. TV shows with multiple seasons typically list episodes for season 1 but not for most of the other seasons. Most of the other seasons do not show metadata nor do they list any episodes. For Big Bang Theory for example season 1 and season 10 show episodes. This seems to be stable across cache clearings. I activated pagination for everything without effect. kodi.log does not show any errors.

Without in-depth knowledge: The relevant json seems to be [20250430_193722500518_15.json](https://github.com/user-attachments/files/19984155/20250430_193722500518_15.json). It contains for example S01E01 "Penny und die Physiker" but not S05E01 "The Skank Reflex Analysis". Same holds for the corresponding html. In fact none of the debug htmls or jsons contain the term "Skank". Please let me know how to approach debugging this.

**Comment by andrewbird** [comment]
I'm seeing this same issue also with libreelec 12.0.2 but with vod 1.1.8. I can however go to the enclosing folder, refresh and then the seasons get populated. I wonder then why it didn't work initially, perhaps a slow load and timeout?
