### ISSUE TITLE
Addon only works if 'Enable Subtitles' is off

### ISSUE THREAD

**Issue by luis-esteve** [Sandmann79/xbmc#84]
In a Raspberry2, when I'm playing with Input Stream the addon works fine if 'Enable Subtitles' option is off. If 'Enable Subtitles' is on, then no movie starts. In the last case the log file shows this:

> 00:19:06.073 T:1606738816  NOTICE: [Amazon VOD] Convert Català Subtitle
00:19:06.087 T:1606738816   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe0' in position 25: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 3089, in <module>
                                                PrimeVideo_Browse(None if 'path' not in args else args['path'])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 461, in PrimeVideo_Browse
                                                PlayVideo(node['metadata']['video'], node['metadata']['asin'], '', 0)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 1583, in PlayVideo
                                                playable = IStreamPlayback(asin, name, trailer, isAdult, extern)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 1707, in IStreamPlayback
                                                opt='&titleDecorationScheme=primary-content', dRes=dRes, useCookie=cookie), retmpd=True)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 1965, in getStreams
                                                subUrls = parseSubs(data)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 2015, in parseSubs
                                                with codecs.open(srtfile, 'w', encoding='utf-8') as srt:
                                              File "/usr/lib/python2.7/codecs.py", line 896, in open
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 25: ordinal not in range(128)
                                            -->End of Python script error report<--

The full log is [here](http://ix.io/FAt)

My settings are:

- RPi2
- Latest Milhouse build #0208, 09-Feb-2018
- Addon: Amazon VOD 0.5.1
- Spanish account (primevideo.com)
- PrimeVideo Area: ROE_EU or ROW_EU (both have the same performance)

Thanks for this amazing addon

**Comment by Varstahl** [comment]
It has been fixed today in c8bebc95936897b824d9a15c87ef7ba852d21db7, but the update is not yet pushed to Kodi.

In the meantime, if you want, you can get the [default.py](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/default.py) from the main branch and manually overwrite it (`~/.kodi/addons/plugin.video.amazon-test/default.py`). That will provide both the fix and enhanced language recognition for the subtitles file.

**Comment by luis-esteve** [comment]
I've updated the default.py and the bug is fixed.
Thanks for the fix
