### ISSUE TITLE
Video won't play because of non-ascii character

### ISSUE THREAD

**Issue by gnekoz** [Sandmann79/xbmc#93]
Hi, I cannot play some video because of some non-ascii character in the description/plot of the video. The log looks like this:

```
20:51:02.864 T:1417098112  NOTICE: [Amazon VOD] Using Host: Akamai
20:51:02.869 T:1417098112  NOTICE: [Amazon VOD] checkURL: https://a17avoddashs3ww-a.akamaihd.net/d/2$c-HKLSg0XzJ6EFB9s1cetwivGPg~/ondemand/dub-dub-iad/7ff3/ca8b/edfb/4556-a227-6798d058b64d/de38c622-0492-4c57-9acc-dee2e701980d_corrected.mpd
20:51:03.732 T:1417098112  NOTICE: [Amazon VOD] getURL: https://a17avoddashs3ww-a.akamaihd.net/d/2$c-HKLSg0XzJ6EFB9s1cetwivGPg/ondemand/dub-dub-iad/7ff3/ca8b/edfb/4556-a227-6798d058b64d/de38c622-0492-4c57-9acc-dee2e701980d_corrected.mpd
20:51:05.654 T:1417098112   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 3150, in <module>
                                                PrimeVideo_Browse(None if 'path' not in args else args['path'])
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 472, in PrimeVideo_Browse
                                                PlayVideo(node['metadata']['video'], node['metadata']['asin'], '', 0)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 1588, in PlayVideo
                                                playable = IStreamPlayback(asin, name, trailer, isAdult, extern)
                                              File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 1749, in IStreamPlayback
                                                mpaa_check = xbmc.getInfoLabel('ListItem.MPAA') in mpaa_str or isAdult
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
                                            -->End of Python script error report<--
```
I was able to fix the problem adding a `decode('utf-8')` to the result of `getInfoLabel`.
Example:
`mpaa_check = xbmc.getInfoLabel('ListItem.MPAA').decode('utf-8') in mpaa_str or isAdult`

I also used `decode` on other lines where the title and the plot of the video are read

**Comment by Varstahl** [comment]
Thanks for the information provided, we'll make sure the cause of it.
